# Coming to America - A Prequel by Abhijit Sanyal {-}


When I finished engineering school and my management studies I did not harbor any thoughts of leaving my hometown – Calcutta and going abroad for any work or further studies. I was fortunate that even before I joined engineering college I had travelled widely in Europe, Middle East and Asia with my parents – so the “wanderlust” issue was not important. I wanted to work in Calcutta and stay in the same city with my parents and friends and family. 

I joined Dunlop India as a “Management Trainee” after my engineering degree from IIT Kharagpur (Indian Institute of Technology at Kharagpur) and was based out of the factory in a town called Shahgunge where Dunlop India maintained a sprawling factory spewing automotive tires and other industrial rubber products. The factory campus also included a huge township with very well maintained and manicured lawns, hospitals, club-houses and even squash and tennis courts. We stayed at the “Chummery” – a bachelor’s hostel and I went every day to the factory for some work, came back to play squash, tennis etc and then drinks at the club. In the weekends, we would go back to the city – on either the pool car or take a train. Life was comfortable but fairly boring. After less than a year of this – a group of about 10 of us – management trainees – all of us from IIT Kharagpur – decided that life had more to offer than making rubber products and we all applied for the fairly tough competitive examinations to the management schools – the Indian Institutes of Management. The results came in on a sultry summer afternoon of 1979 and we found that all of us were accepted – but in different schools across the country – Ahmedabad, Bangalore and Calcutta. The next morning – we all trooped in to the General Manager’s office starting at 8 AM in the morning at intervals of 30 minutes to submit our resignations. The General Manager – a short aggressive looking fellow by the name of Mr Gonsalves – told us later at our going away party – that he was expecting the whole “Chummery” to leave Dunlop by the end of the day. We got drunk over the next few days at our “success” in getting out of Shahgunge – not really knowing what we are now getting into. 

The two years for me at the Indian Institute of Management, Calcutta was a memorable period. The courses were fairly easy and straightforward and during placement time since I wanted a job that would allow me to stay in Calcutta – I joined “The Calcutta Electricity Supply Corporation” as a purchase executive in their headquarters at the Victoria House office. Victoria House was in the center of the city – a 6 storied imposing domed structure built during the 1930s. The name was taken from the Company's Holborn Headquarters, in London. The company was in the business of generating, transmitting and distributing electricity to the perpetually energy starved city of Calcutta. A “pucca British” company – it was founded at the turn of the century and its shares were till recently quoted on the London Stock Exchange. Tea was served in your office twice a day by liveried waiters and a three-course lunch was available daily in the officers’ dining room. It was interesting to see these dying vestiges of post-colonial British culture in an otherwise crumbling economic situation. I was also continuously reminded during our meetings and cocktail party gatherings that I was very privileged to be working there. Most of my colleagues were the scions of the very well-connected business and professional elite class of Calcutta. I was the company’s first few MBA hires – and was a corporate orphan since I came with no recommendations. 

I got bored there very quickly even though I had corporate perquisites like a car, club privileges and other such benefits. I hated the corruption, sloth and indifference around me. I also did not make much money since a large bulk of our compensation was in various perquisites – unlimited gasoline for example which would have a real perquisite in today’s world. In order to make really good money as I later found out – you had to join the dark side – which I was not yet willing to do. 

Calcutta and West Bengal was then in the grips of the Communist Party of India and continues to be even today. The general economic malaise combined with the lack of opportunity and the poor quality of life were all factors that prompted me to explore alternatives. I started frequenting the offices of the United States Education Foundation in India or USEFI – to explore the opportunity of doing a Ph. D in marketing or finance. Nearly 50% of my class at the Indian Institute of Management in Calcutta – had already left for the US or were in the process of leaving. The USEFI offices were then housed in a stately colonial mansion on Outram street. It was policed by a steely eyed woman called Kumkum Mittal and her factotum a reedy fellow called Ganesh. Mrs. Mittal interviewed you and then told you what your chances of being remotely considered for admission at any American university were and thereafter of your suitability of studying for the SAT / GMAT / GRE examinations in the air-conditioned comfort of the USEFI – which was a huge luxury in electricity starved Calcutta. Most of these preparatory books were not available at local book stores or were outdated. She was withering in her assessment of your prospects and political correctness was not what she practiced. 

I met her with some trepidation and filled out the form outlining my education and grades – which she reviewed and deemed that I was worthy enough to borrow the books and therefore study there. I gave the GMAT and GRE examinations – the fees for which were equivalent to a month’s salary. I initially applied to schools that did not require application fees since the standard application fee of $50 was for me a month’s salary. I was accepted at all of the few schools I had applied with offers of a fellowship and full tuition waiver etc. My mother very alarmed at the flow of steady mail from the US and came to know of my plans and was very upset. I shelved my plans and sent a polite regret letter to all those schools that had accepted me. This was before the advent of the personal computer and email and phone calls to the US were an unheard-of luxury. We did have a telephone in the house – which was used by all our neighbors and was even on the visiting card of one of them. Such was life in Calcutta during the late 1970s.

Two years went by and I was getting extremely frustrated at my job. I was in charge of purchase of steel and cement for building the company’s 240MW power plant – which was a major milestone for power-starved Calcutta and a huge achievement for the local government and the company. I was assisted by a couple of clerks and one administrative assistant. A team of four in charge of purchasing steel and cement you might ask – that is rather ridiculous. However, steel and cement were extremely valuable commodities in India in the 1980’s. There was a huge demand and tremendous short supply – which opened up opportunities for significant corruption. Even though there was domestic production of both these products they both had to be imported and I had to continuously manage my relationships with the Calcutta Port Trust, Shippers, extract permits from the Joint Plant Committee, get allocations from the Iron and Steel Controller (that is another story), cajole local suppliers etc., to ensure that they delivered the products they had promised to the construction site. I suspected that the imported products were also prized since there was lower probability of their quality being compromised on the way from the warehouses to the construction site. 

One of the byproducts of a construction of this magnitude was the large amounts of very valuable imported scrap steel that was generated. I sought permission from senior management and organized the sale of this scrap steel along the lines of an auction process – making sure that I extracted the maximum consumer surplus etc. (Remember I was one of the few IIM MBAs in the company!). The company profited enormously from this sale and this was recorded as one of the highest sales of scrap steel in recent company history. However, I sensed – that something was wrong and within the month of that sale I was sent to the “Gulag” – i.e., - I was transferred out of the luxuries of the head office and sent to the Central Stores and Garage – a hazy lazy place where nothing really happened and you just had to “Wait for your retirement” – I was told. “Retirement” – I was 27 years and that seemed that to be a very long wait. I do not have any proof – but I suspect that my transfer had to do something with the sales of scrap steel that I had organized. The volume and revenue from the sales of scrap had historically been very low – for obvious reasons since the surplus “not extracted” was otherwise distributed to the powers that be. 

I settled down to life at Central Stores – there was virtually no work and I used to go home for lunch, a two-hour long siesta. I also spent a lot of my time in the evening watching old black and white movies by Fellini, Truffaut and other movies by obscure Russian, Swedish and Czech directors at the Max Mueller House, British Council and the Alliance Francaise and other local movie halls. I had no girlfriend and did not even know how to acquire one – but that did not matter. Most of my friends still left in the city also did not have access to any female company. My Calcutta based friends were few and dwindling since most of them had either gone abroad or were working in other parts of the country.

One day I came to my office and found that the office and workers I was in charge, was closed and still not open at 8 AM. I asked the “Chowkidar” and the security personnel to open the office and get it ready for the day’s work. They said that there was a union meeting planned at that time and they were told not to open up the office – till the head of the local branch of the union instructed them to do so. I told them – that I was running this office and not the union and they reluctantly opened the office and the warehouse. At about 8.30 there was huge commotion outside my office and I looked outside my office windows which was on the second floor to see that about 100 workers had gathered in the courtyard below and led by the local union leader, were all yelling – “Sanyal Sahib Murdabad”, “Sanyal Sahib – Nipath Jao”. It did not take long for me to realize their ire was obviously directed at me and was loosely translated as “Death to …” and “Go back…..” The local police force was called –  and after an hour of protest and more death threats I was spirited out of the back door and was told to go on administrative leave for a week.  I was later charmed by the fact that even though they wanted me to murder me – they would still attach the honorific – “Sahib”. 

After nearly 4 years at this job – I thought it was now time to think of other alternatives. Opportunities in Calcutta were non-existent and based on my judgment and most of my friends I possibly had the best job in the city given my education and values. I could not argue with that – since I had a car, some nice perquisites (a gasoline allowance among other things), a nice salary and no work. I started writing to business schools in the US expressing an interest in applying for a Ph.D. program. My mother distressed at the resumed flow of large envelopes from the US filled with glossy brochures and forms told me that I had to get married – which I did in the winter of that year. I had to again put a hold on my plans and asked my bride to be during our first conversations (at the local tea-room called Flurys) whether she would be willing to move to the US if I decided to leave for further studies. As far as I can remember she agreed. 

After my wedding, I went back to Kumkum Mittal and USEFI and started preparing for the GMAT / TOEFL examinations and again applying to US universities. I also bribed the postman (compromising on my value systems) to ensure that my mail would be delivered regularly and not stolen because of the US stamps.  My marriage and honeymoon expenses along with the subsequent application and examination fees had depleted my meager savings. I was accepted at a few US universities along with offers of a fellowship and tuition waivers. The fellowship stipend seemed rich – once translated into the weaker Indian currency. I went and perused the 2 months old New York Times and other US newspapers to determine the cost of living from the grocery store sales and coupons that were still available. I kept a detailed chart of these costs and was able to determine that even eating shrimp everyday and a glass of wine – I would still have $50 left from my fellowship stipend. Life would be good – studying, eating shrimp and drinking wine – no militant unions and recalcitrant office “babus” to handle.

Soon after I also came to know that my wife was pregnant which now definitely complicated matters, throwing all my shrimp and wine calculations awry. I wrote to friends in the US to determine my chances to survive (now with a family) on the fellowship amounts. Most of these letters would take about 2 to 3 months to get a reply. Some of these replies came after I had left for the US. 

Finally, my visa papers arrived, and I went to the US consulate for issuance of a student visa. A woman called Laura Livingston was in charge of issuing visas. She had a reputation of terrorizing the local “US aspirants” with her ability to withhold or issue student visas. The local grapevine had rumors of what were her decision criteria – which were according to most people who went through the experience, fairly arbitrary and ambiguous. My interview with her was for about 5 minutes. She asked where I had studied in India and what my GMAT score was. She then asked me whether I was going to ever come back to India. I said – “I am going to try – but I can only give you a hypothetical answer”. She replied – “I do not think you will ever come back – you will very much enjoy studying and staying there in the US”. I left the consulate with my visa and grim forebodings. 

I flew out of Calcutta airport on a gloomy monsoon night in end August 1987 en-route to New York. There were tears all around and in spite of my assurances to my parents they felt that I was abandoning them. I had tried for 10 years after finishing my engineering degree to build a career in India but could find little to look forward to or hope for. 

I had with me about US $250 after cashing out my retirement savings which was also the maximum that the Indian government would allow. That would be about 2 weeks of living expenses at rates well below US poverty levels. Throughout the long plane ride – I thought - how do I bring my wife and unborn child to join me and .... what next?