# Penurious Graduate Student by Abhijit Sanyal {-}

My old expired passport has on page 15 – “Sept – 5 – 1987 – Admitted” over the full signature of “Laura Lee Livingston” – consular officer of the US Consulate General, Calcutta. I arrived at JFK airport on 5th September 1987 after a long flight from Delhi on now defunct Pan Am Airways. A friend of mine who received me at the airport – and I spent a night at his apartment in Manhattan. The next day he drove me and my two puny suitcases to the University of Massachusetts at Amherst. He knew a professor out there who was also in the business school and he decided to meet him as well. On the drive to Amherst – we drove through all the places that I read about – Pelham, Greenwich, Stamford, New Haven and Hartford. I noticed that as we went through the toll booths – he greeted and was also being greeted equally vocally by the toll booth collectors with a big “Hello” and a few seconds worth of conversation. I asked him if he personally knew the toll booth collectors – and he said “No” – “This is the US – there is optimism everywhere”. It seemed to me that the sun never sets in this country.

I joined the business school thereafter and started getting busy with classes and some other “Fellowship” responsibilities. I talked to my wife as much as I could afford, long distance calls were very expensive. I placed my name in the queue for the University married students housing. There was considerable demand for this housing since the rents were cheap – but the waiting list was over a year long. In the meantime, I arranged to rent an apartment at a housing complex called Puffton Village.

I witnessed my first New England snow fall during the month of October 1987 which everybody said was very early for that time of the year. I still remember working in the Computer Lab room and looking out of the window as the snow started to fall. In the next few hours everything was covered in white and what was previously ugly now looked beautiful and what was beautiful was now absolutely magical. I marveled at the snow and still remember walking back to my graduate dormitories, with my feet completely freezing. I still had not bought any winter clothes and I still had my new shoes from India made by the famous Indian company – Bata. Within a few days the soles of the new “Bata” shoes came apart completely and I desperately needed new shoes. I went to a local thrift store and bought winter shoes. My professor friend from Albany called me one day to check how I was doing and I told him that I never realized that winter would be so severe. He came the next weekend and he took me shopping to “Steigers” and bought me nice warm “London Fog” coat. Steigers was a fancy store at the mall but is no longer in existence, a victim of the creative retailing destruction that continuously goes on in the US.

I also arranged for my wife’s visa papers. I was nervous that the “Visa Gods” in Calcutta might deny her a visa since she was pregnant and advised her that she should wear loose clothes, so that her condition was not immediately discernible. She said that she would try, but she also said that it was getting very obvious that she was expecting. The first time that she went to get her visa she was denied. She tearfully called me and said that they wanted some confirmation from me that I was a genuine student at the University. I ran to the International Student Office and explained my situation to Fred Schulten – the student advisor and he promised to send a message to the US Consulate General’s office in Calcutta. The next time she went to the visa office, she was awarded the visa and she arrived just before Thanksgiving, 1987 to the JFK airport at New York. I received her at JFK and the next day we boarded the Peter Pan service that ran from the Port Authority to the town of Amherst. I did not have a car and I asked a friend of mine to receive us at the bus stop. I did not realize that it would be getting bitterly cold and his car – an old Volkswagen Beetle had as he described it “Non-functioning heat”. Both of us froze but thankfully the trip was short. That would explain as to why my friend kept extra blankets and warm clothes in the car. 

We settled down to life at Amherst – I was busy with my classes and seminars and my wife was also busy making friends and finding out about groceries, how the bus system works and building relationships with the UMass medical system. I also started looking at my desperate financial situation. My fellowship stipend was $650 – out of which I had to pay $400 for rent and $100 for medical insurance that left us with about $150 for groceries, utilities and entertainment – which consisted mostly of meeting at friend’s houses for dinner or movies. Contrary to my expectations, life no longer consisted of affordable “Shrimp and Wine” that I thought would characterize my student life.

During one of my wife’s regular check-ups the nurse showed us the ultra-sound results on the screen and told us that it was a boy – “See you can see his weenie!” and we squirmed in our Bengali middle class embarrassment. There was now a concern whether the medical insurance would cover the birth of our child – since it was a pre-existing condition. I researched the issue and found out at the average cost of a child birth was about $30,000 but if you were indigent then the Commonwealth of Massachusetts might pay for the cost. We did the round of all the doctors and the other officials – but nobody could give us a clear answer. One night a few weeks into her stay while returning from the local mall sitting in a bus on Route 9, my wife very excitedly pointed to a blinking neon sign in red – which said, “FAST FREE DELIVERY”. [Psychology – when you are hungry everything points in that direction] She said that should surely solve our problems. I reassured her that it would not. The sign was for a local pizza shop and they would not take responsibility for the birth of our child.

In the meantime, I was thinking of ways that I could earn some extra money to alleviate our dire financial situation. The baby was on its way and we needed a crib, a stroller and other “baby” stuff. We had no furniture except for a mattress donated by a friend which we used for sleeping. A friend in the Ph.D. program got a job and donated his sofa set to us. The sofa had unfortunately one leg broken and I had to somehow prop it up and had to warn visitors to our home not to lean too much on the “broken” side. I bought a desk and some chairs from a used furniture store. My academic advisor donated his child’s crib to us. We painted it and it looked like new. I could not work legally anywhere outside the campus and most on-campus jobs would conflict with my classes and academic schedule. Somebody however said that they needed tutors in the minority education program and I applied there. The pay was $10 per hour and you had to make appointments with your students and help them with their homework and classes. I started teaching these students multiple subjects – Mathematics, Physics, Chemistry, History and Psychology etc. A young girl once came to me and said that she needed help in French. I drew the line there since with my full course Ph.D. program workload I did not now want to learn a new language. In a very mildly entrepreneurial fashion I would organize three to four students together in a single hour session and teach them simultaneously various subjects. There was no rule that said that I could not do this and over the next few months, juggling my classes and my students I was able to save some money with the ultimate goal of buying a used car.

We were poor but happy and the days seemed to fly fast. Winter had turned to spring and the birth of our child was due in end March or April. We went for Lamaze classes and the couples we met were all uniformly friendly and helpful. Since we did not have a car they volunteered to pick up and drop us off after the classes. Some of the male partners of these couples were also introduced as a “coach and a friend”. My wife would ask me – who is therefore the father and are they not married? I told her that it takes all sorts of people and relationships to make the world. It was end March and I was busy with my classes and examinations and during one of Anuradha’s regular examinations the doctors advised us to go to the Cooley Dickinson Hospital at Northampton for a few check-ups and to make ourselves familiar with the hospital. The hospital was about a mile from the bus stop near Smith College and we had to walk the rest of the way there. There was about two feet of snow on the ground and it made for very heavy trudging to the hospital. I helped my wife walk the distance. I told her it was good exercise and she would enjoy the walk. Till this day she says that she has not forgotten that walk but hopefully she has forgiven me for making her endure that walk.

The doctors at the hospital after examining her said that she should be admitted immediately since the baby was on his way. She was admitted to the hospital and I went back to our apartment and brought her suitcase that she had very carefully packed in preparation for this event. She went into labor that night and our son, Aniruddha was born on the morning of April 2nd. We were deliriously happy and I held my son in my arms. I looked at my wife and she looked tired but was otherwise calm and at the same time exultant considering the labor pain she went through over the last eight hours. I wondered at the amazing process of child birth and what a miracle I had witnessed. My wife told me that she had a list of people to call and I should go to our apartment and start calling these people. I thanked the nurses on duty and told them that I would be coming back in the next few hours. The nurse on duty said “There has been some more snow and the roads are slippery. Drive safely”. Smiling to myself, I thought that was not yet a worry for me as I trudged through the snow towards the Smith College bus stop.

