---
title: "03-Job-Hunting-During-A-Recession-Abhijit-Sanyal"
author: "Abhijit Sanyal"
date: "6/22/2020"
output: html_document
---

# Job Hunting During A Recession by Abhijit Sanyal

It was the summer of 1990 and we were on our way to Washington, DC for the annual American Marketing Association conference. The main objective of the conference was to act as a job market with employers – universities and business schools to meet and interview prospective employees – graduate students who were close to finishing their PhDs, as potential faculty starting in the fall of the following year. The business school had graciously decided to fund our hotel expenses for the duration of the conference, but we had to pay for own travel and meals. I decided to take my wife and our three-year-old son – we would  all stay in one room and have an opportunity for a low cost vacation. The hotel where the conference was being held was the Hyatt Regency Capitol – a grand hotel near the US Capitol and other Washington attractions.

We arrived in the afternoon after nearly an eight-hour drive from Amherst, Massachusetts. My old 1983 Toyota did not have very efficient air-conditioning and also had a leaking gas tank which would leak minute to alarming amounts of fuel depending on the incline of the slope where it was parked. The mechanic who used to repair my car said that the cost of repairs was higher than the replacement value of a car of equal vintage but assured me that it was very safe to drive. I decided to keep on driving it till it fell apart. I arrived at the hotel and noticed that there was valet parking. Our arrangements included hotel parking and I parked my car behind a silver Porsche 911 after dropping my family at the reception area. I handed the keys to the parking valet and told him that if possible he should avoid parking on a slope. He took the keys with a quizzical look. I did not explain the details.

The conference was interesting, and I met many potential employers including faculty from across the country and even as far away as the University of Waikato in New Zealand. However, the mood among the graduate students was very somber, unlike the buoyant attitude during last year’s conference at Boston.  There were rumors that all the schools and departments were interviewing prospective students but there was going to be no real hiring since most University funds and jobs were being cut back. However, in order to “keep face” the employers continued to meet “employees” in a comical hiring kabuki dance. We had a great time in Washington, saw all the museums, the Lincoln Memorial, took pictures near the White House and drove back to Amherst with the hope that I would be employed within a year during the Fall of 1991. That would mean a befitting end to our current poverty-stricken way of life and many years of struggle.

That did not happen. The recession of the 1990’s wiped out most potential academic jobs in 1990 except at the top research-oriented universities. The next year in 1991, I went to the AMA conference in San Diego and again interviewed with many universities. In anticipation of a job in the fall of 1992, we had even planned our second child to coincide with an expected upsurge in our income that year but that did not happen.

Ever optimistic I went in 1992 to the AMA conference which was held in Chicago that year. My wife Anuradha was pregnant with our second child and was due on any day. I returned home on the night of August 11th but my flight was delayed. I called from the airport and my wife said that her “water had broken” and she was going to the hospital with her friend. I hurried to the hospital as soon as I landed and our second child – “Ayan”anghsa was born during the early hours of 12th August, 1992. My wife asked me after we came back from the hospital as to how the interviews went and I said that I was very hopeful that we would be in a much better place during the fall of 1993.

That did not happen either as none of the universities that I had interviewed that year called me back. I was living the adage – “The rich get richer – the poor get children”.

I had finished all my course work and my qualifying examinations by 1991. I had also completed most of my dissertation work and was ready to defend my thesis but without a job and a completed thesis, I would be “out of status” and would have to leave the country according to the immigration rules. I continued to be a student and the department chair, and the university authorities graciously continued to extend my fellowship which meant that I could continue to take classes across the university departments. I started taking courses in the departments of psychology, mathematics and engineering. In order to earn some extra money since I could not work outside the campus, I also started consulting at the statistical consulting center (SCC) which was attached to the Department of Mathematics and Statistics. The SCC was set up to help the student and academic community with all their statistical programming and software problems and applications. I had some experience in using statistical software through regular coursework, but it seemed that there were few takers for the job – so I got the position and was soon very busy working there or taking classes.

After 6 months into the job – I was approached by a few graduate students who said that they needed help with the analytical work on their Ph.D. thesis. They were worried that they could not defend or graduate until they finished all the required analytical work. They offered me reasonably handsome sums if I would “consult” with them on completing their Ph.D. requirements. I had now entered the shadowy world of “analytical gun for hire”. I readily agreed with their request but told them they should inform their departments and their academic advisors that they were taking assistance from the SCC. I ended up doing most of the analytical work for their Ph.D. thesis and also wrote up the relevant chapters. I now think that there are at least three currently tenured faculty members who were able to graduate after I spend sleepless nights analyzing and modeling their data and writing up the results. C’est la vie.

One day during the month of March, 1993, our supervisor at the SCC – Trina Lemeshow said that there was a Boston based strategy consulting firm looking for statistical consultants and would I be interested in the position. She said that the salary was at about 9-month faculty salary levels. I leapt at the chance and applied for the position. The next day I got a call asking me to drive to Lexington for an interview. It was a wintry, snowy day in March and I drove to Lexington in my “leaky” Toyota. I spent an entire day at the offices of Mercer Management Consulting meeting about nearly everybody at the office and was entertained with a very nice lunch. Ever optimistic I started the drive back home to Amherst on route 2 in the late afternoon.

The snow was falling very heavily by that time accompanied by heavy winds. My windshield wipers were wiping away furiously as I crawled back home. Suddenly without any warning both my windshield wipers came loose from their moorings and continuing their furious back and forth motion disappeared into the swirling heavy snow and the ongoing traffic. I pulled onto the side of the road and tried desperately to search for the errant wipers –but they were nowhere to be found. I ended up driving a few miles – stopping to clean the snow from the windshield and then continuing for the next few miles till the visibility had deteriorated to a point where I had to again repeat the process. As I was continuing this process, I suddenly heard a crack on my driving seat and the back of my seat fell back onto the back seat. It appeared that the driver’s seat of my Toyota had suddenly lost its “backbone”. I continued the “stop and go” process except that now I was driving hunched forward with my son’s car seat wedged behind me to give me support. A normal two-hour journey from Amherst to the Boston suburbs took me six hours that night. That winter storm of 1993 was one of the heaviest recorded snow falls in the history of Massachusetts. On the drive back home, I thought the god’s portent well for me – only out of such great pointless struggles can there be genuine achievements.

The next day I received a call from John, the head of the analytical group at Mercer, saying that they were ready to make me an offer and he went on to describe details with regard to the salary (which at that time seemed astronomical), signing bonus and other benefits etc. On hearing the salary, I blurted out that it seemed to be too high since I was told that this was a 9-month faculty salaried position. He ignored my comment and told me that if I accepted the offer over the phone they would start the paperwork. Anuradha standing anxiously next to me, signaled to me: “Say Yes – Accept the damn offer”. I accepted the offer and the next day all the paper work was completed, and I had a job to fulfill my vision of the American dream, about 3 years late.

We were very happy and celebrated by going for dinner in a Chinese restaurant in town and ordering regular food from the menu. We were not going to do the $9.95 buffet any more. The day I received the appointment letter, I took it to the local credit union and the Ford Mercury dealer and we purchased a mini-van in keeping with our demographic status as a single income family with two kids. I was also informed that Mercer had a dress code and my wife went into a pleasurable tizzy of shopping for suits, shirts and ties. All this spending was even before I received my first pay-check.

At school the graduate students and faculty members started asking me questions as to how I had got the job and whether I had any connections in the management consulting world --- ‘Mercer only hires from “Harvard Business School” and never from the University of Massachusetts’. I gave everybody different mysterious answers with reference to my Karma and the “leaky” Toyota. Even my faculty advisors were mystified and made oblique inquiries as to the salary levels and benefits. I only told them that the firm would be paying my moving costs as well as hotel expenses till we found a suitable apartment. I think that made quite a few people jealous, but I enjoyed the fleeting moment of perverse pleasure. It was worth a three year wait.

The movers called and asked me how much “stuff” I had. They asked me whether I had any horses or boats since they are only going to move one horse and one boat and two cars.  Rather flabbergasted, I said we had many books, all my academic stuff and toys and no furniture since all the furniture we had were hand-me downs or picked up from the dumpster and my wife did not want to take them. They seemed to be relieved that I did not have any horses or boats. The movers came – a group of heavily muscled large men and said that they would take care of everything. They literally did so and all we did was to pack enough clothes for a few days stay in a hotel till we signed the lease for our new apartment.

We moved from the hotel to our new apartment within my first week of work. The movers unloaded our stuff and arranged it to the best of their ability and my wife’s instructions. On the second day of our stay we notice a terrible smell coming from the kitchen. Further investigation revealed that the movers – who said that they would move everything, had also moved our garbage from Amherst to Lexington.
