# Shearing, shortening and embellishing your name - the American Way by Abhijit Sanyal

On October 19, 1885, the S.S. Eider approached Sandy Hook, New Jersey, and the Narrows, twelve days 
after it had departed Bremen, Germany.  Donald Trump’s immigrant grandfather, Friedrich Trump came abroad on that ship. He was processed through what was then known as the Emigrant Landing Depot where the state of New York processed immigrants before they began pursuing their American dreams. The Trumps in Germany had simplified their name from Drumpf and the immigrant recording ledger in New York records the barber’s apprentice name as Trumpf. Friedrich in pursuing his dream would soon discard the ‘f’ and the family name would become Trump. What an interesting uplifting journey for Drumpf as an awkard unpronounceable, name to the bold and convincing Trump, a word pregnant with decisive and overwhelming power as in “He has the trump card”. 

My name is Abhijit Sanyal and I am originally from the city of Calcutta, India. I flew into JFK airport on a PanAm Boeing 707 in the fall of 1987, not as an immigrant but as a potential one in the garb of a graduate student. PanAm is long defunct and most likely the aircraft has been long mothballed. I have always thought whether it is worthwhile to change my name to make it easier to flow on occidental tongues. Some of my friends and acquaintances have tried various approaches to make their names flow smoothly. 

Changing complicated names to single syllable ones is nothing new. In Bengal and Calcutta where I grew up, the British ruling Raj in encountering and working with the Bengali Babu changed many of their names. Bandhyopadya became Bannerjee, Chattopadhya became Chatterjee but mysteriously Gangopadhya never became Gangarjee but was reborn as Ganguly. Even the illustrious Thakur family’s name was changed to the mellifluous Tagore.

 In India, the most complicated names are most likely from people in the southern states such as Tamil Nadu, Andhra Pradesh and Karnataka.  Venkataraman would become Venky and Shridarahan was transformed to Shri, Rajaratnam would be referred to as Raj etc., A friend of mine whose name was Banawara Venkataramanya was popularly known as “Bunny” and I believe that is what was called out during his graduating convocation address. Even Gautama Buddha’s name Siddharth has been shortened to Sid – a short economical turn of phrase straddling the west and the east. 
 
Are economical poetic names powerful and important? Juliet’s argument to Romeo in the oft quoted lines from Shakespeare’s Romeo and Juliet:

“What's in a name? That which we call a rose.
By any other name would smell as sweet;” seems to suggest otherwise. 

However, Juliet was in love, young and inexperienced and their lives ended in tragedy. History is replete with the success and destructive power of short easy names. The exhortation of “Heil Hitler” gave birth to World War II, enormous devastation, countries annihilated, carnage and political upheaval on a global basis. Would “Heil Schicklgruber” work? That was the original family name of young Adolf’s father. If Adolf did not change his name, maybe the course of history would have been different.

I have a friend whose first name is my namesake – Abhijit combined with the last name of Biswas. In an effort to achieve cultural acceptability after his arrival in the US, he adopted the nom de guerre of Abe Bis. He was trying to make his last name one syllable. However even though he insisted his last name started with a B, some people would hear it as a P and he would encounter raised eyebrows and faint snickers. “You said your name was Abe Piss”. He soon changed introducing his name to Abe Biswas with the last name now its original two syllables. I have sometime thought that it would be a great idea to change my first name to Abe and ally myself with a towering figure of American history but Abe Sanyal really sounds desperate.

My two sons are Aniruddha and Ayanangsha. Both these names are tongue twisting multi-syllabic names too complex for time starved Americans. When they were born, I strongly lobbied for easily pronounceable names, but I lost to my wife’s family in Calcutta. This was also a family that had been seemingly blighted with a succession of wonderful daughters in the previous generation and the first grandsons’ in the family were auspicious occasions and welcomed with celebration. For naming purposes, venerated and distinguished astrologers were consulted, and the eldest child was christened Aniruddha. 

Aniruddha was Krishna’s grandson and the name itself means something that cannot be governed or restricted. I heaved a sigh of relief as there was a way out since Aniruddha could be shortened to Ani. As a child, Ani was extremely obedient and “governable”. 

The entry of the second male child, four years later was greeted with even greater joy and this time, I believe that there were frantic and increased efforts to choose a name that was a rare beauty, which aligned with the stars of this birth would bring prosperity and success to the new born child. All obstacles would dissolve at the very mention of the name. The choice was Ayanangsha. The name means “Pathway to the Sun”. 

My side of the family tried to have their choice of names accepted but they were all rejected. I argued as to why would this lovely baby want to go directly to the sun burning at 6000 degrees Celsius. It was all to no avail. Ayanangsha it would be.  Again, I saw a silver lining. Maybe this too could be shortened to “Ayan”. Ayan was actually quite ungovernable. I wondered that this was surely an odd cosmic shift or miscalculation in names and personality. 

My wife during subsequent doctor’s visit for the kids or herself would be greeted with confusion and questions of whether she was born in 1988 and she surely was not 8 years old? Sometimes it would be “This was your son’s appointment and why was he born in the 1960’s.” The Doctor’s office had mixed up the files of my wife Anuradha and my son Aniruddha. They sound the same and therefore they must be the same. Thankfully this was soon sorted out.

Later when the kids had left for college, my wife started a business dealing in handicrafts, ethnic Indian wear, garments and other gift items. She named her business – Anu’s Collection and over time we opened a website. One day while checking the website, we realized with horror that it was very hard to make the apostrophe in Anu’s collection really distinct. A friend of ours reported that if you searched for Anus Collection, then her website would turn up. This was during 2003, when Google’s algorithms were gradually increasing in sophistication. We hurriedly took down the website. I had visions of huge volumes of traffic from the gay community crashing all the servers and how to handle the hordes who would surely be disappointed by the range of the products and services available. We changed the name to Anuradha’s Collection. The same multi-syllabic problem remained unresolved or was this an opportunity.

My son last week was on New York local TV plugging for organ donors to register as it was National Organ Day. I winced as the TV anchor introduced him as Ani Sayal. Sayal in Bengali is very close to the word for fox. Ani later explained that they had rehearsed their line multiple times.
What is the motivation for brief, easy to pronounce names? I believe that it arises from the nervous energies of an immigrant nation trying to assimilate and unify people from multiple countries, religions, languages and traditions. It is the imagined America of great spaces and limitless opportunities, provided you are willing to work hard. To achieve that success, you cannot be tripped by complex multi syllabic names. However, I believe that as the US becomes increasingly diverse as result of demographic shifts, it may be more accepting of complex names. I do also believe that simplifying complexity will always be a well pursued and worthwhile goal which in the context of my previous statement may appear contradictory.

If Zbigniew Brzezinski can become President’s Carter’s National Security Advisor and the chief architect of President Obama’s foreign policy, I can try to remain Abhijit Sanyal. I do however respond to being called Abe with the hope that a minuscule amount of one of US’s most distinguished President’s by some method of cosmic transference might explain and illuminate my otherwise mundane existence.

