# Sounds and memories of my childhood by Abhijit Sanyal

The only sounds I hear in Lexington – are the hum of my computer and the occasional ringing sound when I get email or the reminder for another conference call and of course the ring tone of my cell phone or my wife’s. When I go outside I am greeted by the call of the birds in summer which is very soothing against the dull background roar of traffic from the nearby highway on route I-95.

My early childhood was in the city of Calcutta – now also known as Kolkata – a chaotic maelstrom of a city with now over 14 million inhabitants located in the eastern part of India. My father having served in World War II, left the Royal Air Force and joined Indian Airlines in post independent India. We initially used to stay at a long, gloomy and cavernous, multistoried building called Karnani Mansions near Park Circus. In the late 1950’s we moved to Ballygunge. I was then nearly 4 years old.

Calcutta was named the capital of British India in 1772 and the city grew to be subsequently called the “Second Capital of the British Empire”. The city then and possibly still is the largest and only industrialized city in the eastern part of India. The city’s relative prosperity and wealth continues to attract the population from the surrounding hinterlands of Bengal, Bihar and Orissa. Certain parts of the city were well planned, presumably during the British regime but grew up otherwise without much planning and thinking by the city fathers.

Memory and recall are complex and poorly understood topics. It is said that smells and sounds can trigger long lost memories and I wanted to determine how much of that would happen if I sat down to evoke these “sensory features”. This personal history of my childhood is based on the memories of what I can remember during my early childhood days and my boarding school days in Calcutta.

We had the sound of crows cawing all throughout the year. This was a constant cacophony then and still is. I suspect a city with little or no organized garbage system encouraged the buildup of nature’s scavengers. You would wake up with their incessant cawing and the patter of their feet on wooden windows and in our open verandah. They were rambunctious, bold and would enter the verandah and tangle with the laundry out to dry. The domestic help would run out to shoo them away, but they would invariably return.

During the monsoon it was the unremitting sound of the rains. When I would wake up it would be raining and when I went to bed in the night it would be still raining. The streets would fill up with water, the public transportation system would break down and schools would be closed. The only sound on the roads was the ting-a-ling of the hand-drawn rickshaws that were the only affordable means of transportation for the common person or the deep throated growl of the large trucks and jeeps that could navigate the waters. As a pastime I would make paper boats out and throw them into the streets from our second-floor window – to see them slowly unravel in the swirling waters and disappear in the drains. A large paper boat that I made out of stiff paper once was strong enough to withstand the waters and float out of sight. I used to imagine that it would go down the Calcutta sewers, down the Ganges and cross uncharted seas.

The other sounds were the sounds of all the various street vendors – each of would have their own characteristic “signature call” to attract customers. There was one fellow who would shout “Sil-A-Kattaoow”. This was the knife grinder who would sharpen your grindstone. Electrical grinders and mixers were not available, and most homes would employ a domestic help whose major chore was to use the “Sil” – a flat grindstone coupled with another cylindrical stone – “Nora” to grind up the fresh spices every day for cooking the day’s meals. The spices to be ground were put on the heavy 'sil' and were crushed by repeated movements of the 'nora', a smooth stone you held with your hands. We were lucky to have a refrigerator but, in most homes, including ours – fresh vegetables, fruits, fish and meat were bought cooked every day. Leftovers were taboo and to be given to the domestic help or the beggars. This was before the days of the cold chain, supply chain logistics and fresh sushi that we are used to in our current day lives. The “sil” and “nora” would lose their grooves over time and that is where the “Sil-A-Kattoow” would come in – or “Let me sharpen your sil”.

There was another fellow who would look for work to refill and fluff up your pillows and mattresses with fresh cotton and fresh cloth – a mattress reconditioning business. He would not use his voice but his instrument which was the shape of a single stringed sitar which he would then use to generate a twanging musical noise. The instrument was used to beat up the cotton and make it fluffier before refilling the pillows and mattresses. He would have a couple of young helpers with him. The domestic help would bring him in and after a long haggling process my mother would finally agree to the terms and conditions. He would rip open the old mattresses and throw out the old cotton – fluff up the new cotton to be refilled and sew up the mattress – which was now good as new. It was glorious to watch him work. There would be little flecks of cotton everywhere and I loved to see how he would use his instrument to whip up the cotton. I would compare that sight with a snow globe that I had, where the tiny figures of Santa Claus and his reindeers would come to sight when you agitated the globe.  That was the closest I came to see and imagine snow before the long harsh winters of New England.

The other sound was the “key and locksmith” man. He would yell “Chabi – Sharabein” – in other words – “repair your keys” and then follow it up with a magical jingle of a huge roll of keys and locks that he would continuously roll using his hands. I always suspected that this guy was in cahoots with the local goons to determine how to open the keys and locks of unsuspecting home owners when they were away.

Then there was of course the “Kwality” ice-cream man. At that time “Kwality” was the only reputed brand of ice cream sold in Calcutta. This gave birth to countless imitators who would sell their ice-cream as “Qwality”, “Quaality”  and so on and so forth. The genuine “Kwality” man wore a branded uniform and cap and was very conscious of the value of his brand. He would shout the name of his brand – “Kwality Ice Cream” to attract his customers. We would look out to the street and try to determine if it was the genuine brand or one of the many imitators. If my mother confirmed that it was genuine, she would then allow us to get our ice-creams – a “Tutti Fruiti” for me and a “ChocBar” for my sister.

Recycling was not only executed by the crows. There was also the scrap paper man. His signature call was “Poorano Kagoj, Boootle Bikri”. This translated to “Want to sell old newspapers and bottles”. His role was to buy old newspapers, bottles and containers. This was a long awaited once every 6-month ritual since the money was used to replenish our ice-cream allowance. I suppose it also took that long to accumulate sufficient materials to recycle. A modern-day testimony of our increased levels of consumption and consequent increase in recycling materials is that we now have to recycle every week. My mother would send for the domestic help to bring him in and she would agree to trade only after negotiating rates. There were different rates for Bengali vs. English newspapers – I am still not sure why. Was it the quality of the paper and newsprint ink? These newspapers were all recycled into paper containers and were used to bag everything from groceries to sweets and candy. Newsprint has since faded from that role with the advent of plastic and polypropylene bags.

At this point my uncle who was then staying with us – would immediately ask that the vendor’s weighing scale be examined – since ‘these guys are always trying to cheat us”. After his scales were examined to satisfaction, we would bring out the old newspapers, magazines, bottles etc. We would not trade the “Time” or “Life” magazines that my father would occasionally buy. These were premium products, which the vender would invariably ask for. The vendor would also ask if there were any “Foreign Liquor” bottles – again a very premium product. He would then weigh the newspapers, count the bottles and containers and total up the amount he owed us. He would then give my mother the money and we would all feel proud of having executed a complex deal and feel very rich for a few moments.

The other recyclers were the so-called merchants dressed in riotous colors from Rajasthan who would exchange your old clothes for stainless steel utensils. These were very complex transactions since the deal values were significantly higher and would take the better part of a day to complete. I do not remember their war-cry – although I am pretty sure they had one. There were also the beggars and the occasional professional mendicants each with their signature tunes. Some of the newspaper money was reserved for them as well.

Many of these sounds have disappeared in Calcutta and possibly their associated professions as well. During my trips to Calcutta – I always try to search for these sounds. During my last trip to Calcutta – the “Kwality” ice-cream man came around one day and the flood gates were released, and memories rushed through my mind. I enthusiastically offered to buy ice cream for my young nieces, but it was declined. The refrigerator at home had enough ice cream and anyway they preferred going to the ice cream parlor at the Mall. 
