# To oblivion and back by Abhijit Sanyal

The call came when I was down to running my last mile. I noticed the caller was Brigham and Women’s’ Hospital (BWH) and I immediately pressed the answer key. It was Kristen, one of the nurses at BWH and she said that the results of the pre-operation blood work had come back and I had to meet the Hematologist Oncologist as quickly as possible. With mounting anxiety, I asked “A Hemonc at this stage. Why what is going on?” She would not elaborate any further and with my heart now racing, I literally ran from the Willards Woods near my home in Lexington to the hospital.

My son Ani, was born with renal insufficiency, which meant that he did not have enough capacity in his kidneys. He was diagnosed with this condition when he was eighteen months old. The doctors said that he had about 60% capacity when he was born which would gradually decline over time and he may ultimately need a kidney transplant. Family astrologers were duly consulted on both sides of the family and there was unanimous agreement that this too shall pass. Comments ranged from “It was nothing to worry about” to “I do not see this in his stars”. Ani was on a bi-annual regimen of routine check-ups and blood tests and everything seemed to be normal. We were lulled into thinking that this too shall really pass. It did not.

Ani had a normal childhood and went to Lexington High School. He played soccer, was crazy about basketball, became a black belt in Karate and won the State debate championships. He was good in studies and secretly harbored a passion for hip-hop music and created “beats” with friends. He had a choice of colleges after finishing school - Carnegie Mellon, NYU, Boston College etc. but chose NYU due to the glamour of New York and its music scene. He became a New Yorker and in his final year in an assertive and independent move, shifted to a shambolic apartment in hip Brooklyn. Majoring in Economics and Finance, he worked for some time in a hedge fund and a consulting firm but then chose to concentrate full time on his music and also working as an English and Math teacher for the Harlem Children’s Zone. Ani’s kidney functions were inexorably deteriorating. 

I read everything about kidneys and its functioning over the years. We made sure that Ani received the best medical treatment. After all we were at Boston, the center of the universe as far as progress in American medicine is concerned. It was at BWH that Dr. Murray had pioneered kidney transplant in 1954 starting with dogs and then with the first human kidney transplant from a healthy male twin to another. This was the best place to be if we had to have a kidney transplant.  During our six-monthly check-ups, we would anxiously ask Ani’s nephrologist if he would ever need a transplant. He assured us with a “maybe” and we would go back to our lives pushing the dreaded thought from our minds. 

A key indicator of kidney function is the level of serum creatinine. It is an easily measured by-product of muscle metabolism that is excreted unchanged by the kidneys and measures above 1.2 being classified as abnormal. Throughout the first twenty years of his life Ani’s creatinine level ranged from 1.8 to 2.2. From 2010 his creatinine levels started increasing. In late 2011 there was a sudden jump in his creatinine levels. Ani’s nephrologist changed his tune and in early 2012, told us to prepare for a transplant and handed us over to the transplant team at BWH. 

Rather bewildered by the turn of events, we started mentally preparing for the transplant and who within the family would be the donor. I was the obvious choice since an earlier test had screened me as a potential donor due to the blood group and antigen match. My wife, Anuradha was not a match but our younger son Ayan was a potential donor. Ani’s condition deteriorated, and his creatinine was now higher than 8. He had recently worked on providing music for a Bollywood movie and they had invited him for the movie premiere and a tour of five Indian cities. He begged the transplant team at BWH for permission to do the trip which was reluctantly granted and in May 2012 spent 5 weeks in India with his mother in tow. He came back to New York and insisted that he was doing well but indications of incipient kidney failure were apparent. His skin had turned blackish green and the toxins in his body were causing occasional bouts of confusion and forgetfulness. The Bollywood movie was a dismal failure and sank without a trace in Mumbai’s murky celluloid graveyard.

He unwillingly closed his apartment in New York and came home to Boston where we had to rush him to hospital to install a catheter and prepare him for dialysis. The installation of the catheter was a major surgery done under anesthesia. Ani was in constant pain after the surgery and during dialysis. We felt frustrated that neither the doctors at the hospital nor at the dialysis unit were able to alleviate the pain.  

I was cleared for transplant by BWH in early August and was required to do a 24-hour blood pressure test. I also reduced my professional commitments and in theory became “unemployed” to focus on the transplant. We were given a surgery date of October 11th. The thrice a week dialysis was a bearable torture with the transplant imminent. However nearing end September, my nephrologist called me up and informed me that they were cancelling the surgery since I was now diagnosed with high blood pressure and an enlarged heart. We were all devastated but I was assured that with medications, the cardiomegaly could be treated and may be even reversed. 

I went into a frenzy of blood pressure reduction approaches. I started taking all my prescribed medications and started researching alternative methods. I completely went salt free in my diet. We went and bought a juicer and I started taking a glass of celery and apple juice concentrate which was “guaranteed” to reduce blood pressure in three weeks. My wife concocted a strong garlic, ginger and honey concentrate which I administered to myself twice a day. We heard of a lady who was a recommended expert in “relaxation techniques” and had worked with patients at BWH. We made an appointment and she heard our story and then started crying intolerably. Panicking, I was not sure who was the patient and who was the counselor and we tried to assure her that we were mentally strong and confident that we would achieve our stated goals. She gave me her relaxation tape which was a set of breathing techniques and positive statements that I was to listen and repeat every night before going to bed. 

I obsessively tracked my blood pressure every hour and entered all the data in a spreadsheet which I tried to link with time of day, diet and major and minor events, exercises and my daily running. I also knew that an individual’s ability to control blood pressure was difficult and unachievable. My blood pressure refused to become normal. All my Google searches and research appeared to be of no avail. 
After 6 weeks, we went back for another 24-hour blood pressure checkup and the transplant team gave us a surgery date in end November provided the independent committee set up to review the results gave me the green signal to qualify as a donor. I was refused, and the nephrologist and the surgeons started conversations to put Ani on the UNOS cadaver list and examine other options. Frustrated and disappointed, I redoubled my efforts. Ani went into a complete shell and refused to talk to any of us. Some nights I would cry myself to sleep and then wake up in a sweat during the night. 

Sometime in late November, my blood pressure indicators seemed to take a turn for the better.  Elated we went back to the transplant team and I was finally cleared as a donor with the surgery date set for the 20th December. We completed the “pre-ops” or the pre-surgery blood work and tests on the 11th December. I had to then meet various counselors whose tasks were to determine my motivations for undergoing the transplant and I was not subject to coercion or bribes. I was also assured that I could back out being a donor at any time and none of my family members would come to know the reasons of my decision! I told the nice lady that I was being paid a fortune in numbered bank accounts on the Comoros Islands and also my son’s first born male child (Swiss banks are so effete nowadays since they squeal to the IRS). She laughed nervously and asked me who made the decision in the family that you should be the donor. I told her “Father knows best” and we should leave it that.  

It was on the Thursday of that week, while running that I received the call from Kristen that I had to meet the “Hemonc”. The “Hemonc” – Jean reviewed my blood work and told me that there was no change of this round of results from the results done in July of that year. I found that reassuring and also mystifying and told her that any naïve person would reach the conclusion that there should be no cause for concern if two results across two points in time were the same. She said that even though my blood work had some very strange results which indicated that I have leukemia but since they were also “non-specific”, she was willing to give me the green signal for the transplant. I enlisted the help of a physician friend of ours, Sunita and we went through a series of conference calls with Jean and other doctors. Sunita explained that the words “non-specific” actually meant “I do not know what is going on”. I was told that the transplant team would be reviewing these results and would also confer with colleagues at Mass General Hospital and other local hospitals.

We started preparing for surgery and assorted cousins and relatives across the country made their travel plans to be with my wife during that time. On the evening of 18th December, I got a call from our nephrologist informing me that the team was not willing to take any further risks and was therefore cancelling the surgery scheduled for the 20th December. He also assured us that the counseling services at BWH were always available although to what intent was not clear. I asked him why they had not checked the results in July and why was this an issue now. He evaded my question and told me that they needed to do more tests to confirm that I had leukemia which would take another five weeks. 

 Crestfallen I told Ani of their decision and I mentally started to think of plan B – take Ani to India for a transplant where donors are available for a price or plan C which was for my younger son to become a donor. Ani who had become almost normal over the past few weeks shut himself in his room and refused to talk to us or get out of bed except for his dialysis treatments. 
 
I refused to believe that I had leukemia and started going for long early morning runs in the grey, snowy winter weather. I exhausted myself doing physical exercise and sometimes had to nap in the afternoon. Inwardly, I accepted that anything could happen and got my affairs in order. I prepared my will, made a list of the pathetic balances in my bank accounts, stocks, insurance policies, pensions etc., and put them in an envelope and told Anuradha where it was kept. She refused to know where it was and assured me that I did not have leukemia. It was a bleak Christmas and New Year’s. 

My wife in a fit of anger and frustration went and met the transplant surgeons who confided to her that they believe that they made a mistake in the whole process. They were also confident that it was very unlikely that I could ever be a donor. She requested them to start testing my younger son, who turned out to be a match in blood group and antigen combinations. 

On 3rd January 2013, my birthday we received a call from the Nephrologist who told us that the “leukemia” results were in and the transplant team would announce their decision tomorrow. The next day we were told that I was cleared for surgery for the 17th January. Elated, we went and celebrated at a Sushi restaurant. 

We reached BWH at 4 AM on the 17th January. The operating theatres were two floors below the ground of the main hospital building and connected by a labyrinth network of tunnels. There was a large crowd of patients, friends and relatives and the atmosphere was one of anxiety with a sense of foreboding. I told Ani that I think I am the happiest person here now and possibly the only person looking forward to surgery.

After a series of check-in procedures, we went into the pre-operating areas which were a hub of activity, milling with nurses, doctors, hospital gurneys and machines. The environment was that of a smooth well-run factory albeit with humans being processed in and out. We were now in regulation hospital gowns and we had a last conversation with each other before being wheeled into surgery. I hugged Ani and we wished each other good luck and the anesthesiologists took over. A young woman marked the left side of my abdomen with a green felt pen and administered the various intravenous entry points on my arms and asked me if I had any questions. I asked her whether they would be monitoring the different parts of my brain using scanners as it slowly shut itself off. I do not remember her answer as white clouds soon descended everywhere.  

 The next thing I remember, I was in the hospital bed with intravenous tubes snaking through my groin and the arms and my left side swathed in bandages. I saw the anxious faces of Ayan, Anuradha, friends and relatives.  My first question was where is Ani and the doctors said he was doing well and “peeing like a horse”. My wife said his creatinine level was down to 1.1. My uncle came to me and assured me that now my troubles were now all over. I apparently looked at my wife and said, “Not really, she is still around!” I do not recall this conversation, but everybody assures me that is what I said. I do not recall my wife’s reaction either.
 
I was visited by occasional intense pain and I had a pain-relieving pump which administered a controlled level of narcotics. The hospital room was a constant bedlam of doctors, nurses and physician assistants, who seemed to be in an endless cycle of giving me medications, measuring vital signs, drawing blood, turning me over and asking me what meals I wanted. There were also the constant beeps and alarms from the monitoring stations, the phones and pagers and the creak of the laundry carts and the sound of my door with each entry and exit. These noises were increasingly absorbed into my dreams and hallucinations and would keep me awake at odd hours of the night. 

Before the surgery, Ani and myself used to spend time watching a TV game show called “Deal-No Deal” where the contestant had to guess which unopened box out of 20 odd boxes contained how much money with the objective being to open the box with the lowest level of money and thereby leaving increasing higher amounts of money on the table to be claimed by the contestant. To entertain Ani, I used to calculate the expected value at each point of the game. Behind each box was a very beautiful woman who would open each one to cries of joy, despair and elation from the contestant and audience. In a recurring dream I was now the contestant wearing a hospital Johnny with nothing underneath and true to my ethnic subconscious, the 20 women were all now wearing beautiful white saris with red borders.  I would choose a box to be opened and it would be only $1 thereby increasing my expected value by $250,000 and I was screaming with joy and all the beeps, sounds and strobe lights were reaching an ecstatic level when my Johnny would come off and I was naked in front of 20 beautiful women …..The nurses were back for another round of checking on vital signs. 

Ani is back at work in NY. His maniacal drive and relentless energy to achieve his ambitions, I find somewhat terrifying. I constantly remind him to slow down and tell him that the odds are against him in the “winner takes all” music business. His colleague Max, in a strange twist of fate was diagnosed with lung cancer at the same time and had part of his lung removed to contain the disease. Their “Will To Win” music album which was a post-surgery effort was recently aired on MTV. He has also inked deals with Spotify and other music streaming companies. He tells me that his window of time is rapidly shrinking, and this kidney will last him at the most twenty more years. I wish him well. As long as I am alive I have no more kidneys to give him. Where this tumultuous journey will take us, and its’ unknown ports of call is anybody’s guess. 

Dr. Murray died on November 26, 2012, aged 93. He suffered a stroke at his suburban Boston home on Thanksgiving and died at Brigham and Women's Hospital, the very hospital where he had performed the first organ transplant operation.
 
