# The story of two Qasims by Abhijit Sanyal {-}

I was about 8 years old when we moved to Baghdad from Calcutta. My father was offered a position in Iraqi Airways and would be on leave from his original employer – the government owned Indian Airlines. We arrived in Baghdad in the winter of 1962 and I still remember the shock of the freezing desert winter in contrast to the mildly pleasant winters of Calcutta. Our house was in the old Railway colony near what is now the old Baghdad airport and close to the main railway station and the Presidential Palace. My father’s colleagues lived nearby, and my father’s office was at the airport – which was a 10 minute drive.

In the sixties Baghdad was a relatively modern city with wide clean boulevards, large palm trees, supermarkets and big American and German cars. The weather was very hot and dry in the summer with occasional sand storms that reduced visibility to zero and covered everything with a thick film of dust. The winters were severe with temperatures dipping to below zero and water pipes freezing, but there never was any snow. There were also movie halls that showed Hollywood and Hindi Movies. One particular open-air movie hall used to show Hindi movies all year long. These Hindi movies and their songs were very popular, and they were dubbed in Arabic for the local population.

Politically, Iraq was very unstable. The monarchy led by King Faisal was deposed in 1958 by an army General by the name of Abdul Karim Qasim who took over as the 1st Prime Minister of the Republic of Iraq. When we arrived in 1962 the memories of the 1958 coup was still fresh on everybody’s minds and the massacre of the royal family by Qasim and his men was a favorite topic of the cocktail circuit. The Prime Minister to the monarchy - Nuri as-Said - a man responsible for many repressive acts evaded capture for one day but was caught and shot after attempting to escape disguised as a veiled woman.  My father would discuss the history of the country and I would read about it during our visits to the British Council – the local intellectual watering hole. T.E. Lawrence’s adventures in “The Seven Pillars of Wisdom” were one of our favorite books along with the stories of Gertrude Bell – an English woman who in a certain way was responsible for the creation of the Hashemite dynasty in Jordan and the modern state of Iraq. 

Gertrude Bell was a writer, traveler, political officer, administrator, and archaeologist who between the years 1900 to 1926, travelled, explored, and mapped vast parts of Greater Syria, Mesopotamia, Asia Minor and Arabia. Through her extensive travel and contacts with the local tribes and the people she became very influential in shaping British imperial policy-making in post-World War 1 Middle East. At the end of World War 1, with the erstwhile Ottoman Empire in decline, she along with the ruling Arab tribes drew up the borders within Mesopotamia to include the three Ottoman provinces that became Iraq. Using her unique perspective and relations with tribal leaders she played a major role in establishing and helping in setting up the administrative infrastructure of the modern state of Iraq. She along with T. E. Lawrence (of Lawrence of Arabia fame) was held in high esteem by British officials and the local rulers. For a woman in her age and time, she wielded an enormous amount of power. She earned the sobriquet of “al-Khatun” or a “Lady of the Court” who keeps an open eye and ear for the benefit of the state. 

In 1963, Abdul Karim Qasim was the absolute ruler of Iraq but he was also loved by the common people. He was not very fond of the western powers and gravitated towards the Soviet Union. He also apparently seized land and assets from the British owned Iraqi Petroleum Company and distributed the land to the peasants.  The cold war was at its peak and the US and Soviet Union fought their wars through their proxies.  Within a few month of our arrival, Abdul Karim Qasim was deposed in a violent coup and I still remember the gunfire and small arms fire that we could hear from the nearby Army encampment. I also remember seeing aerial dogfights from the roof of our house and fighter jets dive bombing the Presidential Palace which was within viewing distance. My father did not go to work for a few days and Baghdad airport was closed. We later heard that many Iraqis were killed in a vindictive hunt that immediately followed the coup.  It was rumored that the coup against Qasim was motivated by the Bath party and interests that were against Qasim’s control of the petroleum sector and was carried out with the backing of the British Government and the CIA. Qasim was killed and our neighbors told us that his body was never found so he could not be given a decent burial. In November of 1963 there was another coup against the Ba’ath party and the previous regime was overthrown and a new government under the leadership of Abdul as-Salam Muhammad Arif took over the reins. 

After the situation had calmed down my parents had to find a school for us and my sister and I were enrolled in a local missionary school run by an order of French nuns. The medium of instruction was in French and I knew as much French as I knew Arabic which meant that I did not know either language. However, the school had a very large percentage of children of the expatriate population who were also equally clueless about the French language. Within a year however, both me and sister were fairly fluent in French and Arabic. I have since long forgot both languages – although I do recognize certain words and phrases. I also started to read and enjoy “Tintin” in the original French.  At about the same time my mother also hired a domestic help who was also called Qasim. Qasim was a tall strapping young man about 20 years of age who had never completed school. He was in need of a job and started working for us and other such families as a domestic help. He would come and help my mother with the dishes, cooking, running errands and also help my father maintaining our garden. An amiable fellow, he also taught me and my sister Arabic and provided us insights into the local people and politics. We in turn taught him English and over time he was able to converse with us in passable English. He would also help us during our regular parties which my mother had to host.  My father would give him a jacket and tie and he would serve drinks and appetizers. 

In 1964 an English language school was opened by a local British couple – Mr. and Mrs. Hartley. My parents withdrew us from the French school and we were admitted to Mr. Hartley’s school. Life was very good and interesting. I found school work easy and not as rigorous as I would hear from my cousins during our regular trips to Calcutta. I was also very interested in history and archaeology and the village and areas in and around Baghdad was full of unexplored verdant sites. Every two or three weeks we would visit these sites called ‘Tels’ such as Babylon, Ctesiphon, Ur, Mosul and other such locations and do our own unimpeded exploration and acquisition. Over the years I accumulated many pieces of artifacts that if I had now would be worth an illegal fortune, but I would also be accused of stealing national treasures. I am sure Gertrude Bell who founded the Baghdad Archaeological Museum would have approved of my scholarly pursuits, although not the acquisitive one.

Qasim was still with us. He had saved enough money to buy a big used Chevrolet Impala and drove that around for work. One day he came to work and looked very troubled. After some time he told us that he had been drafted into the Army and would have to leave work to join the training camp for 6 months. During that period his cousin - Ali would work at our house and he would come back to join our household after his 6 months training was over. Qasim left – my mother gave him a fresh set of clothes as a gift and he promised he would come back after 6 months. Ali, his substitute was not as diligent, and my mother had to spend a considerable amount of time training him to get all the household chores done.  

We were also getting used to witnessing abortive and a few successful coups and overnight changes of the Iraqi government. The common people were not very affected except there would be curfews and the occasional tank battles inside the army encampments. Occasionally we would get a premonition of an impending coup with the thinning of traffic and a mysterious sense of anticipation on the streets followed by a flurry of activity and movement of armored vehicles and Tanks from the nearby army base. My father would come back early from work and would talk about rumors that Baghdad airport may be closed for the next few days. The last one I remember was in 1966 when two tanks came and parked outside our street for some time. The tank commanders and the soldiers were very friendly and allowed me to enter the tank and sit on their seats. I still have the shell casing of a large caliber gun that they gave me as a gift. 

Qasim came back to work for us after his training was over and my mother was very relieved.  We were still attending Mr. Hartley’s school, but my parents were not happy about the standard of the teachers and level of teaching. In 1966 my sister was sent to a boarding school in Beirut. At that time that was the only boarding school for girls in the Middle East. My parents also contacted my old school in Calcutta and decided to home school me – so I ended up attending two schools – going to Mr. Hartley’s school in the daytime and then would come home and be home schooled by my mother based on the material that were sent every month by the Franciscan fathers of Don Bosco School, Calcutta. 

Every few months we used to visit my sister in Beirut and we would then drive to various religious and historical sites in Jordan such as Roman ruins of Balbeck, Jericho, Petra and various points along the Dead Sea. Beirut was a fashionable, cosmopolitan and sophisticated city – the “Paris” of the Middle East. You could ski on the snows of the resorts near Broumana and on the same day water ski on the Mediterranean. The West Bank, Jerusalem and Bethlehem were all then part of Jordan and I still have various artifacts from our trips. 

Qasim was still working for us and he also ran a small general store – financed by my father. He had to go back – once or twice a month to continue his military training. His life was improving, and he told my parents that he wanted to get married for which he was saving money. Marriage was an expensive affair since he as the male had to pay dowry to his prospective wife’s family.

By 1967 the war clouds were gathering again in the Middle East. In early May 1967, Qasim told us that he was again being forced to join the Army and would be sent overseas and this time Ali also would not be able to work as his substitute since he was also drafted into the Iraqi army. We bid both of them farewell and my mother gave them some gifts and Qasim promised that he would be back as soon as his unit was demobilized. 

In May 1967, Egypt expelled the United Nations Emergency Force (UNEF) from the Sinai Peninsula, which had been stationed there since 1957 to provide a peace-keeping buffer zone. In reaction to the Arab – Israeli tensions, Egypt amassed a huge number of tanks, armaments and soldiers on the border, and closed the Straits of Tiran to all ships flying Israeli flags or carrying strategic materials, and called for unified Arab action against Israel. On June 5, 1967, Israel launched what is commonly viewed as a pre-emptive attack against Egypt's Air force and completely wiped out the entire Egyptian and Syrian Air forces. Jordan, which had signed a mutual defense treaty with Egypt on May 30, then attacked western Jerusalem and Netanya. Iraq also publicly committed its units to the war effort. At the war's end which lasted for a few weeks, Israel had gained control of the Sinai Peninsula, the Gaza Strip, the West Bank, eastern Jerusalem, and the Golan Heights which were originally part of either Egypt, Jordan or Syria.  The Arab armies – Egypt’s and Syria’s along with a few units from Jordan and Iraq were routed and the Egyptian Air Force was wiped out.

We had no news from Qasim and our inquiries to Qasim’s family were to no avail – since they did not know his whereabouts either. One day in early August we were surprised to see Ali at our doorstep and my mother asked about his welfare and also about Qasim. Ali started weeping and then told us his story. Their unit which included both Ali and Qasim were sent to the Syrian border with Israel and were awaiting orders to enter Israel. However fearful that their own soldiers might turn against them, the Army command issued the soldiers weapons but without any ammunition. They did not enter Israel at all and when the Israel Army mounted an attack in the early hours of dawn – they abandoned their positions and fled on foot. Qasim was killed in the attack and Ali saw his cousin fall but never found out what happened to his body.

That same year, in 1967, Iraq severed diplomatic relations with the US and Great Britain. Mr. Hartley’s school was closed down. I was shipped off to a boarding school in Calcutta where I spent four miserable but formative years before joining IIT – an engineering college. My sister finished her schooling in Beirut and started university education in Calcutta. My father’s contractual obligations with Iraqi Airways ended in 1971 and he returned to Calcutta after a nine year stay in Baghdad.  
In July 2004 after the fall of Saddam Hussein’s government, Abdel Karim Qasim, the slain Prime Minister’s body was discovered by a news team associated with Radio Dijlah in Baghdad. His burial ground is a shrine and he is now viewed as a hero and saint by many Iraqis.
 
