# Hoar frost and the conscious universe by Dr Carl Von Essen {-}

Henry David Thoreau, in his winter wanderings around Concord, observed an unusually heavy hoar frost one morning.  He described it in his essay “The Natural History of Massachusetts”:

“Every tree, shrub, and spire of grass …was covered with a dense ice foliage, answering, as it were, leaf for leaf to its summer dress….It struck me that these ghost leaves, and the green ones whose forms they assume, were the creations of but one law; that in obedience to the same law as vegetable juices swell gradually into the perfect leaf , on the one hand, and the crystalline particles troop to their standard in the same order, on the other.”

Thoreau expanded these speculations to generalize that other phenomena or “natural rhymes” could “imply an eternal melody, independent of any particular sense.”

An eternal melody of nature? Played by what organist?

In his classic masterpiece, “On Growth and Form”, the Scottish biologist D’Arcy Thompson described the systematic self-similarity of anatomical structures in nature. He wrote, “Cell and tissue, shell and bone, leaf and flower, are so many portions of matter, and it is in obedience to the laws of physics that these particles have been moved, molded, and conformed….Their problems of form are in the first instance mathematical problems, their problem of growth are essentially physical problems, and the morphologist is, ipso facto, a student of physical science.”

His observations on this architectural evolution was later explained as forms of self-similar sets or fractals by the mathematician Mandelbrot in his “Fractals in Nature.” 

This evolution of thought began much earlier, perhaps when the Pythagoreans discovered and described the relationship of the harmonics of sound to whole numbers.

Our perception of nature is confined by the limits of sensation. Only our imagination can explore beyond those limits. But indirect evidence from cosmological research suggests marvelous discoveries that can transform our mundane lives. That the universe is alive is one such metaphysical discovery. It is increasingly verified by the calculations indicating the presence of previously unknown cosmic forces such as dark matter and dark energy, existing beyond our range of observing instruments.

The universe is a living presence. Following the chaos of the big bang, it is now possible to see order through the forces we now call the laws of physics, realized by the Pythagoreans and then formalized by the Platonists.

Consciousness did not appear suddenly in one species, Homo sapiens.  It has been there in some form from the very beginning.

Today, on our Earth, we, like Thoreau, can marvel at natural wonders and speculate on the forces that have created them. Since the very beginning of life, from the single organism that has led to us and to every living being, there has been an awareness; for being aware and escaping danger has allowed our archaic ancestors to survive, reproduce and evolve. These mind-like properties, a consciousness, is the consequential necessity for the evolution of life. 

Human discovery brings closer and closer our awareness that our universe is a living being, throbbing with an energy that governs all, an energy that we have not been able to measure, even comprehend, a consciousness which is shared by all life and matter. Thoreau’s hoar frost is such a manifestation.

 
