# Reaching the other side by Dr. Carl Von Essen

Occasionally I find myself looking at something and then have been surprised to realize that I am actually seeing it. As for example, standing on the edge of the Grand Canyon and “admiring the view.” This scene registers on my retina which transmits the data to the visual center in the back of the brain. The resulting mental image certainly evokes a pleasurable feeling, perhaps also an emotion of awe or even fear (what if I should fall off the cliff?). 

But then something else happens. The image opens wide, like the opening curtain of a play. I enter and become part of the scene, grasping the magnificence of the geological formation of the Grand Canyon, its colors, and its history. I have shifted from looking as a passive spectator to seeing as an active participant, mustering my mind to uncover all the bits and pieces of memories that relate to what I am now seeing.

These are the two landscapes of the Grand Canyon—one through the eye of the body, the other through the eye of the mind.  Henry David Thoreau coined an apt expression for the latter,” a sauntering of the eye.”  

This phenomenon happens to everyone. Most of us spend lots of time in looking, hearing, touching, tasting and smelling without fully appreciating what our senses tell us. Like spectators, we are largely looking at existence, rather than, as other animals and as plants are compelled to do, living in the moment, deeply involved with the objects of their senses, using all their experience, because often their lives may depend on it. 

Thus then is the difference between being an observer, recording an impression or gathering data, to being a perceiver, distinguishing differences, discriminating the sensory information and creating relational concepts. Indeed the word perception comes from the Latin, per-capere, to take or grasp through, that is, to actively seize upon an object or process such as an observation.

Of course, we so-called “enlightened” human beings have moved beyond the primitive need to only survive and reproduce; little need nowadays to be preoccupied with the whisper of wind or the sound in the forest that may warn of consequences of life and death. 

Indeed, with the distractions involved in living in our complex technological society, I readily lose attention and concentration and do not heed my senses, allowing them to slip by “unconsidered and unnoticed”.

Yet the wilderness still resides within through neural connections (engrams) that are hard-wired and inherited early in our evolution. My senses are still acute enough to tell more than I am generally conscious off.
A walk along the sea-shore, however, is an example of a sensory experience that triggers awareness, enriches mundane life and gives more meaning to what I am here for.

Smell is perhaps the most evocative of our senses. Next to touch, it is our most primitive sensation, closely associated with the emotional brain. The sharp, iodine-like smell of tidal flats can breach mysterious reservoirs of memories that have long ago been catalogued and stored away. The sense of smell can work like a light switch, a long-forgotten experience is immediately recalled when an uncommon, but immediately recognizable scent wafts past. 

Through vision, I see the clear pools in which delicate anemones, spiny urchins and starfish nestle, while tiny crabs, ignorant of my benign interest in their hiding places, scuttle away from my looming shadow Fronds of filamentous sea weed sway gently in the currents of the crevices and channels that are carved into the submerged rocky formations, creating images of beauty that stir primeval associations.
I hear the breaking waves and taste the salt that is scarcely different from the taste of my blood, a sensation that recalls the origins of all of us from the ancient sea.  Perhaps these sensations trigger the most primitive engrams of roots from the distant past. 

What lies within these sensory experiences? Can I distill them into some pure nectar that can be preserved and ever after be a part of me, perhaps imparting equanimity, wisdom and understanding of the mystery that is life?

Perhaps so. That nectar of experience is the memory stored in the mind, reachable by mysterious neural processes.

However, there is a barrier that limits the reach of our senses. Mathematicians tell us that there is an abyss that conception cannot span. It delimits the fathomless dimension beyond the observable universe. Swedenborg called it the abyss of nature. Our senses cannot get us there, only our intuitive imagination and the cold, pristine language of mathematics. What is this barrier beyond our sensory world?
A century ago, a biologist, Jacob von Uexkull, described it in a metaphor that can be readily grasped.

It starts with a story about the world of the wood tick. 

The tick climbs a plant and positions itself on a leaf or twig and patiently waits there for days, weeks, even months. When it senses the odor of butyric acid, a component of mammalian sweat from the exocrine glands of the skin, it releases its hold on and drops. If lucky, it will fall on the passing mammal, and through the sensation of heat, finds its way to the base of the hairs where its primitive pincers will penetrate the mammal’s skin to enable it to feast on a blood meal. When fully engorged it will drop again to the ground and slowly repeat the process. 

Through his observations and experiments Uexkull determined that the tick’s senses are completely confined to the small range of smell and to temperature that I described. That is its world. Uexküll studied similar qualities in many other life-forms and eventually conceived a term that he called a subjective soap-bubble to describe the confines of the perceptive universe that surrounds each living thing. According to this model we too are encompassed by this metaphoric soap bubble with a range of perceptions that are comparable but by no means superior to those of our fellow creatures. For example, compare our sense of sight to that of an owl, our hearing compared to that of a tiger, the sense of smell compared to a dog. We have, of course, invented appendages that vastly and artificially extend our senses. The tick’s sensory world spans a few inches, our sensory world spans billions of light years and infinitesimally small dimensions with the observing and recording instruments of our invention. Yet our world remains limited to that which we can perceive.

We are, in fact, also confined within that bubble. That is our world. Without our senses there would be no universe. But, as thinking, observing, and measuring beings, the theologian and priest, Thomas Merton believes, mankind has come to isolate himself within this impenetrable bubble which contains all apparent reality in the form of purely subjective experience. Confinement in that world he claims tends to a centering upon our own collective ego, thus we become oblivious to the certainty that the self is not in the center but is merely part of the vast ground that extends beyond comprehension.

We are cluttered too with our own discursive thinking which hinders our perception of a cosmic reality that lies beyond the walls of that metaphoric soap bubble. Although mathematics can surely penetrate it, the language of poetry may make more accessible the knowing of our place in this mysterious place.

Take for example what the poet, Rilke, experienced while sitting in the garden of Duino Castle.  Leaning against a tree and absorbed in the surrounding nature, “in a state of almost unconscious contemplation,” he felt some “almost imperceptible vibrations,” appearing to emanate from the tree, a condition so perfect, so persistent, and different from all others he had experienced. He insistently asked what was happening to him and almost immediately found an expression which satisfied him, as he said aloud to himself that he had reached the other side of nature.

 He had entered into the natural surroundings in a unitive experience and through his imagination was looking beyond the walls of the sensory bubble and “reaching the other side of nature.”
Such too was the moment one night on the island of Helgoland when the physicist Werner Heisenberg, alone, looking out over the sea, described his visionary experience, how he “saw into the very heart of nature,” the other side of this abyss, when the solution to the uncertainty principle, a vital part to the quantum mechanics theory, exploded into his consciousness after endless calculations over many days.
They both experienced the extraordinary glimpse of the distant reaches of reality lying beyond the perceptive barrier, one in the metaphoric language of mathematics, the other in the metaphoric language of poetry.
As I view the Grand Canyon, or indeed any object that stirs the senses, a grander vision may enter my consciousness. It is that moment, when a “tremendous muchness” William James’s term, becomes unforgettable, awesome and beautiful.  

The state of pure experience does not happen everyday. It is an exceptional moment for human beings, fettered as we are by the symbolic structures which direct our mundane activities. And why should it be otherwise? We have built those structures ourselves, within which we live and survive. But, Wallace Steven’s gorilla of nature is there, in the room with us, and can not be ignored. It won’t go away. It is well to be prepared when that moment happens, to look into the very heart of nature and to try to reach the other side, the visionary world of spirit.

This then is a primal, basic, deep awareness of existence. Let our mind’s muddy river with its ceaseless flow of trivia and trash flow unhindered until some clarity allows us to glimpse the universe’s pure reality and sublime beauty.
