# The Showing by Dr Gouri Datta {-}

The tempo of the usual hustle and bustle of daily life seemed to have jumped to a faster gear at the large old house, that stood like an ancient mastodon, at the end of  the winding narrow small town road in Bengalitola, Phul-jharia.

Mrs.Hema Basu pushed her gold-rimmed glasses down to settle more firmly atop the bridge of her nose, and jerked the red Parker fountain-pen to encourage the ink to flow unhampered. She started writing what looked like a menu on the long thin notebook with lined paper, usually reserved for making grocery lists and keeping a running tally of expenses.

 ‘Ma,’ said the cook, Shivji, coming out of the kitchen . His face was flushed from the heat of the a Janata kerosene stove, a gas heater, a cooker and a traditional clay stove spewing coal smoke.
Most household help called the mistress ‘Ma ‘in ordinary Bengali households all over northern India. Whereas in the  fashionable corridors of parts of  Kolkata, the capital of Bengal, the uniformed chaprasis  or peons would call the lady of the house –’mem-sahib’, a word originally  reserved for western white women, a throwback from past colonial times.

Last year Hema had visited Rekha , an old school friend, who had married a prominent businessman in Kolkata. 

 Not only did Rekha live in an impressive mansion that used to be the living quarters of some long dead and buried British East India Co official, but she also had a special haunted room said to be visited  on occasion by a sepulchral Lord Warren Hastings , Viceroy to India from England in the eighteenth century.
 
Rekha, Hema had noted with awe, had seven servants, all in blue and khaki liveries. They would address Rekha’s husband as Sahib  or the great  white man, and Rekha as Mem-sahib or the great white woman. , the adjective ‘great’ being mentally supplied to the meaning by Rekha.

Since that visit., Hema  had tried to train their new chauffeur, Jailal, to use the  Sahib  and Mem-sahib  routine, which he falteringly but faithfully followed. However, Shivji having  been with the family for years, found it unacceptably hard to give up what he was used to. He reverted to calling Hema’s husband, Aswini  –’ Babuji ‘ or respected father and Hema –’ Ma’ within a few weeks of Hema’s enthusiastic coaching, much to the latter’s chagrin.

Aswini Basu was a tall, lanky man with an absent-minded air, who had studied advanced Statistics in England, but had turned down a coveted actuarial position in  London to return to India to be a part of the country’s newly earned independence. He now taught Mathematics in Darbhanga Mithila College nearby , and felt satisfied and fulfilled. He also wanted to be with his aging parents, his father nearing retiring age .though still running a busy practice as an Ayurvedic medicine practitioner.

Aswini was a man of patriotic principles. He had participated in the ‘ Quit India ‘ movement to end British rule, and had walked with Mahatma Gandhi in the famous  ‘salt marches ‘ of the forties. . To this day he wore only khadi, a coarse off- white cotton fabric originally made from hand- turning spinning wheels locally, as an act of national solidarity, and to shun imported western clothes.
He had moved in with his parents and in a couple of years had married through ghatak negotiations, this fair skinned and dimpled woman, Hema, distant relative of distant relatives .  He and Hema had had three children, all growing up in that large mansion of a home  designed and built  by his father, the Sr Mr Atul Basu , who had  made a good living and a name for himself in his profession as a healer. 
The house had seven bedrooms, two levels of terraces, large airy windows, and high ceilings. There was a spacious lawn, an orchard of guava, papaya, lichi,  and  banana trees , and four different varieties of mangoes.

Atul Basu, stopped working three years ago after  Aswini’s mother died of a sudden heart attack, and  surrendered himself to being cared for, if somewhat bullied, by his strong -minded daughter in-law, Hema .  He created his own complete world   within the confines of his second storey bedroom, and his neighbors had not seen him leave the house in the last couple of years.

The Basu family , though originally from Bengal, had migrated two generations ago to the nearby state of Bihar in search of jobs –when Bihar had plenty to offer with its mica mines,  flourishing forestry and fishery departments.  Managerial and supervisory  care-taking positions in the many palaces of the Maharajah of Darbhanga, were also  desirable job options, who still managed to keep up some semblance, though rapidly declining, of pomp and circumstance.

The family spoke both, Bengali, their original mother-tongue of Bengal , and also Hindi, their adopted dialect of the state they had migrated to.
The Bengali migrants, known to the Calcutta Bengalis as  ‘ Prabasi Bangali’s ,  spoke  their original mother tongue, Bengali , fluently enough. But over the course of generations their accents would become tinged with the Hindi tones of their adopted state.  In addition, influence from the latter would affect also their food habits and certain aspects of their dresses – a change not looked upon favorably by the authentic cousins  from Bengal proper and, in fact, considered  material for ridicule and sly mimicry.

Hema was especially sensitive to this as being considered a Bengalis’ Bengali was very important to her when she visited her relatives in Kolkata.  
.
She was a woman of contrasts, in many ways, as her daughters sometimes pointed out when they were in the middle of  their not infrequent  mother-daughters arguments.

Hema, though very conservative and down- to- earth in certain matters,  was like a mother marsh heron, grounded and  wading through one of the monsoon- made water puddles in the fields next to their house. She occasionally wanted to flap her wings and take a soaring trip with the eagles that at times flew down from the mountains of Nepal, not so much for the spirit of fancy-free adventure, but for the advantage of wearing sun-kissed plumes and looking eagle-like.

Hema had done her matric degree from a high school in Burdwan, close to Calcutta, and though she did not speak much English herself, she had several western touches in her household décor to tweak her neighbors’ curiosities and envies.. There was Wedgewood imported chinaware, her tea- trays held  serviettes of English linen embossed with an impressive English name a, and a tea- cosy that she had bought at an upscale  store in one of her shopping  forays to the New Market in Kolkata . There were also puddings and soufflés in place of the regular Indian desserts when she had the local Binapani Club’s Ladies’ Auxiliary meeting at her house, recipes she got from the local missionary school’s Anglo Indian teacher.

She was often  frustrated by her husband’s what she considered-old fashioned stolidity
This characteristic  thwarted, if not completely wiped out, her desire to be in step with some of her snobbish upper class acquaintances.
 
‘Ma-ji ‘ , repeated Shivji again, breaking her concentration. ‘ What would you like me to do with all that chhana ‘.

Hema got up, flinging the end of her sari, to which a bunch of household keys were tied, over her shoulders. The keys, knotted to a large  circular silver key ring , were a power symbol for most women in India, Tying the keys on her person for safety and security , yet being able to flaunt them with the characteristic jangle –was something that the traditional lady of the house would do in the old fashioned zamindari days, when  the rich land -owner in his fiefdom was the one whose stylish living  was to be emulated. Those powerful zamindars were long gone, though there still were vestiges of that rich heritage in some parts of rural Bihar and Bengal.

Hema walked down to the kitchen at the end of the long corridor that ran between the  dining room and the well-stocked pantry . She inspected the white cheese like curde that had had been produced by adding  a large quantity of lemon juice to a tureen of boiling milk, delivered fresh by the milkman , Nathni, that morning.

She stirred the pot vigorously with a long handled ladle to make sure that the milk had curdled properly, and then had Shivji hoist the heavy tureen over the kitchen sink.  so that The pale  whey liquid   was to be  strained out through an old square piece of  a torn pillow-cas ,  that had become thin gossamer like over the years due to constant use and washing.

The kitchen and household interior still held the old heritage , while the outer parts were presented as  modern and  western, mostly by Hema.

Hema poured a portion of the liquid into a tall glass, stirred in two large  pieces  of  misri crystallized sugar, that she had especially ordered from the sugarmill in Sakri.  Though a long  hour’s drive in their old Ambassador, it was worth it to take the trouble.  Hema knew where to get the best things from even though they lived in this very small town with limited number of stores. 

She set the glass on a tray with four arrowroot biscuits. It was  to be taken to the second floor where her Father in-law’s bedroom was.

The senior Mr Atul Basu  preferred this particular drink  late morning every day, as it worked wonders on his ‘ constitution ‘. Much better  than the draughts of Phillip’s Milk of Magnesia or even the ayurvedic cure-all, Chyavan -Prash  paste . Hema dutifully made up a glass for him for  eleven o’clock on the dot, the prime hour for the fiery pitta waves of the diurnal Eastern health cycle to be buffeting the body, as her now-deceased Mother-in law had trained her to do before the latter had died. 
Hema squeezed the remaining watery liquid out of the lump of white cheese, knotted it in the cloth, and hung it around the kitchen faucet to drain it drier.
‘This is to be made into rasgullas for tomorrow,’ she told Shivji, who nodded. He understood that special preparations were afoot for the big day tomorrow.

It was not a time for Pintu Mishti Bhandar store sweets or kebabs from the corner Moslem mughlai snacks bistro . Everything had to be home-made and from scratch. Otherwise it would be a negative reflection on the worthiness and social standing of the host family. 

Rasgullas were sensitive sweetmeats. The dessert of Rajahs, thought Hema. The cheese had to have the finely tuned resilience and texture, kneaded hard with a balanced sprinkling of flour and semolina , shaped into balls the size of koel-bird’s eggs, and boiled in a  sugar syrup of ‘ one thread consistency ‘, indicating a thin, light  solution –till the balls swelled up like yeast –leavened bread, soft and smooth. It was the mark of a well-run kitchen to produce the perfect rasgulla, the ultimate of Bengali sweets and always a challenge to the culinary artistry of the cook.
The maid, Bibi-dai, entered the kitchen with a small platter of  unripe  turmeric roots, gnarled and fingerlike. ‘Is this enough ?’, she asked.

Hema looked at them and pondered. The turmeric was to be peeled, smashed with a heavy pestle on a stone spice-board . The stone base slab was pockmarked with drilled holes to give the act of grinding more friction, The turmeric was to be wetted with slaps of gauged amounts of water from a bowl , and then mashed down into a bright yellow paste, the color of summer sunshine. Hema smiled inwardly. 
She had gone through this ritual herself twenty years ago. Now it was her daughter, Vaidehi’s turn.
 ‘Let me see,’ Hema  said, briskly, feeling the turmeric spuds. 
 
The spice paste was to be blended with yoghurt, sandalwood  paste and chickpea powder. It would then be applied as the traditional facial pack for  the  brides to be.
For tomorrow was to be a special day for Vaidehi. It was  the day of ‘showing‘ a preliminary interviewing prior to an arranged marriage being finalized, an occasion when the prospective groom and his family would  come to meet the would –be bride for the first time.

Vaidehi looked for a place to hide from the rest of her family. She  found refuge in her GrandFather’s room. 
The senior Mr. Atul Basu sat with reams of paper spread out on the large old ebony  four poster  bed.
‘Dadu’, said Vaidehi, using the Bengali word for grandfather, ‘What are you doing with all these papers?’.

‘O Vaidehi’, said Sr. Mr Basu , looking up above his round steel-framed glasses, ‘ Come and sit down , right here ‘ . He patted a small bare spot on the bed beside him, shifting around some papers to make room for her. ‘ I’m looking at these astrological charts.’.
Vaidehi had seen her Grandfather do this for hours, pouring over strange markings and graphs . He had been  comparing charts for her future marriage alliances  ever since she was sixteen , which was a good four years ago.

To her secret joy, he had discarded one  prospective bridegroom after another, as the planets, according his readings, were not congruent. 

‘Venus and Mars  are in conflict ,’ he would say.Or ‘Saturn is inconjunct with the Moon –the match will not work.’

Finally he had given a partial nod to this particular young man, Devraj’s astrological chart But there were still a few  concerns and  he was not totally satisfied.

Vaidehi’s mother, Hema,  had begun to despair of ever getting her older daughter married –due to the rigors of astrology.. She  had been greatly relieved at what amounted to a green signal from her Father-in –law about this marriage prospect . . She wasted no time in arranging a date quickly for ‘the showing of the girl ‘.. Devraj’s family lived in Ranchi, about three hundred mile sfrom Phul- jharia. . In one of their telephone exchan ges  about working out the logistics, it was discussed that Devraj ‘s family would drive down in their own Maruti van, to see Vaidehi and put up with relatives who lived in Darbhanga, next town to Phul-jharia.

The fact that  they had a car, and a sturdy one at that, capable of traversing the long three hundred miles of distance—impressed Hema.

Vaidehi made herself comfortable beside her Grandfather on the bed . , She  stretched out with a pillow under her stomach and her chin on her elbows. She loved this part of the house, especially this particular room, which was haven due to her GrandFather’s comforting presence.

The chrysanthemums  in the terrace outside ,stood up on the clay pots like colorful jack-in -the –boxes. White, pink, mauve, yellow. The zinnias looked like smaller versions of them, equally colorful and festive.. Pansies with elves’ faces—a child’s magic land. A few ladylike kalavatis with yellow and red  flowers shaped like conch shells, and large furling green leaves, added extra color.

However, Vaidehi’s favorite was the juhi plant with the tiny star like flowers and heart-breakingly sweet smell. The scent brought  an ache and swirling pleasure into her at the same time, a mixed sensation that sometimes bewildered her. Did other’s find that scent so magnetic or was it only for Vaidehi and all the delicious secrets  it signified  for her.
Vaidehi sighed and brought her attention back into the room. The walls were lined with all kinds of books from Tagore to Shakespeare. Some had textured  solid leather binding, appearing important and aristocratic loking  . Others were coming apart at the spine with pages leaning out of them , as if money hastily half pulled out of a wallet. Several were  bound in tight colourful  cardboard covers  of paisley prints by the local book binder , who almost had a fulltime job here in this house , A few  were  carefully glued together with home-made glue made from flour and water.

A red and white Murphy radio stood atop the bureau, used for the nightly news from Akashbani Kolkata , or if there was a classical music program  by a favorite artist.

A stack of His Master’s Voice gramophone records  were on a small turn-table next to the bureau . Grandfather had made classical Hindustni music a focal point in his life, his every waking hour literally defined by  either khayals by his favorite singers or classical pieces in  sitar sarod  or flute  A sad requiem of malhar played on a rainy afternoon with the juhi’s exuding their magical scent sometimes made Vaidehi want to weep and weep with strange longings she could not explain, and was too embarrassed to talk to anybody about.

She looked at her Grandfather  again and gave a long sigh, moving around on her stomach to get comfortable.
He smiled at her, his face serene and faultless in her eyes, despite the scar below his right eye from the claws of a mongoose that he had once surprised while walking in  the heavily wooded hillsides of Hazaribaagh, in quest of a rare herbal plant . This was one of his stories , amongst many that he would tell and retell his grandchildren. Sometimes they were bedtime stories. At other times they were tales for dark evenings , when the electricity would be out , the hurricane lamp light would be too dull to encourage reading.   The children   would all crowd under his mosquito net to avoid the inevitable bites., and imbibe the stories with their round wide eyes, as well as their ears.

The room , Vaidehi thought, had interesting dents like her GrandFather’s face. There was a deep crevice in one corner of the cement floor, a result of the notorious earthquake in the 30’s that left much of Bihar in ruins. The steel door of the Godrej almirah against the wall bore the starburst  mark of a bullet from a robber’s gun. That was another hair-raising story , Vaidehi remembered, thank goodness , it had happened before she was born. It was a room with stories and experiences, a room with a character. 

‘Escaping, are you? ‘, said Grandfather, glancing at her with a knowing smile. He knew that she was not happy about what was to happen tomorrow. ‘ I know you are upset about this ‘showing ‘ coming up tomorrow . Am I right?'.
 Vaidehi  nodded silently and with a hint of a sulk in the shrug of her shoulders.
‘How else will you get married then,’,he went on gently. ‘ Arranging our children’s marriages is our tradition . That’s how it’s done,’He cleared his throat a bit , and added, ‘In most traditional, conservative Indian households‘.

‘It’s a terrible tradition !’ , burst out Vaidehi. She  wound  the ends of her bandhni printed dupatta sash  into  knots like fists . ‘Why do  Bengali girls have to go through this?‘.

‘Your Mother had to through it, and her mother and grandmother too, before that. Your Grandmother had to go through this. I never went to see her, you know, but my parents did, and I took their word for it .Thank God they had good taste!’, he smiled, trying to ease her. 

‘It’s not nice being on display like a mannequin or cattle at the Noyatola bazaar ‘, retorted Vaidehi,  half sitting up on her haunches on the bed , her cheeks flushing .
‘Your Mother must have felt nervous, too, when she had to sit for her showing when we went to see her 
‘He went on in his coaxing voice  smooth like the polished ebony surface of the bed-posts ‘ Where would you be if the showing hadn’t happened and the marriage hadn’t taken place with your Father ? ‘.
 ‘ Oh , Dadu . You know very well what I mean ,’ Vaidehi sat up straight now ,alternately  fidgeting and practising a lotus position  in trying to calm her excitement. 
 
Her Grandfather was suddenly quiet.

‘I know it’s not pleasant for the girl at all‘ , he said finally. ‘It was even worse fifty, sixty years ago.‘ He added with a remembering smile of memory seeping in. ‘Your Grandmother was told that she would be marrying me without her  ever having seen me before, and for that matter, I her , I was very curious on my wedding night as to what she looked like’.
 He paused to look around for his bottle of Chyavan-pras , the herbal cure-all , He dug out a teaspoonful of it to have it with his afternoon glass of milk that Bibi-dai had brought in.

He cleared his throat as he swallowed the brown herbal paste . ‘ For the immune system , you know, Rishi Chayvan put this formula together aeons ago. . I have to get it by  mail order from this special store in Delhi. None of the others sell the authentic stuff . All modern chemicals in the mixture that gave me heart burn . Always go for the real stuff ‘ .

He paused , peering at Vaidehi who was impatiently playing with the two gold bangles she wore on her right forearm . ‘ Oh, where was I ?Yes, Yes, So throughout the long marriage ceremony all I saw was this small person wrapped like a mummy in a red sari and veil, and almost falling down with the weight of all those marigold garlands. ‘.,

He gave a short laugh, showing a gold upper tooth . ‘Then later that night when I did see her, she turned out to have the prettiest eyes in the world. But that was the luck of the draw, She could have looked like a shakchunni,’ he said ,using the Bengali word for a particularly  ugly witch , ‘ and there would have been nothing I could have done about it . In those days, it was even stricter – the choice of the bride was in the hands of the groom’s parents . We just had to trust our parents’ words ‘.
Vaidehi was restless, She changed positions several times, 

She finally lay on her back  and concentrated on the two lizards spread-eagled on the ceiling. She hoped they would not make their lizard sound,  ‘tick-tick-tick’. A lizard’s ticking was an omen that a person’s last words would come true, her Grandmother used to say.
She did not want her parent’s choice  for her life partner to be her truth . 
Vaidehi’s thirteen year old sister, Rohini, and eleven year old brother, Aridra, entered the room. .

‘Ma has been looking for you,’ Mrittika announced with a wait-till-she-finds-you type veiled  foreboding in her voice. ‘ She’s been calling your name for hours.’.
Vaidehi made a face, but not as defiant as she wanted to in order not to set a bad example as the older sister, She  pulled the shepherd’s check blanket from the foot of the bed  over her head.. ‘I’m tired’ , she said, ‘ Tell Ma I need a nap ‘. 

‘She’s not going to be happy about you napping in the middle of the day .’ Rohini’s voice took on a sing song of controlled bossiness. 

‘ Yeah, Ma  wants to go over what we have to do tomorrow ,’ chirped  Aridra. ‘ It’s your showing, Didi 

‘ He called Vaidehi the word reserved for ‘big sister’. ‘ I don’t know why we have to go get dressed up too .’ . 

Hema appeared at the door, bearing a covered bowl. She pulled  one end of her sari like a veil over her head on seeing her Father-in-law, ‘Here you are, Vaidehi . I thought you were studying in the attic. Here’s the facial masque for you .You have to keep it on for half hour before you rinse it off with warm water.’. 

‘Why do I have to put all this on ? ,’ complained Vaidehi, repeating what she had already muttered, whined, and tearfully argued before..

‘It’s to make your skin look fairer, Sona’ , said Hema , using the term of endearment in Bengali, denoting a’ golden child’ .. ‘How do you think we are going to justify what we had printed in the newspaper about you in the marriage ad –that ‘you had a sunny complexion like ripened wheat ‘ ‘ ..

Vaidehi winced. It was the typical euphemistic description of a dark skinned girl by anxious parents, trying to create a pleasanter illusion of beauty with words  All this exaggerating was  in order to persuade the reluctant choosy would-be grooms and their families.to accept the girl , who was : mere object ‘, Vaidehi thought angrily. 

‘What a farce all this is.!’, Vaidehi said, rebellion in her tone. 

‘Also I have picked out a maroon sari for you to wear tomorrow’, went on Hema , trying to control her exasperation  with a show of ignoring Vaidehi’s comment . ‘It will make the complexion look brighter'.

‘They will be lucky to get Vaidehi as the bride,’ interjected  Atul - babu,. ‘Where are they going to find such a pretty smile and graceful ways ? ‘.
 
‘Graceful !’ Hema , exclaimed, trying to keep herself from raising her voice in deference to her Father- in-law. ‘That’s what you think ,Baba ‘. She used the word for  ‘father’ to address him. ‘ She doesn’t listen to a thing I have to say. All girls have to get married , and this is the way it is done in most families.like this. .’ 

‘No,’cried Vaidehi, finding a loophole, ‘ What about Ketaki? ‘.

Hema took a breath . Ketaki was the neighbor’s daughter, a Hindu girl who had eloped with her Muslim lover when both families had strongly opposed their union. 

‘Look at the shame it brought to her family,’ snapped Hema ‘ Ketaki’s mother has not gone to the Kali  temple or any public function since then for over six months ‘. .

Vaidehi knew that Ketaki was living a life of intense romance though shunned by the community.  They had very little money and were barely surviving hand to mouth in neighboring Jhanjha . . She had seen Ketaki, looking very thin and half starved , working on some  documents at a local bank , trying to get a job. .

‘It’s very hard not to be able to see your own family and to feel you’ve brought stigma and shame on to them .’ Ketaki had said., her eyes sunken but intense.’ But I couldn’t have married anyone else but Iqbal. Maybe things will get better ‘ . She had added wistfully. 

Vaidehi opened her mouth to say something in mild repartee to her Mother , but shut it again.
‘Listen to your Mother, dear ‘, said Atul -babu . peaceably ‘ Go on down stairs with  her . I’ve got to look at the young man’s chart in more detail ‘ ‘  He shut the big , thick ephemersis book, inserting his blue-green peacock feather that Vaidehi had found for him,  as a book mark .He also  picked  up his quilled pen and dipped it in the ink-well of Supra Royal Blue ink to make some more markings on the astrological parchments. This was his way of saying that he wanted to be left alone. .

A gibbous moon covered by tissues of clouds hung,.faint and diaphanous, behind the trellis of willowy plantain trees.

Vaidehi lay on the double bed she shared with Rohini, but could not sleep. She was thinking of Mainak, something she had done every waking hour since he had first spoken to her about two years ago.
She had seen him in passing over the years as they had grown up in the same neighborhood. 

But had never directly met as they lived in two different social worlds.

Mainak had spent two years away in college in Calcutta , living with his maternal uncle as his father could not afford college fees or books here , rumors said. He had returned subsequently to live in the nondescript small house with the corrugated tin roof and peeling paint at the edge of town to live with and take care of his Father, who was riddled with arthritis, and  stayed mostly in bed,

Vaidehi would see Mainak  chatting with his friends for hours , under the sprawling tamarind tree that was a landmark in  the center of Bengalitola.. Such aimless hanging around or ‘adda’ was considered a characteristic of loafers and ne’er-do-wells by the neighborhood elders,.and much frowned upon
Mainak would cycle back from college, late at night, whistling the latest Hindi movie musical hits, quite tunefully, Vaidehi thought, -when such behavior was deemed feckless and recalcitrant;

On the other hand, Mainak had, stunned his critics, by being able to recite innumerable pages of poetry by heart at the annual elocution contest during the  Saraswati Puja festival at the local Binapani club, and winning the best actor’s trophy three years in a row. .

His reputation as the talented ‘Bad Boy ‘ of the town made the girls curious and intrigued about him , and their parents wary and uncertain. 

Vaidehi remembered the day she had actually spoken to Mainak for the first time, as sharply as a Jatin Choudhury  wood etching that hung in her Father’s  study.

It was two years ago  when she had attended the All Bihar Book Fair held on the lawn behind the Binapani Club., closely chaperoned by her Mother Vaidehi had been enthralled by the piles of books,  stacked like Shivji’s potato parathas  or  tumbling willy nilly like icing on a cake done by a child’s hands, laid out on dusty tables inside canvas tents .The tables of books seemed in separate small feasts like the Spanish tapas she had read about-- for the book gourmand’s , such as her, hungry eyes. O how she had loved the fair, and to think that Mother almost forbade her from coming , claiming that there would be too many loafing young men standing about in a public place like that for a girl from a decent family to be seen in.

Had it not been for the fact that Father was the president of Binapani Club that year , which had proudly sponsored the event –Mother would have had her way !.

Vaidehi  entered more deeply into  that  rather thrilling reverie.  

Yes, it was at the point that she had picked up a book in Bengali by Mahasweta Devi and another book in Hindi by Amrita Preetam , both well known Indian woman writers. She had then heard  a baritone voice near by. say: 'Ah, good selections ‘, said the voice. 

Vaidehi had wheeled  around to find herself looking at Mainak .

He was tall. But rather thin with sharp edges of cheek bones showing like cliffs and precipices.. He  spoke in this slightly husky , resonant actor’s voice. His eyes had an interested but cryptic smile, that she felt was both fascinating but disturbing, as if he could read her mind. ‘ Have you read Mahasweta’s ‘The Mother of Case Number One Thousand and Eighty Four ‘ ? It’s a torpedo of a book—aims right at police brutality’. 

Vaidehi did not quite know what to say.  Her uncle , Mejokaka , was the Police Superintendant of Muzaffarpur.

She did not quite know whether Mainak had made that comment to assess her  views or get arise out of her.. At first she thought it was rather too forward of him to lay out his beliefs before her within a few minutes of their meeting.

Mainak went on, as if he even read  the reason  for that discomfort in her eyes and understood the need to disarm,  He went on to  talk about other books. He had pointed out several more stalwart authors, impressing Vaidehi by the minute by his detailed knowledge of even their lesser known writings.  He had a skill with his words, smooth and flowing like the Kosi river , all the while his eyes holding hers. 

She had looked around nervously for her Mother, who, she was sure, would not have appreciated Vaidehi’s being involved in a long conversation with any non-related young man, much less a young man with  a dubious reputation.

Especially, thought Vaidehi bitterly ,all the while  crinkling her eyes as she intensely tried to visualize every nook and cranny in Mainak’s face that day as the sun slanted in through the tent flap and touched his lips.. She was taken aback by how sensuous and full his lips were, on that rather rugged face.—mobile  and softly curved, a contrast to the cragginess.. She felt herself blushing.

A raucous Hindi movie song blared on the loudspeakers belying the finesse of such a cultural event, But Vaidehi found it suddenly appealing , as if it was a part of the whole picture—light through a tent, dark eyes with another language , of a promised adventure, a puma through the undergrowth, a beautiful mandoline  at her feet. 

‘You’d better move along’, he said, mesmerizing her again by deciphering her thoughts., ‘ Your Mother wouldn’t want you to be seen hobnobbing with me’. 

His eyes had laughed , both reckless and .empathetic at the same time. And Vaidehi had quickly walked away.

Fortunately, Hema had been engrossed in getting her book signed by her favorite local author, Bibhuti Mukhopadhyay , in the adjoining tent, nd had not noticed the interchange.

The next day , Mainak had met Vaidehi at in front of   Lady  Rotterham Women’s College, and walked along side her, wheeling his bicycle   She was surprised, excited and yet embarrassed to see him –as if he were a manifestation of some guilty but pleasurable.  thought . 

She walked  from the Common Room of the College to her classes, her light blue kurta matching his shirt,, her shyness , almost parallel to his nonchalant controlled insouciance. Again a sensation of hidden rippling muscles like waves under the surface, a look that was in charge but begged her at the same time. Begged her for what ? She was not sure. . . . They chatted ostensibly about mundane and every day things , about novels and movies, and all the while his eyes had had spoken to her of something else..

The meetings happened, sometimes every day, sometimes less when Vaidehi would be paralyzed by fear that someone would tell her Mother about Mainak walking along the College paths  with her, and he would beg him to not come , He would stop for several days, and then suddenly appear, both aware of  each other’s desperate attraction and yet the need to maintain a façade of casual chit chat .

As Vaidehi feared, the walks through the college compound, though initially lightly taken by her classmates as  the natural but temporary course of an admirer  stalking  a girl, were now beginning to cause sniggers and snide comments even amongst her closest friends who thought that she was giving the young man  much too much inappropriate encouragement. 

One day, he gave her a book of of love poems by the famous, Vidyapati, the fourteenth century poet of Bihar, who wrote of the intense fascination and the heart-wrenching forbidden love between Lord Krishna and his married paramour, Radha. That was the first time , after the initial body language stage , that there had been an  object exchanged  as a symbolic expression of the word ‘love’.

Mainak had gone on expounding about psychology and transitional objects, and Kant and a priori and all the words that entertained and stimulated  her, but she had been trapped inside the flutter of her own heart and all his words had turned into wordless Vrindavani sarang  for her, played on her grandFather’s antique turntable, the sitar music streaming out of that corrugated 78 rpm, twirling her round and round into the laugh of a sunshine after a baisakhi summer cloudburst .

Subsequently they had to stop meeting at College as Vaidehi was afraid that a wisp of a rumor reaching Mother’s ears would ban her from going to College. The relationship went on , conducted now in creative and surreptitious ways, mostly through artful letter brought back and forth by trusted, sworn –to-secrecy friends. 

There were  an occasional rare hour or two of stolen time together,  in the guise of going ona college trip with girlfriends that Hema perceived as trustworthy as Vaidehi’s alibis . 

Once they had sneaked in a visit to the Maharaja of Darbhanga’s palace courtyard to see the peacocks dance during monsoon season, remembered Vaidehi with a pang. 

The memory of that coursed through her blood  like absinth ,  fearsome  and fiery in a heart-somersaulting hide -and -seek way; intoxicating because he would hold her hands for a few minutes behind the long flap of a cloth  that the friendly rickshaw -puller had draped over the front of the rick -shaw in order to give them brief , much-coveted privacy; and bitter-sweet because of the hopelessness of their situation. 

They had , planned and plotted, and role-played various scenarios.

Mainak would go up to Vaidehi’s Father to ask her hand in marriage, which, of courese, the latter would refuse, and have the durwan, a trained laathi warrior, literally show him the door with his oil slick bamboo stick with the brass head. Thus failing this afore mentioned plan, they lovers would elope in the dead of night, much like what Ketaki and Iqbal had done, to start a life of their own. Initially, the scenario would further unfold as they added pieces to each others imagined scenes, the Basus would be very angry and humiliated , and send a posse of police after them , with Mejokaka  advising and directing his counterparts in Phul-Jharia . .
‘Charges of kidnapping‘, Mainak would bark in a stentorian voice, twirling n imaginary iron ferruled baton and patting a ferocious cascade of mustache over his upper lip in imitation of the local havildar. ‘You are under arrest, youngman -Deleted swear words, in front of the ladies etc. I have come to take the girl back to her parents’ .

‘It’s too late, police chacha,’ Vaidehi would put on a solicitous but victorious voice, and address the policeman as her respected uncle.  She would then cover her head with a kerchief in imitation of a married woman’s modest veil and add coyly,. ‘We’re already married‘. The prospective fantasies of such an exciting outcome kept the both of them regaled for hours.

However, Mainak would have to get a job first, before any such bold move could be implemented. 

Vaidehi fell into a fitful sleep. Her dreams felt like a woven  magical fisherman’s net,  that had trapped her  day- time thoughts, and was now  gathering them up at night transformed shiny, scaly haulings of hallucinations. 

She dreamt of a yellow shamiyana, a large tent pitched in their backyard. It was hung with colored streamers and panels of gold thread embroidered Banarasi cloth . 

Guests were streaming in and out in waves.  Musicians wearing red fez hats sat atop a scaffolding type high dais  in one corner, blowing out their cheeks over their shehnai horns, and nodding their heads like snake charmers, in time with the rhythms.

But why did the sounds, instead of being the joyful and heady crescendo of a happy wedding alliance sound out as the mournful dirge-like notes of the sad requiem raga ,  megha-malhar ? 
Vaidehi , in her dream , found herself dressed in the traditional red Bengali wedding colors, walking as her Father held her arm. She  treaded slowly on the carpeted floor strewn with pink  rose and milky white hasnuhana petals, heel to toe, heel to toe, the red alta on her feet bright as her heart’s blood, as if she were trailing her wounded heart behind her. On she walked towards the groom, who stood at the far end of the tent, as if a thousand light miles away, wearing a topor , a bridegroom’s  white crown, handcarved from shola, the cork plant, with scrolls of jonquil and jasmine garlands hanging from the tiers of the headgear, covering his face.

Vaidehi’s eyes were  brimming with tears, cresting like the Mirza talab pond next to their house during heavy monsoon showers and threatening to spill into the arhar lentil and sugar- cane fields.  She knew that the man wearing the wedding topor was not Mainak. Her legs were ready to give way when she heard her Father urgently whisper to her: ‘You have to forget about Mainak. Not only does he not have a job, but he is also a Naxalite !’ .

Vaidehi woke up with a sharp longing like an ironmonger’s stave through her heart. She had fallen in love with a completely unsuitable man—a charming, feckless, jobless, penniless man, who in addition to all these handicaps, also happened to have the wrong political leanings..

He was a fearful word that made newspaper headlines—someone an average citizen did not understand and was afraid of, a Naxalite.  .

The dream had been very vivid, She could almost smell the Aguru scent that had been sprayed on to her Father on his bundy and khadi pajamas as he entered the shamiyana by the welcoming bevy of bejeweled nieces and cousins. His khadi cap, crisp and white, sat slightly angled on his partly bald head . Even on his daughter’s wedding day he wore his favorite  khadi from his days of national allegiance, instead of the tussore silk kurta that her Mother had wanted him to wear .
Vaidehi steadied herself against her Father  in the dream and looked up at him. A man who wore a Gandhi topee and voted for the Congress Party would never accept someone from a militant political group as his son-in-law…

A cool breeze came in through the windows, and woke her up. She pulled a blanket on her self and looked out at the sky. It was her favorite month of Kartik though she felt no joy this year.  She would be able start seeing the Orion constellation, now that the skies had changed for winter, Her Grandfather had taught her to recognize the Hunter with the red and blue stars forming the belt at his celestial waist.. She preferred the Indian name –Mrigasira, the head of the deer.This was her nakshatra, the smaller archipelago of  star grains , on a line going up  to the bigger planet Moon, which had been scudding on the doorsteps of  of Leo when  she had been born . This is how her grandfather had explained it.

She lifted her index finger and outlined the star’s silhouette in miniature against the mosquito- net  fabric. Her Mrigasira. It spoke of freedom, of scented woods, gentle animals with pea-pod eyes nibbling sugar-cane leaves, of lightness of spirit, of speed of happy hooves.

However, tonight she remembered that in the olden days the sailors dreaded the appearance of Mrigasira on the eastern sky, as it usually portended a storm. 
Vaidehi felt afraid too.

Nakshalbari..

The name of this small town in West Bengal carried the impact of a Molotov cocktail bomb, that its most infamous inhabitants were so given to using. From there rose a core group of young men with socialistic militant views. They were young, angry, intense and passionate.They burned with the fire of  outrage at social and financial inequality amongst people, and demanded reform and fairness, if needed, at the point of a gun..

They were dedicated to their visions and would stop at nothing to achieve their idealistic ends, Vaidehi had read in brochures left by unknown hands in her college common room,  --equality for all, raze all useless, ostensible riches and all institutional behemoths to the ground, eliminate the difference between the rich and the poor, give rise to a new social class of shared resources. 

This powerful political vision had spread like floodwater into all crevices and corners of India, and swept the Indian youth off their feet . It was  threatening to rock the cornerstone of the foundry of traditional government rules. .

The Naxalites, as the members of this group were called, were known to  bomb, kill, kidnap powerful old-order political figures. The police suspected and blamed most crimes, initially political, later almost  all varieties , to being sponsored and masterminded by the Nakshalbari group  The authorities were thus quick to arrest them and recommend the harshest of jail sentences, if not downright death.. Police brutality went toe to toe with the Naxal’s violence

That their adolescent child would fall under the sway of this political affiliation with its charismatic leaders and idealistic visions-- was every parent’s grotesque nightmare. .

Each person suspected of being  a Naxalite was automatically registered in secret police diaries.
 
Mainak’s name, if not heading the list, was certainly a part of it, Vaidehi knew. 
Dipti, Vaidehi’s best friend, came in with an arm full of books. 

Vaidehi was sitting on a chair in a shaded area of the courtyard, near the basil bush where a clay lamp and wilted flowers lay scattered from evening worship the night before.

Hema was massaging Vaidehi’s hair with warm coconut oil to be washed off with green tea and grapeseed extract  shampoo, that she had obtained  as a gift from a sister in law who just returned from Japan , 

The Japanese certainly had shiny black hair , and knew of ancient secrets and formulae to turn ordinary objects  into things of better quality,-even make food out of seaweed, Hema thought
Bibi-dai, the maid, who had cared for and partly raised Vaidehi since she was six years old, was delicately painting designs on the soles of the latter’s feet with a cotton swab dipped in alta, a vermilion red liquid used for  decorative art on the soles of the feet, mostly of married women..
‘Don’t move so much,’said Bibi-dai, holding Vaidehi’s leg firmly. 
‘You’re tickling me,’ groaned Vaidehi , her voice commensurate with her disgruntled expression. . 
'Alta is a part of auspicious rituals of a women’s body,’ Hema said, separating Vaidehi’s hair on her scalp in rows with her fingers and pouring oil along the rows as if to irrigate the roots.
‘More like it is a sedutive ritual,’ grumbled Vaidehi under her breath, making sure that Hema couldn’t actually hear her words. 
‘Oh, Dipti, good thing you are here early ,’said Hema . ‘Maybe you can braid Vaidehi’s hair after she washes it.’.

Dipti dutifully touched Hema’s feet in the usual Bengali gesture of reverence  in greeting  a senior person and sat down on the madur  bamboo floor mat, close to them .
‘That oil smells beautiful, Kakima ‘,Dipti said, using the word for ‘Aunt ‘ in addressing Hema. ‘Did you add some Jaba-kusum oil  to the coconut? ‘ 
‘Oh, it’s a big concoction,’ Hema said proudly, as Vaidehi made a face at Dipti. ‘It has rose water, almond paste, shikakai powder that your uncle’s student got all the way from Madras, honey and aniseed paste’. 

Hema got up wiping her oily hands on a red and white checked duster, tucked to her waist  
‘And tell Vaidehi that she needs to have a better attitude about the ‘showing of the bride’ that’s going to happen . Maybe she’ll listen to you,.’ Hema said, in parting. to Dipti , ‘ Your sister just got married to the nice boy from Patna .Didn’t she have to go through the same ceremonies and rituals ? Tell Vaidehi that’ . 

Dipti and Vaidehi exchanged rapid glances.

Vaidehi knew that Dipti had probably snuggled in a leter from Mainak inside the cover of one of her books, a form of postal delivery that they had to resort to due to restrictions and monitoring of Vaidehi’s movements, more so since recently since serious  arranged marriage negotiations were in progress. In addition, Vaidehi’s transformation to the somewhat more than ordinarily necessary defiance of all girls to be ‘ shown ‘ was beginning to worry Hema a little.

Holidays and vacations were even harder, making meetings w Mainak  almost impossible as college was closed and Vaidehi was house-bound,. Mainak, though, always made creative efforts to see Vaidehi one way or the other.

He once came in on the pretext of asking the Senior Mr Atul Basu about the astrological implications of his uncle’s date of surgery and whether it would be wiser to change the date when it was discovered it would fall under the auspices of the hostile constellation Magha..

They had been chatting intently a good  twenty minutes when Vaidehi came into her GrandFather’s room with his afternoon tea and puffed rice spiced with ginger. She stopped in her tracks to see Mainak, of all people there. He winked at her roguishly, when Dadu briefly looked away to rifle through some papers.. She frowned back, warning him to be careful, as though her grandfather was neutral and accepting of most people, Mainsk would have hell to pay if Mother ever found out. 

She also marveled at his putting on a show of great interest in astrology, when she knew that he thought of it as unscientific mumbo jumbo.

She heard Mainak ask as Hari Pasad Chaurasia  played on his flute the plaintive and beautigul raga Shiv-Ranjani :
‘Your two main interests, sir, astrology and Hindustani classical music –is there a connection ?' Vaidehi grinned inwardly. Trust Mainak to have studied up on natal charts and the different aroha and avaroha of the different ragas just for this occasion –the devil ! 

Grandfather looked at Mainak for a brief second as if to appraise the question. Now here was a thoughtful young man, Vaidehi could hear him thinking. 

‘Well,  music and astrology they are both about healing, about comforting the part of the being that may need replenishing. Astrology is not just about predictions. It is a form of preventive medicine or protection by anticipating the future or existing gaps. And as far as music is concerned, you know about soothing the savage breast’.

Vaidehi had put on another record, raag Gauri, by Nikhil Bannerjee, a contemplative piece for the evenings, espoused especially by devoted Sikhs , she had learned from Dadu. She knew his likings to a T. 

He especially liked all the sad ragas, more since Didu had died three years ago.

There was a sequence to how the music would be played most days: Basant of loneliness, Shiv- ranjani of contemplation, Behag of compassion  Occasionally sounds of Darbari Kanara or Kamoj in sharod instrumental would  filter in from Dadu’s room  if Vaidehi happened to awaken  for a drink of water or to get an extra blanket. She would realize that the insomnia was bothering him more than usual that particular night. Dadu always had a smile on his face and never moped but the music expressed  his missing Didu, thought Vaidehi. 

On the days Dadu did not feel well physically,Vaidehi heard mostly Jaunpuri, Hindolam, Ahir-vairab and Pooriya—the ragas for healing the body 

Vaidehi also remembered that Dadu had enquired through his several musical contacts about getting a rendition of Raga Vindu- dhani when Didu became very ill with a sudden stroke. The Raga was out of stock in the Kolkata stores, and arrived several months after Didu had passed away. Dadu had played it only once, and then packed it away in its cover and foam packaging and placed it in the back of his bureau drawer. 

‘Don’t you like this record ,’ she had asked, surprised at his act . 

‘ I do like it very much , but it become unbearable for me to hear it’, Dadu had said quietly. Later he told her that it was a raga meant to give life to the dead. That her Dadu, who was always so strong and appeared in control of his inner world, could become so sentimental with grief even years later, was a revelation to her that day. 

Her brown study was interrupted as she heard Dadu say ‘Carnatic Claxsical music especially has a great correlation with astrology.There are 12 zodiac signs, as there are 12 swaras or notes’ Mainak was listening intently but Vaidehi knew that he was only doing this to get some more time in the room –the quirk of defying convention and authority in Mainak, and the oh so sweet daredevil romantic sneakiness.to see her,jut to see her., she hummed to herself internally to the playing music .

‘Just as the Sun and The Moon are the most important in astrology , so are the two swaras Sastha and Panchaam the most important,’ Dadu went on. ‘ There is so much more, but that will take me a week to tell you all that , My family knows how  I am obsessed I am  with  my interests ‘ he smiled a bit ruefully. 

Just then Hema entered the room with a heap of washed towels on her arms, and recoiled seeing Mainak. How did a good- for- nothing young man who had nothing better to do than stand around under the tamarind tree with his equally lazy friends, and with such a rapscallion’s reputation –gain entry into the Basu house –Vaidehi could almost hear her Mother thinking. Especially a house where a nubile girl was being nurtured and prepared for a well-arranged marriage, added Vaidehi mentally,bitterly..

‘Baba, it’s time for your massage. Rajinder is waiting with the camphor oil,’ Hema said sternly, flashing her Father –in-law somewhat of a warning glance. Rajinder the , gardener, had wiry muscular arms, not only from lifting and pouring heavy buckets of mulch and sod for Hema’s prized eggplant, cauliflower and tomato garden but also for his exercising them in daily kneading of  Dadu’s arthritic joints and stiffened muscles to form .

‘Ah well, then,’  said Dadu, looking somewhat sheepish, and realizing he had inadvertently displeased his daughter –in-law in some way.’Time’s up, I guess. Saturn the Master of Time and Discipline-can’t disobey him.’ He added rather obliquely or in his doddering old-man– act that he sometimes put on to get out of scrapes, Vaidehi thought,

‘I’ll move along. Thank you for the fine advice on the dates , sir ‘, said Mainak , all handsome  courtesy and attentiveness , moving towards the door. Thank goodness he had not attempted to touch Hema’s feet in the usual gesture of greeting or addressed her as  ‘Kakima’ in a last wicked act of tease as Hema may have kicked him , Vaidehi thought with trepidation.. 

Vaidehi saw a flash of  Mainak’s blue shirt,  breathed the slight hint of interesting bad-boy , cheap tobacco aroma , heard  the rapid whirr of his Hawaii sandals slapping down the stairs—and then he was gone. 

‘I thought I would stay the afternoon and help Vai with her make up.’ Dipti was saying to Hema.. ‘I can do her hair in a elo khopa that she looked so good in during last Ashtami Puja’. 

Vaidehi felt like making another face at Dipti for egging Mother on with all her suggestions, but curbed herself. She settled down to Dipti working on her hair, and leaned back in her chair.. Her hair was still wet and needed to be brushed out to dry.

She closed her eyes as the brush strokes relaxed her

She struggled to focus on reality, but today seemed especially hard for some reason as the day-dreams crowded in. This could be a bad omen , But she let herself get swept into them just to be able to tolerate the tension of all the turmoil that was happening in her. . 

She remembered another one of Mainak’s escapades. –always into drama, he was.

The bahurupi festival  season occurred in the autumn of every year. The villagers whose families were trained in this particular art form, would dress up in various guises of mythological gods and goddesses or characters from the epics of India, and go from door to door, delighting the children and earning a few paisas

Last year  Mainak had disguised himself as a hermit from the Himalayas, his face caked with ash and soot, wearing a wig of long, knotted uncombed hair atop his head, twanging a rickety ektara to supplicate for alms.. 

Vaidehi who had accompanied her excited sister and brother to the door, had no idea of the true identity till his trademark roguish wink stopped her in her tracks,  She had played along, and slipped the bahurupi an extra couple of rupees secretly to indicate that she had recognized him .

‘Oh, elo khopa sounds great,’ Hema was saying to Dipti, as Vaidehi’s attention returned to the room. ‘I have so much else to do.’ She bustled away to supervise the kitchen , leaving the two girls to escape a bit later to the verandah outside her grandFather’s room. There Vaidehi could surreptitiously read the treasured missive from Mainak, as Dipti kept watch for intruders..

Vaidehi loved  Mainak’s letters. They were rushed and urgent like his intensity, and yet his feelings for her stated in both calm directness and in the sweet euphemisms that lovers are spontaneously inspired with.. They made her laugh, they made her cry. They were filled with unusual quotations from T.S Eliot to Sunil Gangopadhyay.to Jibonanada Das to Dom Moraes Even his doodles at the margins were interesting.

Vaidehi’s heart beat a faster lub-dub as she read on .

Mainak knew about the ‘showing’ today , and realized that should the event progress as smoothly and successfully as her parents hoped and Mainak feared, it would only be a matter of days before a date would be firmed up for nuptials with this would -be groom.

In the letter, Mainak was asking Vaidehi to prepare herself to elope with him. He even had a date planned—a week from today, on a nigh when there would be no moon. Mainak would have a taxi ready and waiting behind Vaidehi’s house. She would have to pack only the most essentials, and sneak out from the servants’ entrance, as the main big corrugated iron gate would be double pad-locked. 
Vaidehi gasped and related the contents of the letter to Dipti.

‘I couldn’t do it,’ she whispered, as the two sat pretending to look at books together, ‘ The shame of it would kill my parents.’

Mainak had planned to approach Vaidehi’s father once he got a job, but because of his subversive political background and police records, he had found most doors closed despite a Master’s degree in journalism. 

Once he had even received a call for an interview for the Indian Nation newspaper in Patna. But this offer had been suddenly withdrawn once the editor found out that he had marched in the anti-government parade last year on Independence day in August. Vaidehi had shed bitter and frustrated tears over this. 
‘Just my luck, ‘she had wept to Dipti, her confidante and messenger. 

Vaidehi and Dipti spent the rest of the afternoon, conferring gloomily and desperately by turns , as grandfather poured over his charts  in the next room with occasional clearings of his throat and requests for tea with basil and honey to take care of the tickle..

Rohini came in, full of almost- grown- up- sister importance, to remind them that it was time for 

Vaidehi to get ready. Dipti jumped up with a guilty groan. Hema would be upset if she saw that Vaidehi’s hair was still not done .

Vaidehi got up with a resigned sigh, and held out the boxwood and cherry wood comb set that Hema had newly bought from Chatterjee Brothers just for this occasion.

Dipti separatedVaidehi’s hair into eight strands with quick fingers, and plaited it deftly into an intricate mat of tresses,black ribbon and gold skeins. She  pinned the plait in a low slung bun with a turquoise antique pin, that had belonged to Didu, when she came as a new bride. It copied an old Persian  design of two birds , holding a bowl of perfume. . The stopper could be opened to pour out scented oil on the woman’s hair in Mughul times.. The replica had the same design, and Vaidehi pictured Didu dressing up for Dadu to come home, pouring out a drop of  the perfumed oil on her ring finger, and lightly rubbing it on her hair parting.  To this day, a faint flowery scent lingered at the tip of the stopper.

‘I bet they used pheromones in the oil,’commented Dipti, patting the last stray strands into place.’I wish Mainak could see you now.,’  she added, standing back to admire her handiwork. .

‘I thought you said you’d do just a loose  old bun of an elo khopa,’grumbled Vaidehi.  ‘What happened to that ? You could have done a less elaborate job, you know.’ .

‘I didn’t want Kakima to suspect me of being in cahoots with you,’Dipti whispered back. ‘Besides, Didu’s hair pin may bring you good luck, who knows ‘.

The guests were already seated in the drawing room.

The daytime covers of the sofas had been removed. The floors had been scrubbed and polished by Rajinder, and the whole house had been sprayed with Flit to chase away mosquitoes and flies, and then rose water attar had been sprinkled lightly to dispel the smells of marathon cooking . Incense sticks smelling of jasmine and bel -phul  burnt in strategic corners. 

Rohini was re- pinning the pleats in Vaidehi’s sari, while Aridra was running back and forth with running commentaries.

‘There’s a very fat man, Didi’, said Aridra in the loud sotto voce of a child who hasn’t quite mastered the art of whispering yet., ‘He’s the father’..

‘Shhhh’, hissed Rohini, trying to hush him
‘The mother looks very strict,’ continued Aridra, ignoring Rohini, and looking at Vaidehi sympathetically, ‘and she has a mouthful of paan.’.

Vaidehi now understood why her Mother in the past two days had been so intent on teaching her how to make a real classical paan preparation.-’as they did in the old time  zamindar and babu houses ,’ Hema had said. , ‘ Making the after dinner mouth- freshner is almost as important as making the payesh perfect for dessert’. Hema had even written out the instructions in her rounded script for Vaidehi to memorise. :

Wash each fresh leaf. Paint the inner side white with lime paste. Place a small amount of filling in the center, Fold it in the shape of a triangle, Pin it with a clove.. There was an elaborate description of all that could go into the filling. It  read like an alchemist’s mix to Vaidehi.—silver-foiled cardamaom seeds, rose petals preserved in sugar water, dry roasted coriander seeds, anise, fennel , saffron, coconut shavings, sliced sweetened betel nuts , catechu bark paste.

‘You might as well put in motor oil and the whole spice box too.’ Vaidehi had grumbled, irritated and miserable. ‘ And order a brass spittoon for her to spit the stuff into as well.’. 

‘Don’t be disrespectful ‘ Hema had given Vaidehi the warning look The ‘ She Who Must Be Obeyed ‘ look, as Vaidehi  had describe it to Maina , when exchanging family anecdotes. 

Paan was not customary in their house. It was an un-beautiful habit as far as Vaidehi was concerned, making the teeth stained reddish black from the juice. The only good thing she had heard about it was the fact that paan leaves had leukaemia curative properties in Ayurvedic Shastra treatments, something she had heard from Dadu from his reminiscences of his herbal doctor days. 

Hema had had the house and servants feeling hassled, in trying to obtain the moghai variety of paan leaves, apparently the best kind . Rohini’s job had been to obtain a good pinch of of liquorice yasthi-madhu powder from  Dadu’s medicine chest, to be used as a filling for the would -be mother-in law who was apparently a connoisseur of  this. 

Father had drawn the line at putting in granules  of Zafrani Zarda, derived from tobacco products, that produced the actual feeling of well being. In a household where neither cigarettes nor alcohol  had ever entered – tobacco grinds, even to please a groom’s family, was unacceptable. 

Vaidehi smiled inwardly as she thought of Mainak, and his love for Chaar-Minar cigarettes, the worst kind. Unfiltered tobacco, the toying with danger, the intoxicating aroma of smoke and sweat. She liked this on Mainak,like it were his signature smell, but on  no one else.;  and yet feared for his health. 
‘And the groom, Didi, ‘ pattered on Aridra, ‘ He seems real nice. He gave me a whole bar of Cadbury chocolate ‘.

‘Don’t call him a groom .’ snapped Vaidehi, a little more abruptly than she had meant to address her little brother. ‘He’s not one yet.’

A little before  six thirty in the evening, her father had come to escort Vaidehi down to the drawing room. At six thirty sharp she  stepped over the threshold into the room. Not a minute before or after. This was the time, the muhurat, that was astrologically auspicious for her, her grandfather had sanctified, a time when the Moon would enter her Seventh House in her natal chart, or some such thing, as Mainak would laughingly say..

Vaidehi entered the room in her maroon sari, pinned together by an array of large and small safety- pins to ensure every fold in place, several pairs of slender  gold bangles, the red and gold meenakari cloisonné ear rings reserved for very special occasions, and her Mother’s necklace with the ruby locket. She felt stiff and artificial. 

‘A cross between Madame Tussaud’s wax figure and a clown,’ she thought bitterly.

She remembered only in a haze how the next two hours had passed. Her mother had shown the visitors all the cross-stitched table- cloths, appliqué bed-covers, and sundry other embroidered pieces  that Vaidehi had done in her Home Science classes while in high school..

There had been an extended argument with her mother over this the evening before.  ‘You might as well show them the running stitch, stem stich , chain stitch practice pieces that I had done in grade two,’ Vaidehi’s tension had spilled over into every little aspect of what she was required to do for the ‘ showing.’  ‘ I feel like a performing flea’ . 

The portly would-be father- in- law  bit into his third samosa , and asked Vaidehi if she could sing. 

Vaidehi had demurely said ‘No', when Hema overheard this and quickly jumped in to say:’Oh, yes, she can sing'. She has taken classical voice lessons from an ustad for seven years.’

Immediately all the guests were clamoring for a song, much to Vaidehi’s increasing anxiety. She caught her mother’s gimlet look and  complied. It took her several minutes to think of a song to sing.
She was actually surprised that her mother had not hounded her to have something prepared. 

Perhaps Hema had  feared  that Vaidehi could go to the extreme of  standing out on the terrace in a thin salwar –kurta  during  the early morning dew time just to catch a cold  so she wouldn’t have to sing!

Vaidehi closed her eyes and tried to think of a Tagore’s song . The one that seemed to rise in her was ‘Kichhu bolb o boley eshechhilem ‘ ‘ I came as I had something to say ‘ , which she sang acapello with a slight nervous quiver in the beginning , but bold and free as she went deeper into the song.

They all clapped vigorously as she finished the song. She remembered with a tug in her heart how a few months ago she had sung the same song when she had made a clandestine visit to Mainak’s home with him.on one of their rare trips together.

Mainak and his father lived in  a small, two bedroom unprepossessing structure, a shack compared to the huge house she had lived in all her life. 

Mainak’s mother had died of tuberculosis when he was only twelve, and Vaidehi had marveled at how much like her Mainak looked in the large framed picture in their musty , small, dark parlor. 

Mainak’s father had lost an eye and a leg in trying to escape from prison, where he had been jailed for plotting with other Freedom Fighters at the time –to assassinate a British official. 

He had been black- balled from most jobs due to his jail record, and had to remain content with a low paying clerical job at the local State Bank. 

Vaidehi had understood then the passion for political justice and fairness for the masses that  ran in 
Mainak was inherited from his father. It was a glow that urged them on but it had taken its toll on both their lives.  

Vaidehi had sung several songs that evening at Mainak’s house, including this particular one she chose that day, as if singing it to Mainak again, in absentia.

Mainak had recited yards and yards of poetry from memory- Tagore, Nazrul, Bishnu Dey, Ram Basu, ShaktiChatto, Subhas Mukherjee as if they were a matching pair in a jugal bandi  musical lyrical duet..

Mainak’s father had nodded at her appreciatively . Vaidehi had been surprised at how openly he had accepted his son’s girl, and how different this had felt from her own family’s strict constricting views. 

Vaidehi was pulled back into reality by the young man, Devraj, leaning towards her  to ask :

‘What are you majoring in College? ‘ . She had answered him politely , but all the time her eyes had silently pleaded with him : ‘ Please don’t make this difficult for me . Please understand I want to marry someone else’. 

Devraj’s mother had chewed on one paan leaf triangle after another like cud, Vaidehi thought, and had to visit the bathroom a couple of times to spit out the remains. She had finally shifted the mound in her mouth to one side of her cheeks, and had asked Vaidehi to come and sit down next to her on the divan, She had patted Vaidehi’s hand and said,  ‘My son actually works in Bangalore . I hope you can accept being so far away from your parents,’. 

Vaidehi hadn’t answered her directly, but lowered her eyes in that particular gesture as she had been indirectly trained and expected to do as a shy young fawn of a girl from a protected environment. . 

The guests had eaten the rasgullas, chhanar murki, samosas, and shrimp cutlets with great expressions of praise for their large sizes,and gourmand taste. The guests had been quite unprepared for such food temptations in a small town, almost a village in a poor state of Bihar  . They  had sipped the Orange pekoe and Makaibari mix that Hema had brewed in her best English Royal Doulton teapot with the thinnest hairline of a chip that she could hide if she kept her thumb on the right spot , again with surprised delight that such good taste and  sophistication  could be expected in a rural area, so far away from the bigger cities. . They had left with promises to call the Basus with an answer the next morning.

Aswini had taken off his saved –for –special days Nehru jacket that he had worn for the occasion with the relieved air of someone being allowed to exhale bated breath, and commented that the visiting family and the young man seemed very decent. , He had a good job as an engineer, had respectful manners, and no younger sisters to marry off 

Hema was equally pleased.. She finally a piece of cutlet that she had been too keyed up to eat before, she mentioned that in a way the son living far off in Bangalore away from his parents was not a bad thing at all . It would allow Vai to get to run her own household and establish closer bonds with her husband faster. 

'They ate all that food ‘ , Hema, said, ‘That’s a sure sign that they liked Vaidehi. When we had gone to look ata girl in Varanasi for my brother, my motherwould not eat a thing, not even the special ladoo sweets they had brought in special from Delhi. That’s when I knew that my mother did not like the girl ‘.

Vaidehi left the room feeling unbearably miserable. She couldn’t bear to be a part of this conversation.

Later, much later that night Shivji and Rajinder  came into the dining room as the family sat there after dinner –to report that there had been  news of a huge  bombing in Patna, the state’s capital.  

Several people had been injured, including a prominent judge and his aide . All towns in Bihar were now under a state of Emergency, surveillance having been ratcheted up especially at the borders of Bihar, West Bengal and Orissa, Buses, trains , private cars leaving or entering a city were being stopped at check-points , and all airports of Bihar had been shut down.

The family piled into Atul-babu’s room to hear te eleven o’clock nightly news on  the big radio. 
The damage was far more extensive than servants’ sources at down town Darbhanga Tower and the newspaper hawker boys had conveyed. 

The bridge that spanned the Ganges river near Patna had been around eight o clock that evening. Credit for that had been claimed by the local Naxalite group. It was in protest  against recent cruel and unusual police acts of violenc, especially that of forcibly blinding prisoners for punishment before even the due process of law had taken place.

Though no one had died in the bombing, much damage had been rendered to the bridge. This  would bring much of the functioning of the city to a prolonged halt, In addition the bridge and it’s supports would need extensive repairs, and transportation to and from Patna to the other side of the river would be a nightmare.

Arrested soon after the episode, the newscaster went in his solemn tenor reading, were Mukund the Wolfman,  leader of the Naxalite subchapter of North Bihar and his two main lieutenants, Gopal Ghose and Mainak Ray.

It rained all afternoon the next day. 

Usually the rains would bring on the stack of monsoon ragas on the turntable –the line-up of malhars, malkaus. sarang.  But Vaidehi was shocked to hear strains of Maru Behag streaming out into the cold wet afternoon. A night raga played in the afternoon , and one of poignant loneliness and viraha –the heart cry of longing and loss that marks separation. Why did Dadu choose this raga of all ragas today, when she didn’t need those extra twinges. ? What was he thinking of ? Dadu who always instinctively understood her needs and emotions –today seemed to not read  her.
Bibi-dai  entered the family room , with laundry basket of dried clothes that she had rescued  from the outside nylon clothes-line just in time before the afternoon down pour started, and started folding them. 

Aridra ran around excitedly. peering closely at the earthworms, snails and tadpoles that seemed to have been awakened by the rains, and were crawling and coiling and jumping , as befitted each—all over the courtyard.

Rohini exclaimed ‘ Awful,’  ‘Yuck’ ‘ E-ma ‘ as she shuddered over the school  of frogs and small, harmless water snakes as they collected near the puddles of water near the courtyard steps. .
Vaidehi’s mood was as dismal as the day.

She was also angry and bitter. She had frequently begged Mainak to give up his militant political activities, but it was always difficult to get through to him in this matter. He would look at her and smile and enact a soliloquy from a historical play ‘Shah Jehan ‘ or quote Ovid or Kalidasa or Rumi, or completely disarm her with a compliment as if to perversely but charmingly say, ‘I don’t want to talk about it'.
Her dreams of ever marrying Mainal had always been fragmented and faint, but now with this new development—they were about to evaporate for ever. Not only was he an impoverished good-for nothing, but now an identified, if not condemned criminal as well. She trudged heavily upstairs and sat on the armchair near her grandFather’s bed, trying to distract herself, by flipping through the Desh and Bartamaan magazines.
 
'Dadu,' she said softly trying not to break into an audible sob, ‘Can we stop this Behag record, and try something happier like Hansdhwani or Tilak kamod , please Dadu?’.

Dadu looked at her for a minute. Why don’t we stop all the music for a bit ‘, he said , quietly, and just feel the silence.’

Vaidehi turned the turntable switch off and sat down.

The sound of the raindrops on the on the terrace and against the windowpanes soothed her for a bit, 
In a while she heard the distant repetition of prayers being sung from the nearby Ram temple, ‘ Jai Sia Ram , Jai Jai Sia Ram’, chanted to the thump thump of dholak drums . Vaidehi could feel one of her daydreams about Mainak coming on like a great epileptic spell, and  though she tried to stop it, she was swept into it. 

She remembered last year’ college trip to Janakpur, the  birth place of Sita, wife of Ram, and the epic Ramayan’s heroine. 

Vaidehi had been intrigued and thrilled to find that Mainak had taken a separate public bus , and turned up at the site  as well. Not wanting to miss a n opportunity to be with Vaidehi away from the onerous supervision of her family.

Vaidehi’s classmates rising to the occasion , had formed a cordon around the pair to allow them to walk away from the range of sight of the two chaperoning professors.

They had walked fast and had found refuge behind a bullock cart piled high with hay. It was not romantic but  offered  a temporary camouflage. They sat on a pile of bricks and chatted.

‘This part of Bihar was called Videha , centuries ago ‘, Mainak had said, making Vaidehi marvel as usual about how much he knew about a lot of different things. 

‘The farmer king who ruled here, was Janak. One day he was doing his royal duty of initiating the ceremonial sowing of the crops, and began tilling the soil with his golden plough. Suddenly, lo and behold, the ground parted, and there emerged this beautiful baby girl, Sita, whom he adopted as his own daughter.  Because she was born from the land of Videha, Sita was also called Vaidehi—so that’s the origin of your name.’

Vaidehi had listened in rapt attention as she did to all of Mainak’s words, as he spoke them with the well-spun magic of a born story teller, and his muted drama voice of an experienced stage actor who had taken many local stages by storm.
.
Vaidehi, daughter of the land, Maiden of the Earth. She had loved her name even more since then.

Mainak had taken out his ubiquitous Charminar cigarette packet, and was attempting to extract a cigarette. Vaidehi snatched it away from him, half- playfully, half seriously. ‘These are poison, for your lungs and heart’.

‘Who says'?, Mainal had begun his teasing  banter, which  meant that he would half drive her crazy with his charm and the other half insane with his incorrigibility. 

‘You might as well smoke those bidis they sell on the streets, They have even a higher percentage of nicotine.’ 
Vaidehi came to with a start as she heard her grandfather clear his throat through the mists of her dreams.. 
‘What’s the matter, dear ?,’ said Atul –babu, looking at her intently .
‘Oh, nothing, just these long  days of cold drizzles,’ replied Vaidehi, trying to sound casual. .

‘It’s something much more than that, it seems to me.’. . 
There was a period of silence. 

‘I don’t want to marry this man , Dadu , ‘ , she burst out suddenly, her eyes bright wwith tears.
He looked at her.’ Why not ?’.
‘I just don’t. Dadu waited a while and cleared his throat again, ‘Is there something you disliked? ‘
‘Yes, Everything‘.

‘He seemed a nice enough young man from when he came upstairs briefly to meet me, and from what your parents said ,’ Dadu remarked, sill looking at her. ‘Is anything else the matter ?’.

Vaidehi could not speak any further as tears were  rolling down her cheeks.

Dadu continued to ponder her silently ‘Hmmme,’he uttered finally. ‘Hmmme , Is this about the young man in the newspaper ? He asked. ‘ Is this about Mainak Ray ? ‘.

Vaidehi straightened up startled. . 
How did Dadu, this old man in his eighties, who never left  the house, and in fact had not left his room in three years –know about Mainak ?
‘How, how did you know‘ she stammered. ‘ Don’t tell me you saw it in my stars! ‘ She added with a faint smile. 
I met him once, remember?‘ said Dadu, his eyes with their ghost reflections of cataracts, now bearing a small twinkle. Yes, indeed, Dadu, had met Mainak during one of the latter’s devil-may -care visits to the Basu household, a place Mainak called the ‘lion’s den’.

‘How could you tell? ‘, asked Vaidehi , surprised and embarrassed.,
‘I saw how he looked at you , and how you looked back ‘.
Vaidehi was quiet, an amalgam of emotions quagmiring her words. 
‘I don’t think your parents have an inkling‘, he went on. ‘If you are serious about this young man and he about you, it will work , but it will not be an easy road‘.
‘I don’t see how it will work , Dadu ‘ asked Vaidehi , ‘ Everything seems such an impossibility.
‘Nothing is impossible if both people want it. But both have to want it truly,’ He paused .’Are you willing to wait ?’

Vaidehi nodded wordlessly. 

Dadu coughed slightly.
.
‘Well then. I’ll just have to find all your prospective bridegrooms’ horoscopes incompatible with yours for the next few years. ‘ , he said ‘ His eyes crinkled in a conspiratorial smile.

Later that day, Vaidehi heard her Father call Devraj’s father, Mr Das. The latter had wanted to move ahead with the arrangements, and have the marriage set for next Spring
Her Father’s voice was firm and without hesitation.. Since the horoscopes showed some serious conflicts, she heard her Father say, it would not be wise to proceed and though he regretted this deeply, he could not very well  go agaist his own Father’s concerns. 

Even later the sme day, Vaidehi had sent out a large wad of hundred rupee notes via Dipti to contact  the best lawyer in Patna, someone  who had political clout and the  fight in him to handle  even the most  impossible- seeming cases. 

With the right amount of money, a lot could be done.-- money that her grandfather had taken out from that large locked Godrej almirah in his room , money that he said he had been saving to contribute towards her wedding  trousseau.

The billowing winter rains had stopped late that night and the gentler rajani gandha scented winds had wafted away the light tattered  rags of clouds to reveal a starry sky . The mrigashira constellation sparkled .like a diamond toy animal  etched by a happy child.

A fresh crop of mushrooms had sprouted in the hollow of the guava tree trunk, and Vaidehi could see them  through her window, as a nodding bunch of survivors in the ocean of opal moonlight.

She smiled and tucked herself in for the first night of restful sleep in weeks.  
