# Cremation by Manisha Roy {-}

 *[This is an excerpt from my novel Professor Hamilton”s Passage to India (Yapanchitra Books, 2009, Kolkata, India.) The book is about the adventures and misadventures of an American physician who goes to India with a fellowship to do research in infectious diseases. Despite all good intentions, Dr. Hamilton faces huge problems in both professional and personal life. The chapter below describes one of them.]*
 
By the time Charles reached the sandy bank of a stream that skirted the village on the north, it was twilight.  From a distance he could make out a group of people who had already built a funeral pyre with layers of freshly cut wood and bamboo.  Bina’s body was already being hoisted onto the pyre when they arrived.  Sanat approached him gently pressed his palm to console him as if Charles had been the one who had lost a close relative. 

“I’m glad you came,” Sanat said.

“I really don’t know why I’m here. But I couldn’t stay away. I had to do something.” Charles whispered. Sanat nodded.

It was only forty-eight hours before that his Indian friends Sanat and his wife Sumita had requested him to help their young friend Bina, who had been ill with fever and an infected appendix. In his long career as a medical doctor Charles has seen many cases of infected appendix and he knew that the patient needed immediate surgery before the infection became fatal. With great difficulty Sanat arranged for an old car to take them to the nearest town – over thirty miles distance -- where there was a hospital. But Bina’s appendix burst before they could reach the hospital. Charles was devastated.  He was angry and frustrated that he could not save a girl from such a simple problem only because of the lack of any medical facilities in rural India.

Charles was doubly frustrated because this was his chance to give the young couple back something in return of all the help they offered him ever since his arrival to the village for his research on parasitic diseases. So far in his six months stay in India Professor Charles Hamilton, M.D. had succeeded in annoying Indian doctors and the American Consul General in the city with his over enthusiasm and his need to cut through the bureaucratic red tape. It was only after he had arrived to the village that he had found people who seemed to accept him with respect and eager to help. Sanat and Sumita welcomed him with open arms and their warm hospitality won Charles over.    

Barefoot men covered Bina’s body with two more layers of wood leaving her head uncovered but supported by the lower layers.  On one corner sat a few women, also barefoot crying softly.  Sitting in the center must have been Bina’s mother.  Charles wished he could do or say something to her, but refrained from it.  He was sure that Sumita had said what needed to be said to the family.  His only hope was that they wouldn”t blame him for what happened.  The western sky on the other side of the stream was still pink.  The sand banks stretched wide on either side of the narrow winter river.  Dots of light twinkled from a distant village.  A few crows and vultures sat quietly on a dark tree branch waiting for the burning to be over.  Charles felt a shiver.  It felt as though he was on another planet where people from this world go only to burn their dead.   

Stepping forward was a priest with a tuft of hair hanging on the back of his shaved head.  A piece of red silk was wrapped around his upper body over his clothes.  Lighting a torch made of bamboo and dry twigs, the priest gave it to Bina’s father and led him to the pyre.  The old man walked in a daze and touched the torch to his daughter”s mouth and repeated a few words after the priest.  The priest then took the torch from the father”s hand and lit the pyre at different places.  The dry winter air fanned the fire immediately, and soon smoke began to cover the place.  A wail from the small circle of women cut through the evening sky and Charles inadvertently put his two palms on his ears.  A stout, dark man with a red headband came forward with a big stick and began to poke and probe at the burning wood as if attending to a large fireplace.  The group of people eventually broke up, some going near the water to find driftwood or a stone to sit: others walking away.  Sanat led Charles away a bit and they sat on a rotting tree stem. 

“I was a teenager when my father died.  It was in Calcutta and he was taken to the crematorium of the city where the fire is never extinguished, they say.  The line of the dead was no smaller than the line in front of the movie house on the other side of the street.  I was at an age only to notice the bizarre aspect of death and I didn”t have the courage to feel anything else.  I didn”t know what my father”s death meant for me at the time.”  He stopped. 

By now an acrid stench of burning flesh hit their noses.  Charles felt nauseated, but didn”t dare take out his handkerchief from the pocket to cover his nose.  The wails from the circle of women became more subdued.  By now the sky was dark without a trace of color.  The only color was the hot orange of the fire, which was now blazing above the pyre occasionally spitting sparks into the air. 

Sanat wrapped his shawl closely around him and continued, “Since then I have been to many funerals where I have seen the burning of the body like this.  It takes me somewhere otherworldly and gives me a message that my own death is a religious event.  You see, for the Hindus, fire is a god who witnesses all our ceremonies including the rites of passage.  This god is present at weddings and embraces us at death.  Fire burns the mortal body to release the essence of life.  Watching the slow disappearance of a lifeless body of someone you love is the only way to accept death.”  
 
Charles was getting angry at Sanat”s philosophy.  How could any one feel better about death by watching the body of his child burn to ashes?  He said, “I don’t know what you”re talking about.  It”s none of my business, but I can tell you, if my daughter died without proper medical treatment only because I couldn’t get her to a hospital, I”d raise hell.  In my country we try hard to make treatment available to everyone.”  He paused briefly before adding in a lower voice, “I’m sorry.  It”s not easy for me to stand by and do nothing when something like that happens.” 

“But Charles, what could you have done?  We did everything we possibly could.  Bina’s parents are grateful for your efforts, but they accept their misfortune.  The philosophy helps.  Believe me, having lived in a village many years I now understand why and how they accept such tragedy.  Their only other option is to fight against all powerful gods, who are anything but predictable.  Tell me, with so much science, technology and good intentions, can you control illness, aging and death?” 
“Illness and aging to some extent, but not death.  Not yet.  But in the meantime, we save more lives than we did a decade ago.”  The words sounded out of place as soon as he uttered them.  Sanat touched his shoulder and said, “I’m really sorry, Charles.  It must be hard for you to be so far away from home.  I wanted you to come to watch this, because despite the stench and crudity of burning a body, one can see that this body is nothing but a shell even though it lived, loved, and laughed.  I don’t know how, but it helps.  Thanks for being with us.” 

Charles looked in the direction of the pyre.  The stench was stronger than before.  “I”d no idea that the body of a frail girl could take this long to burn,” he thought.  A woman was distributing shawls and wraps to the remaining onlookers.  Some went closer to the fire to warm up.  Charles forgot he had a sweater.  He could feel the warmth of the fire even at this distance.  Sumita joined them.  Her voice was broken from the tears she hadn”t shed.  They sat in silence. At some point Charles stood up to stretch his legs and walked slowly toward the pyre.

Bina’s father sat on the sand only a few feet from the fire, his eyes fixed on it.  Charles lowered himself next to him and touched his hand.  Sanat”s words were still fresh on his mind.  He remained sitting with the old man watching his daughter”s body being swallowed up by the crackling and spitting fire.

When the whole thing was over, the man with the red headband salvaged a piece of bone from the ashes and gave it to Bina’s father.  He also gathered some ashes in a clay pot and gave it to one of the women.  The priest accompanied the father to the river and chanted some mantras before the bone was thrown into the stream.  Everyone washed their feet and hands in the cold water and turned back to go home.  The man with the headband cleared up the remaining ashes and threw everything into the water.  Now that the fire was gone Charles felt the chill of the evening air and put on his sweater that was hanging from his shoulders.

“I convinced Bina’s family not to bathe in this cold water,” Sumita said to Sanat. Then she said to Charles: “everyone witnessing the cremation is supposed to bathe, then change into new clothes before returning to life again.” 

They began to walk back single file.  The sky was now clear with a million stars and a boat moon throwing a dim light.  The village was quiet except somewhere a night bird flew from a tree flapping its wings.  Following the silent procession Charles lost all his bearings and felt empty inside.  He was relieved when they approached his little house.  He declined Sumita”s invitation to join them for a bite and rushed into his house.      
