# California Stories - Welcome to California (Part 2) by Manisha Roy {-}

*[I studied at the Universities of Rochester and Chicago between 1960 and 1963 and obtained my second Master’s in Anthropology. In 1964 I went back to India hoping to live there a few years to finish the fieldwork toward my doctoral research. I was lucky to land a cushy job at the Anthropological Survey, Gov. of India as a research scholar which would offer me ample opportunity to do the fieldwork. Within a couple of months I discovered the dark side of this lucky break. I was 28 years old at the time and invited a lot of jealousy and animosity since I believe that I was offered the position due to my foreign degree over many senior and perhaps deserving candidates. I have written about this extremely painful time elsewhere (see My Four Homes, a memoir, 2015) but this article is not about my sojourn in India. I want to write about my re-location back to the US in 1969. The events below are experiences of my initiation to the next three years of graduate school at the Univ. of California, San Diego.]*

**Welcome to California - Part 2**
**The Traffic Police: Encounter 1**

Within a few months of my first year’s study, the chairman of the department of anthropology of UCSD asked me if I would be interested in teaching an undergraduate course at Long Beach University near Los Angeles. I was chosen partly because I already had a few years of teaching experience both in Kolkata and Rochester and I was also older than a typical graduate student because I lost five years when I was in India. I accepted the offer and began the job which involved driving over 90 miles each way every Thursday evening. Being brought up in a family headed by a father who was a stickler for punctuality (he worked for a British company) I was always nervous about not making it on time and always ended up rushing to places. So I drove faster than the legal speed limit often and that became a habit. Of course I kept my eyes open for the traffic police and was fairly successful in escaping the speeding tickets. 

One Thursday, as usual I was already late starting my trip and within forty miles on the highway I realized that I and my car were at the mercy of the notorious Santa Anna wind. I had not encountered this particular phenomenon in my decade long driving experience in this country, so I had to slow down. To make the problem worse and even dangerous, my car was a used Corvair, a production of Chevrolet Co. and the car that Ralph Nader wanted out of the market to save the environment. I was always pro-left in issues political and social and would have not bought such a car but my landlord a retired sea captain sold the car to me which, he swore was only two years old, in excellent condition and not a polluter. The car was owned by his daughter-in-law who was an air-attendant, therefore hardly needed a vehicle on the ground, he added. The car looked nice and the price was right. So, without consulting any one I bought it. Among other technical peculiarities the engine of this car sat in the back leaving the front as a trunk space.

Going back to that day on the highway in the clasp of Santa Anna, I could feel the problem of keeping the car on road because the light weight front of the car was no match to the force of Santa Anna wind. After a few minutes of futile efforts of driving safely I became nervous and stopped the car near a hill slope off the right lane. I got off the car looked around to see if I could put something heavy inside the trunk space to increase the weight to stabilize it. I saw some boulders along the edge of the break-down lane but none of them were small enough for me to carry to the trunk. That day I was formally dressed in a silk sari because there was a students’ party after my class and I was invited to attend. The clock, in the meantime, kept ticking. I had to solve the problem of stabilizing the car otherwise I’d never make it to my class still another good fifty miles away. I chose a smaller rock and began to roll it toward the car. 

I barely made it a couple of feet or so, when I saw a pair of large boots in my path of vision followed by a thunderous voice, “What do you think you’re doing?” I looked up from my low and bent posture to see a six-foot- uniformed man looking down at me. Two side holsters with hand guns at his hips did not escape my quick scrutiny. As I raised myself from the road somehow holding back my flying sari and hair, I saw the large Buick police cruiser behind my car. Before I allowed myself to be alarmed I told the truth,

“Hello officer, I was trying to move a rock to put in my car to stabilize it to drive safely in this wind. You see, I have to teach a class at Long Beach in less than thirty minutes and I’m afraid I won’t be able to make it. I’m so glad you arrived just on time. These rocks are so heavy! Could you help me out here, please?” Whether it was my exotic appearance in a flying sari or my embolden but polite request or both, his voice changed somewhat and said, 

“You cannot remove these rocks, these are state property. I see you have a Corvair, a risky car to drive, period. I shall pretend I haven’t noticed your illegal behavior. What do you teach?” He picked up a couple of boulders with ease and dropped them in the open trunk of the Corvair and even arranged them securely so they won’t rattle. “There you go. Drive carefully. Anthropology? What is it anyway?” He brushed his hands off and pulled the hood down.

“Thanks so much for all your help and for not giving me a ticket. You’re a perfect gentleman and I shall not forget you.” I said with my most seductive smile and started the car. The six-foot-tall traffic police with two handguns on his hips stood a bit puzzled by what just happened. I was sure it was not his run-of-the mill traffic incident. I did make it to the class fifteen minutes late and when I told the story to the students to apologize for the delay, they too looked a bit puzzled.  

**The State Police : Encounter 2**

My second police encounter did not go so well. About a year later – by that time I had got rid of the Corvair and owned a third-hand two-door Ford something. I even got an inspection done to make sure this was not a polluting vehicle and the engine was in the front.

As usual I was driving fast on the same highway going to Long Beach to teach one day. At some point a couple of police cars passed me with deafening siren and high speed. Relieved by the words ‘State Police’ on the cars I concluded they were after some big fish – perhaps an escaped prisoner or a murderer on the run. I also slowed down just in case. Within a few minutes another State police car approached and drove in front of me stopping the car signaling me to stop. I had no choice but to pull off to the break-down lane, stopped and rolled my window down. A Hispanic-looking officer with an accent, different uniform and hat asked for my license. Assuming it was a speeding ticket I kept my mouth shut and took out the license from the glove compartment and showed him. After looking at it for a few minutes he kept it and ordered me to open the trunk. Now I got annoyed. I was getting late and I had no idea why I had to open my trunk. I opened my mouth and said the wrong thing.

“Why do you want to see my trunk? I’m already late for my class.”
“OPEN THE TRUNK!” A thunderous order boomed this time. I missed a heart beat and turned off the car, took the same key bunch and handed that over to him through the open window. Instead of taking the key he ordered me again to open the trunk. Now I realized that at this point any argument was not only futile, he might even arrest me on charges of insubordination. I got off the car and opened the trunk with one of the keys. The officer bent his opulent frame with difficulty to look inside the trunk which had a tire and a few bags of old clothes to be donated to the Salvation Army and a bag of old books if I recall correctly. He asked me to empty the bags of their contents. Again I bit my tongue to stop myself from asking any questions. As soon as I scattered all the contents of one bag on the floor of the trunk he shouted at me to empty the bags on the road. By this time my anger had vanished. I felt like crying. The officer moved toward his cruiser and opened the back door and a leashed dog jumped out and began to sniff my old clothes and books. Now I got the drift. These state police cars with their drug-sniffing dogs were looking for drugs. But, why me?

After a few minutes of the dog’s inspection, the officer ordered me again saying, “You can go” and handed back my license. He and his dog went back to his car. No explanation, no apology – nothing! I put back my things in the trunk quickly and went back to the driver’s seat. I looked at my wristwatch to see I was already one hour late. But I dared not speed. I did not want another encounter with any police – traffic or otherwise. I was reminded of the gentleman officer I’d met a year ago. My California story could end here. But without a brief epilogue my fateful adventures with the California highway police force will remain incomplete.

**Epilogue:**

Three years and seven months later the day before I was leaving La Jolla I had a spin in my car for the last time. I had already finished my last exam defending my doctoral thesis followed by a big party on the Pacific beach with everyone I knew and sold the car along with other household staff. I kept the car for one extra day to finish my errands like returning the library books etc. There was a valley on the road between my studio apartment and the university library and I always loved that patch of the drive as the car speeded from the natural gradient. This time I may have pushed my accelerator a bit more to match my light-hearted mood as the car radio blasted my favorite Beatles’ song “Let me hold your hand…” When the traffic police stopped and accused me of going thirty miles over the legal speed limit, I blurted out, “But officer, I am in a good mood and may have speeded a bit. You see officer I just finished my studies here…” He cut me short and wrote a ticket and without any niceties left. I did not mind the ticket as much as I minded his ruining my good mood. Again I could not help thinking of the first and perhaps the last gentleman traffic police I‘d met and would ever meet. 
