# And then there was Amsterdam by Nilay Mukherjee {-}

The phone buzzed in Ronodeep’s cubicle. The caller id showed it was Neil Baxter. Neil was Ronodeep’s boss. 

 “Can you come into my office for a second?” Neil’s voice sounded tense and Ronodeep instinctively knew that this was not a good sign. Ronodeep was working furiously to finish his presentation before he and Neil left to catch their flight from Boston to Lyon. Neil knew about the hard deadline and the interruption could only mean one thing: there was a problem.
 
Ronodeep traversed the twenty steps between his cubicle and Neil’s office trying not to guess what could have happened. For the past month, he and Neil had been planning their way out of extinction.  A series of corporate reorganizations had left them without a home. As part of the last move, they had been attached to the Hernia Group in France, simply because there was no place else to put them. The company “valued their diverse skillset” and their “expertise in biologics” but did not know how to use them to further the newly redefined corporate vision. Laying them off would have made business sense, but upper management was trying not to initiate another disheartening round of reductions unless they had to. Neil and Ronodeep were given an option:  they had to define their own value proposition in the new setup. “Make yourself useful or be gone” was the unmistakable message. 

Undaunted, Ronodeep and Neil had worked hard to find something useful to do. The Gurley machine was their savior. Neil had discovered this little known apparatus used to measure the bending stiffness of paper and had rigged it to be able to do the same thing in hernia meshes. Why was this important? It turns out that hernia meshes are used by physicians to keep vagrant bowels from exiting the abdominal cavity through weak spots.  They look like woven pieces of netting material:  some third world docs have even fashioned hernia meshes out of mosquito nets. A drawback is that the meshes are too stiff compared to the abdominal musculature on which they are sewn and this mismatch in stiffness causes pain in patients. There was a clear mandate from surgeons: They wanted meshes that did their job of keeping bowels from herniating, but they had to be less stiff. The issue that plagued the Hernia Group in France was that there was no cheap and reliable way to measure the stiffness of these meshes. Thus, there was no way to know if the various “fixes” the group thought of to try to change the hernia meshes was actually pushing the stiffness of the meshes in the right direction. That was until Neil thought of the Gurley machine.  The Gurley could be their ticket to becoming useful to the Hernia Group, but Ronodeep and Neil first had to show that the concept would work.

Ronodeep had used his Six Sigma Black Belt experience to validate Neil’s proposal of using the Gurley machines to measure the stiffness of hernia meshes. Despite skepticism from the manufacturers of the Gurley machine, he was able to demonstrate differences in stiffness between various types of hernia meshes. It looked like the machine possessed enough discrimination for the job. But was it reliable? Ronodeep got four different operators to try it and had shown that variation in results between different operators was small. A batch of new samples had arrived from France and were tested.

Ronodeep’s statistical analysis showed encouraging trends and his French colleagues were excited. At last it seemed that Neil and Ronodeep could do something that was going to be highly valued. They were summoned to the French headquarters near Lyon to present their data and Ronodeep had an hour to finish his presentation before he and Neil were due to leave for the airport. 

“What could have gone wrong?” Ronodeep thought as he knocked on Neil’s door and poked his head inside.
Neil was sitting with his feet up on the desk, phone in one ear and looking at his blackberry at the same time. Ronodeep’s years of association with Neil had prepared him for this extravagant display of multitasking. He was not offended when Neil did not look up to acknowledge him: Ronodeep knew that his boss had Attention Deficit Disorder (ADD) and this was how he managed his life.  After 30 seconds, Neil hung up the phone and immediately launched into a series of expletives drawn from his hunting experiences while growing up in rural Tennessee. 

“These French bastards are ambushing us”, he finished with a flourish. Ronodeep waited patiently for Neil to come to the point, which he eventually did. 

“They bought themselves a Gurley.” he exclaimed.  “Can you believe this mess? They are trying to pull the rug from underneath our two feet!“ 

Neil continued addressing his invisible adversaries: “Son, I ask you where you were when I came up with the damned idea.” He waved his hand compulsively.  “Sheeet!” he grimaced, drawing out the syllable for maximum effect.  

A silence ensued while Ronodeep mulled over the implications of this latest bit of news and what the best way to react to it would be. They were being scooped, no doubt about that. Would it be better to play nice and teach the French everything they knew and at least get credit for being a team player? Of course, that meant the search for being useful would have to start all over again. Or should they stonewall the French until they gave up on trying to figure out the machine and returned the testing duties to them? It could work, but it carried the significant risk of alienating the French. Also, what if they were able to figure it out: it was not such a hard thing to do once you knew a few tricks.

“Your Taxi is here” Martha’s voice sounded over the intercom. Ronodeep was in the process of shutting down his computer, so he was out of his cubicle in less than a minute. Neil joined him and together they took the two flights of stairs to the front of the building, Neil playing with his blackberry all the time. “Some day that man will fall down the stairs and break his neck” Ronodeep thought.
The Taxi turned out to be a SUV: nice and spacious with enough room in the back to hold their bags. Martha obviously knew her job and Ronodeep made a mental note to thank her when he came back: you can never be appreciative enough as far as the “admins” were concerned. The driver was a middle-eastern-looking, young man who informed them that there was internet access in the taxi if they wanted to surf. 

“What terminal is your flight going out of?” he asked. When neither Neil or Ronodeep could remember rightaway, the man opened an app on his I Phone: “Terminal E for international flights” he announced after a short while. ”Your password for internet access is CABONTHEGO.” He smirked a little as he spelt it out.

While the taxi speeded down I 93, Ronodeep surfed the net, not because he had to but because he could. He had never surfed while riding a taxi and the novelty of the G3 router next to the dashboard that connected him to the rest of the world was too much for him to pass up. He decided to check what it could do: No, it would not run Netflix: streaming video was too much data to handle. YouTube was also very slow: Ronodeep was starting to despair, when he thought of Facebook. He opened his page to see that 8 new notifications were pending: the closed group of his high school graduating class had been active. After he read accounts of one of his buddies bragging about the single malt scotch he used to dull the post surgical pain of a tooth reconstruction and a rather spirited argument over who was more sexy: Suchitra Sen or Aparna Sen, Ronodeep felt the need to post something. Skillfully handling the slight bumps in the road, his fingers raced over the keyboard as he wrote: “Posting from the back of a cab as I glide on I93 towards Logan. My boss thinks I am hard at work! This is glorious!” He quickly changed the page, half glancing towards Neil to see if he had been caught in the act. Luckily, Neil was still glued to his Blackberry, typing out messages with two thumbs.

The engine showed signs of overheating and for a while it looked like the taxi driver was going to pull over and call for help. Neil spotted it even as he continued his online communications and deftly handled the situation. Using expert vocabulary aimed at establishing his credibility as an automobile expert, he convinced the driver that he could “make it” to the airport without breaking down. In reality, they would have missed their flight, if the driver had to pull over and wait for a replacement. Things got tense for a while as the driver kept checking the temperature gauge and swearing under his breath in Arabic. Fortunately for Neil and Ronodeep, he decided to keep going and they arrived in Terminal E without incident.  An hour later, they were aboard the 747 to Amsterdam.

“I am going to order me some Gin and Tonic, so I can get some sleep on the flight. We are going to need our strength in Amsterdam.” Neil winked at Ronodeep as he pushed the attendant button over his seat as soon as the plane reached cruising altitude. Ronodeep had just begun to look at his travel plans in some detail (he had only scanned them before) and was slightly puzzled. They were going to arrive in Amsterdam in the early hours of the morning. However, instead of catching a connector to Lyon right away, they were spending a day in the city, staying at the Marriott and then go on to Lyon the next day. Five days in Villefrance, a small town near Lyon, then back to Amsterdam, spend another night there and then catch the plane to Boston: that was the plan. Neil’s comment began to make sense to Ronodeep. Neil had built in some R&R (Rest and Relaxation) time in Amsterdam: that became obvious. Perhaps there was a shade of concern that showed itself on Ronodeeps’ face, so Neil launched into an explanation:
“The flight to Amsterdam is over 6 hours long. That entitles us to first class travel per company regulations. But we are busting our butts back here in coach to save the company some cash. No doubt, we are going to be stiff as a board when we land. I am going to need a day to get over my jet lag so I can be prepared for them French hogs!” Neil smiled conspiratorially. Ronodeep knew the numbers: Neil had a point. Business class fare was $5000, coach was only $600. It is easy to justify a couple of additional days of hotel and meals if they travelled coach. Of course, there was another reason why Neil had chosen Amsterdam as the place they would spend their recovery time: Ronodeep instantly guessed what it was and he conspiratorially winked back. He too, ordered a gin and tonic, moved his seat back and tried to make the best of his cramped situation. The more he slept on the plane, the more he would be awake in Amsterdam: that was incentive enough. Now if only, that child two rows behind him would stop wailing!

Schipol airport in Amsterdam was large and busy. Ronodeep had not used it in over 7 years and it seemed a little older and a little bit worn down from what he remembered it to be.  They passed through customs without incident and made their way to the train station that would take them to Amsterdam Centraal, the center of the old city. As Neil and Ronodeep came out of the station dragging their bags behind them, they were accosted by overcast skies and a light breeze. Ronodeep looked up, noticing the old architecture: he had read that some of those buildings were over 300 years old. They were long, narrow structures with sloping roofs, stacked next to one another. Each one of them had a large protruding hook constructed into the top floor. “These used to be warehouses” Neil said. “Those hooks were used to haul merchandise onto the top floors”. Ronodeep was also fascinated by the bicycle stand next to the train station. One of the few multi-level bicycle parking lots in the world, there were literally tens of thousands of bicycles parked there. Most of them were rusty, utilitarian bikes that got you around from point A to point B: it was apparent that their owners would not care too much if they got stolen. 
Neil had been to Amsterdam before and started pointing out various things to Ronodeep as they walked over the mossy, stone paved roads. “The old city has a ring of concentric canals. There is the Herengracht or Canal of the Lords, the Princengracht or Prince Canal and the Kaisengracht or Emperor Canal. Then there is the Singelgracht which serves as a moat.” Ronodeep tried to imagine what things would have looked like a few hundred years ago. He remembered some of the descriptions from Chevalier’s novel: Girl with a Pearl Earring and tried to imagine the scenario: the herring ships offloading their catch to be gutted, salted and barreled, the wind-powered sawmills churning out Baltic timber for shipbuilding, the Dutch fluyts setting out for the East Indies and the New World: this was where all of that was happening! It seemed so different and quiet now.

Ronodeep also tried to reconcile what he was seeing with the pictures of Holland he had seen peeking out behind the smiling faces of his friends on Facebook: that Holland was full of tulips. There was no sign of tulips on this cold winter morning. He remembered Dutch stories he read as a child where windmills figured prominently and the boy who bravely put his finger in the dyke. He looked around for these massive structures but all he saw was paved roads and small bridges over the canals staring at him in the depressing light of the overcast morning. They were somber in their ancient attire, blackened with age: Ronodeep realized he was going to have to fall in love with the old to appreciate Amsterdam.  The houseboats on the canals were rather rickety as well, so it was a relief when they arrived at the Renaissance Marriott and found it to be thorough modern, albeit with a distinct European flavor. They checked into their rooms: Ronodeep stashed his passport, dollars and computer into the safe in his room, fished out what euros he had remaining from his last trip to Europe and took the elevator to the lobby to join Neil, who was pacing around, bursting with energy.

They set off, exploring the shops of the old city: boutiques, novelty item stores, cafes and coffee shops. A coffee shop in Amsterdam is a euphemism for a marijuana bar. Rondoeep had read somewhere that the Dutch, being primarily a nation of traders, quickly realized the immense tax-earning potential of legalizing marijuana and prostitution. In one fell swoop, they got around having to police their borders for illegal trafficking, building a large prison system to house offenders and deal with criminal gangs vying for territory. Instead they gained a steady stream of tourists and guaranteed tax income from the sales of some of the best regulated, quality controlled, marijuana in the world. The same could be said for the legalized sex trade: prostitutes are routinely screened for diseases and their incomes taxed. A few rowdy tourists and the occasional vomit on the sidewalks: that was a small price to pay for all these benefits.

Neil entered a coffee shop with the calm assurance of an experienced customer. The man at the counter, more a boy than a man with a metallic lip piercing, greeted them in good English and pointed them to their choice of “weed”. Neil began his educational tutorial as he looked over the menu that bragged of twenty different kinds of pot and hashish: “There are three ways of smoking pot” he declared authoritatively. “You can mix them with tobacco and smoke it like a joint, you can smoke it all by itself like a reefer or you can vaporize it”.

They had taken a booth with their recently purchased gram of what the boy described as ”this will make you relaxed in the morning” weed and another gram of Moroccan Hash when Neil pointed to a contraption that looked like the base of a Kitchen Aid mixer/grinder. “Tetrahydrocannabinol or THC is the psychoactive constituent of the cannabis plant and is excreted as a resin. It vaporizes at roughly 180 °C. At that temperature, the rest of the bud does not burn. So you get the entire buzz and none of the other harmful effects of smoking.” said Neil, with a smile. He ground up the weed and carefully transferred it to a receptacle on top of the vaporizer. Next, he affixed a large, transparent plastic bag over it and turned on the “fan” inside the vaporizer. The bag filled up slowly, with what looked like faint smoke. Once it was full, Neil removed it carefully and put a valve-like device on the end. Exhaling deeply to expel air from his lungs, he put the valve to his lips and began a long, slow inhalation process. When he could go no more, he held his breath for what seemed like an eternity to Ronodeep, and then slowly exhaled. Only a few wisps of smoke escaped: most of the THC was absorbed into his lungs and was now speedily finding its way to his brain. He handed the bag to Ronodeep. “It’s all good” he said with an air of satisfaction.

Ronodeep had not smoked pot before. Sure, in college he would hang around the potheads: they were the creative types and had the best insights to share with him. It was a relief from his more grounded, engineering friends. For some reason, his lungs could not handle smoke. Every time Ronodeep tried to puff at a cigarette, he would double over coughing and gagging. This peculiar disability had saved him from cigarettes and ganja in college and probably ensured he stayed on the straight and narrow path of academic success. Now, with a job and family, visiting a country where smoking pot was legal, and with the aid of enhanced vaporizer technology, he would finally get a taste of what it meant to be “high”. He had been drunk before, more times than he cared to remember, but he had never been “high”. “Byom Shankar”, he muttered under his breath and inhaled.

The first few hits did not seem to affect him. “Large body mass”, Ronodeep thought of his 6 ft 2 in, 260 pound frame, “Give it time”. And then, it started happening slowly. As he looked around in the dimly lit coffee shop draped in red wallpaper, he noticed the other inhabitants of his den. They were mostly younger couples cozying up to each other, smoking, laughing. Ronodeep realized that the girl behind the counter seemed so much sweeter than just a few moments ago. This was not the lustful rush that he normally feels when he spots a young nubile saunter down the street as if she was a model walking down the ramp. This was a more mellow feeling: he just wanted to look at the girl and felt a kind of affection for her. As he felt his face warm up and his throat began to dry, Ronodeep thought “I am officially in lalaland!” He smiled at Neil. “It’s all good”, Neil said, his eyes glazed over and red.
Ronodeep could feel the music more intensely as his buzz ripened. He recognized an old Pink Floyd favorite: Brain Damage. He had heard the song many times before, but the lyrics made more sense now: “There is someone in my head but it’s not me.” Yes, he was definitely feeling the beats. He could hear the clouds burst, there was thunder in his ear. He suddenly knew what the dark side of the moon was like. “Yes man! I feel you.” he chuckled under his breath as laughter rolled out from the speakers “I can’t think of anything to say except I think it is marvelous!”

“Come on man! We gotta roll!” Ronodeep jerked up with a start as he felt Neil’s hand on his shoulder. He had dozed off and now, as he slowly came back to his senses and stumbled out of the coffee shop, he experienced for the first time, the other side of THC. His throat was parched. “Cotton Mouth” Neil explained as he handed Ronodeep a bottle of water: the experienced partner had thought of this eventuality. Ronodeep realized with some alarm that his sense of balance was not all there. The sweet buzz from before was gone but the sense of imbalance remained as an inconvenient aftereffect. As he walked carefully along the narrow sidewalks of Amsterdam, avoiding cyclists at every crossing and occasionally holding onto something for support, Ronodeep desperately wished for his light-headedness to go away but it would plague him for a few more hours. “We gotta eat”, he said, hoping that sitting down will help him work it off. “We need some chow before we go see the museums”.

They settled for a middle-eastern restaurant and ordered a large meat platter: ganja makes you hungry. As they dug into their lamb chops and shawarma and washed it down with cold Amstel, they watched a football game on the big screen. Over the next few days, Ronodeep would note that football was everywhere: there were games every day and when there were no live games, there would be full length replays of the more important ones.

His blackberry buzzed and Ronodeep whipped it out, a habit ingrained in him from his years of corporate experience. One of his Bengali buddies, a provocative poet and a business consultant rolled into one, had sent out a mass e mail wishing everyone Happy Bengali New Year. He had ended with ”I hope everyone is having good Bengali food wherever you are!”

Ronodeep chuckled and started typing away on his blackberry “Having good food. Unfortunately, not Bengali. Amsterdam is good for many things but if you want Muger Daal with Begun Bhaja you are out of luck”.

Ronodeep had hardly taken another bite when the blackberry buzzed again: His considerate, if slightly bored friend had taken the time to Google Indian restaurants in Amsterdam and had sent him a list. He had recommended the Maurya, based on user ratings.

Ronodeep replied: “Google Zindabad! However, I doubt even the Maurya will have what I am craving for. I guess I will have to drown my sorrows with Amstel instead” 

Within 90 seconds, he got the following message: “No muger daal or begun bhaja here in NJ, but there is payes, pati sapta, makha sondhesh, darbesh.... I am happy!”

Ronodeep felt a deep pang of emotion when he was reminded of these culinary delicacies, particularly the pati shapta. This was a wonderful Bengali creation: a crepe with coconut filling that was made only during winter festivals. Ronodeep remembered watching his mother make the coconut filling when he was a child: carefully grinding the coconut with a special tool he had not seen anywhere else in the world and then boiling it in molasses until it became a sticky, brown mass. He suddenly hungered for its rich, sweet taste tempered with the slightly salty, crispy crepe. 

He typed back. ”Food envy is weird. I am having a delicious apple strudel and all I can think of is pati shapta” Ronodeep thought for a moment and typed some more.

“This raises a philosophical question….. If.... Even in the land of weed and red lights I have to "make do" with apple strudel instead of pati shapta..can there ever be a heaven on earth?...If we always have to "make do"... why not "make do" with less and less? Can U drive it all the way to "ajagar protha" where you only eat what drops into your lap? The Buddha tried and gave up so that demotivates me a little from trying, but to the intellectually curious the question remains.”

There were no deep, philosophical answers that floated back over the Atlantic. Instead, a few other people in that e mail chain jumped in and offered their condolences. 

One of the more well-travelled members of the group, a Jungian psychoanalyst by profession commented: “I'm intrigued by the power of Bengali food-love: we Bengalis will order our individual comfort food even in heaven before our fate is decided by whoever decides these things.” She probably sensed Ronodeep’s despairing mood and tried to nudge him in the direction of what he could expect to enjoy. She wrote: “There is a delicious thing available in the duty free shops of Schipol. It's a liquor called Laka, which is made from an arctic berry called cloud berry because these berries are shaped like clouds. This poetic origin aside (or perhaps because of that) this liquor has the most exquisite taste.”

After they had sated their surging appetites, it was time to feed appetites of another kind. Ronodeep and Neil spend the next several hours taking in the sights of Amsterdam. They went to the Van Gogh Museum, The Rijks Museum and the Anne Frank House. Ronodeep, used to the massive museums of New York and Chicago was less than impressed with the size of these museums, but he was more than happy to view, in real life, a lot of the paintings that he had seen only in coffee table books of Art. 

There is something suspenseful as you walk up to a masterpiece: a sense of anticipation and dread. Half of you is giddy with expectation and the other half mentally preparing to be disheartened. Part of your mind is determined to let in the feeling of awe that should come from viewing a masterpiece while the other half is rebelling against mindlessly accepting a masterpiece as magnificent. Regardless, many of the pieces managed to surprise Ronodeep in their own way. The Night Watch, by Rembrandt for example was enormous, filling up an entire wall and even though Ronodeep was anticipating a large painting, he was taken aback by its colossal size.  Although he knew of Rembrand’t clever use of light and shade or chiaroscuro, as it is called in the artistic lingo, he was mesmerized by how easily his eyes followed the light to the main characters. They almost seemed to be moving! Later, when he read the blurb beside the painting, he learnt of the chiaroscuro and the various tricks Rembrandt used to create a sense of motion. Ronodeep had read similar descriptions before, but now he understood what they meant. A parable he had read in his youth floated up to his consciousness: You can describe a rosogolla, you can show somebody a picture of a rosogolla but unless you let him eat it, he will never know what a rosogolla truly is”.

Ronodeep decided to take an audio-tour guide at the Van Gogh Museum. He needed to cover it in less than two hours and the tour guide promised to take him to the most important pieces and provide commentaries as well. As he walked by hundreds of canvases, Ronodeep marveled at the portraits, was fascinated by the still life and wowed by the landscapes. However, taking a tour guide has its own unique advantages and disadvantages. You feel like you are being led by the hand through a maze but you are also being told what to think. Ronodeep appreciated the first aspect but he was slightly put off by the second. For example, he heard at least three or four times in the commentaries that Van Gogh was heavily influenced by Japanese woodcuts or ukiyo-e as well as their silk scroll paintings and prints. He noticed the Japonist influence right away when he heard the commentaries, but knowing that somehow diminished the experience for him. In his mind, Van Gogh had occupied the position of a visionary: whether by disease, madness or pure genius, the man had managed to see sunflowers like no other man before him. Now Ronodeep was being told that he was just like other people: influenced by what he saw, limited to the sphere of his experiences. He did not want to hear that Van Gogh had tried and failed to make the human figures look natural in the Potato Eaters: the painting spoke to Ronodeep as a caricature and he refused to give up that image. Then there was the depression of dealing with false expectations. Starry Night is perhaps one of Van Gogh’s most famous paintings. However, it is not in the van Gogh Museum in Amsterdam. Ronodeep did not know it at the time and he was looking forward to seeing it at every turn. He would not get a chance until a few months later when he was at the MOMA in New York.

Anne Frank House was a revelation for Ronodeep. He had imagined a small hideout in a dark, damp corner where Anne and her family cowered for two years before an anonymous phone call tipped the Germans to their presence. Instead, it turned out to be rather spacious accommodations at the back of a spice factory and warehouse. Of course there were difficulties: they had to black out the windows and not flush the toilet after dark so as not to tip off anyone else that they were living there. Also, there was a rather ingenious bookcase and steep staircase that guarded the entrance to their secret apartment: boundaries they could never cross. Ronodeep was impressed by Anne’s neat longhand: he had been struggling to improve the hideous scrawl that his 9 year old son called handwriting. He was also struck by a video recording in which Theo, Anne’s father mentioned how surprised he was when he actually read Anne’s diary. He thought he was close to her but he concluded that most people do not really know their children. Ronodeep wondered how closely he knew his son. But then again, did he really want to know what dark thoughts were ruminating inside that lovable head?

Neil had given up trying to keep up with Ronodeep’s culture binge and had gone back to the Renaissance Marriott to take a nap. He now called and wanted to know if Ronodeep was ready to head to the other tourist attraction of Amsterdam: the famous Red Light district. Ronodeep had always been curious about this place. When Ronodeep was a teenager, his father had gone on the lecture circuit in Europe. He came back laden with delightful “foreign” gifts and stories. Ronodeep had heard his father mention the Red Light district in passing and his surging hormones had romanticized that place into a dreamland. He was looking forward to the place: curiosity, hope and passion coursing through his brain in equal measure.
The layout of the Red Light district was pretty much what the brochures had described. In the streets and by alleys were hundreds of small apartments, mostly on the ground floor. The red fluorescent lights were on and girls stood behind glass doors displaying their wares. Ronodeep peeked into a few of the apartments and they seemed to be pretty basic: a bed with a thin mattress, a sofa, a bathroom, a washbasin and a thick wad of paper towels. A few had curtains drawn: presumably there was behind-the-scenes action. Hundreds of tourists milled around watching. Ronodeep was amazed at how many women tourists there were: they came in all ages and nationalities. This was no seedy place where men secretly ducked in and out of forbidden alleys: this was a celebration of sex: curious bystanders outnumbering potential clients ten to one. Ronodeep wandered why the women tourists were there: perhaps they wanted to see how they compared with the professionals?

The “women of the night” came in all nationalities, shapes and sizes. There were a lot of Asian women, but there was also the Scandinavian types and a few African girls. Many were middle aged and not all that desirable: Ronodeep was reminded of Fantine, the hopeless grisette in Les Miserables, who had sold her hair and two front teeth, prostituting herself on the streets of Digne while she slowly died from tuberculosis as she tried to pay for her daughter Cosette’s upkeep. Ronodeep felt a small shiver down his spine, as he hoped none of the women here were that desperate. They certainly did not look like that: some were blowing kisses at passerbys and looked like they were trying to generate some business, but most of the girls stood around looking bored or talking on their cell phones: Ronodeep figured there was a lot of downtime in the prostitution business.

There were other kinds of entertainment at hand. For 25 Euros you could go in for a demonstration of live sex, girls playing with phallic instruments, dances of various kinds: you take your pick. Ronodeep and Neil wandered the streets until their curiosities were satisfied. Both loved their money and were unwilling to pay 300 Euros for half an hour with a prostitute or even 25 Euros for a 3 minute dance. Plus there was the inconvenient fact that they both had wives back home who would not take too kindly to this behavior. And then, there was the specter of disease: despite the regulations and frequent checkups that the sex workers had to go through, sexually transmitted disease rates were pretty high in Amsterdam.

As the evening wore off into night, Ronodeep started to feel the limitations of his body. His feet were sore from walking a lot, his nerves on edge from the cornucopia of sensory input. They had repaired to a bar and were now sitting with large mugs of Amstel in front of them. It was crowded and the music was throbbing in Ronodeeps ears. The waitresses would sometimes get up on the table and dance for a few minutes to get the crowd roaring. Girls moved around with boys in chase. Couples were kissing in corners while at other corners, the unlucky man was being pushed off by some haughty girl. Ronodeep was too tired to actively pursue his voyeuristic instincts: mostly he just sat there and let it happen before his eyes. An Indian-looking girl tipped her drink at him and he barely nodded. She went off and a few minutes later he saw her dancing with an older man: a faint tinge of “what might have happened” shivered through him but his inertia was stronger. Ronodeep realized his party animal days were behind him. He now mostly longed for the comfort of his bed. It was time to retire for the night.

As he lay back in his bed at the Renaissance Marriott, Ronodeep’s thoughts drifted to their trip ahead. The specter of the French problem resurfaced in his mind. He was too tired to think actively about it, so he just let it float around in his consciousness for a while before he drifted off. In his dreams he saw Uma Therman as Fantine, running the Gurley machine, smiling toothlessly at him under a starry night. The French were smiling too and Neil was saying: “It’s all good!”


