# The Marijuana Talk by Nilay Mukherjee {-}


So, we were getting into my car: my son and I. We had just watched the Fantastic Four. It got 8% on Rotten Tomatoes, but my son wanted to see it anyway because he had read the book…. ahem… the comic book….ahem..the graphic novel (as he reminded me). He thought the movie was low on action, but remained faithful to the original storyline. Good! But that is not what this story is about.
As we were getting in, a car pulled up next to us and four teenagers got out. As soon as they opened the door, my nostrils smelled a smell that I had not smelled in a long time. Ahh…. It was truly aromatic! “Pot”, I said before I realized what I was saying. “Those kids are smoking pot.”
Now, there are various responses possible to this statement. My son could have ignored me, like he so often does. He could have said, “What’s pot?” absentmindedly, as he changed the station on the car radio and then forgotten about it. But that was not what he said. Instead, beaming from behind his spectacles, he adopted this faintly mocking tone and asked: “How do you know that, hmmm?”  
I backpedalled furiously. In my panic, I took refuge in chemistry: I explained how THC, the active ingredient, was an aromatic that evaporated around 180 degrees Centigrade, hence the smell bla bla bla. But it did no good. My son, simply waited me out and repeated the question: “How do YOU know that smell, hmmm?” The unspoken question hung in the air. I thought for a second if I should go the “I smoked, but I did not inhale” route and decided against it. Blurry visions of Amsterdam flashed by. Then I hit upon it: “Son”, I said in my gravest tone. ”Marijuana or Ganga is considered to be a holy thing in India. Many Sadhus smoke it. Everyone over there knows that smell”.   Phew! I had dodged a bullet…..or so I thought.
I was hoping to move onto other topics, but his next comment gave me pause. “Don’t worry” he told me. “It is legal in Massachusetts!” 
“Now, wait a minute,” I said. “It is NOT legal” I said vehemently.
 “It is”, he said, in a cool, confident voice.
“OK”, I thought. “It is time to have the talk.”
“Look son,” I said. “It has been partially decriminalized. That is not the same thing”
“What?” said my son…. And that was all the opening I needed.
“Son”, I said.  ”The Federal government still considers it as an illegal substance. But many states changed the law because their jails were filling up with non-violent offenders who had just a little bit on them, for recreational use. Now, they decided to go for the dealers, so they only catch people who have a large amount on them, with intent to distribute. It is still illegal to buy and sell it.”
“But”, my son interrupted “ In Colorado……”
“This is not Colorado”, I said with some heat. “Now, let me tell you the various levels of laws that exist. First, scientific studies have found that marijuana, smoked safely…that means while NOT DRIVING A CAR…does offer pain relief and has lower addiction potential than many over the counter medicines. So, many states, including Mass, has allowed medicinal usage: that means you will need a doctor’s prescription to get it. Colorado has gone a step beyond that and allowed recreational use: which means that it is no different than buying beer or wine. But the federal agents can still arrest anybody who possesses pot, don’t forget that. And many people are still worried about how the law will be abused: so we just have to wait and see.” 
My son maintained his smugness through my heated diatribe. Then he said: “I already know all that. They taught us this stuff in Health class, right before we studied about Sexual Assault.” 
I decided to let it go. 
