# Niagra Falls by  Nilay Mukherjee {-}


She climbed the railing that separated us from a swift death

The dark, green waters of the Niagra
Menacing

Only Six feet deep

Flowing faster than the proverbial “torrent” 

Its Herculean force not yet unleashed

But it is all there

Very much there

If you looked closely, you can almost feel its power, drawing you in

A hundred feet away, the water poured over the edge into oblivion

You can hear the roar as it rushes by Hurricane Deck

The water smashed into a million particles of spray

Diamonds glistening in the sunlight next to the rainbow 

She climbed the railing that separated us from a swift death

I, boxed in by the crowd, could reach over and grab her arms
But I froze

Lest a small mistake caused her to loose her balance
I, in my mind’s eye

Can see the newspaper headlines:

Teenager swept away by Niagra Falls
Victim died trying to photograph herself while hanging on the wrong edge of the railing

I can see her drowned face

Pale, eyes slightly open

Under the dark green waters

I can see the grieving parents leaning over the crushed body

And then, the younger sister joins her on the other side

No!  No!!

Not two dead

The little one, she does not deserve this

Bring her back!! Please bring her back!!

Interminable moments pass

Pictures are taken

Memories preserved

Then they climb back

Unharmed.

I can breathe again, but my head is reeling.
