# Rishi comes home from Debate by Nilay Mukherjee


So my son came home after 4 weeks at debate camp.
First, I thought he had become a stoic: because in response to my anxious questions about whether he missed home, he said: "No. But I don't miss camp either."

Next, I got all the bad news.

Someone had stolen a hundred dollars in cash from him, while he was in the shower. Ok. "How did it feel?" I ask. "I tried not to feel anything", he said. "But I was determined it would never happen again. I carried my stuff with me everywhere after that" Stoics are indifferent to the vicissitudes of fortune...... so not quite a stoic. Ok.

The glass front of his I-phone was shattered. It was in the backpack which was tossed around. But it still worked. I tried to hold on to my smile. I hadn't seen him in four weeks, I reminded myself.
He had packed his passport next to the toothpaste tube and now it was swimming in a pool of toothpaste. Hmm. I cleaned every page with a paper towel. Stay calm!

"All teachable moments," I consoled myself. But the hundred dollars still stung! Ouch! Remain calm!
"So what was the most important thing you learned at camp?" I asked. "That I should learn how to cook", he said in a deadpan voice."The food was horrible"

The boy is growing up, I thought. Good. Maybe he will learn the chicken tikka masala I have been wanting to teach him.

Next I got the details. There were two hours of lectures each morning: the basics of debating, philosophy, psychology, political ideology, policy etc. etc. Debate prep the rest of the time.
They told him about the Stanford experiment ( this is where they took volunteers, assigned half of them roles of prisoners and half as guards and ran the experiment for a few weeks until they were forced to shut it down because of the horrors that transpired). He now believes that we are all the product of our environment. There is no such thing as free will. Hmm. This can be a source of conversation later. I make a mental note of it.

We went to his favorite Italian place and he mixed the baked Ziti with the Chicken Parm and wolfed it down: I guess the food at camp was pretty bad.

He smiled for the camera. That's a first.

And all this while, I am looking for differences. Four weeks. That's a long time. Did he meet a girl at camp? Summer romance? But I didn't ask him.

"Did you watch any movies? Music?" I asked. "They forced us to watch Beauty and the Beast. I prepped for debate all through it". Ok, so much for romance.

He yawned. I took the hint. No more probing.

The boy had grown up. In ways I can't imagine and in ways I can't control. My role now, is to stand aside and wish him well.

Good luck son!