# Give me Knowledge by Nilay Mukherjee {-}


The buzzer rang harshly, splitting the early morning air in Ronodeep’s bedroom. He was already in a semi- conscious state, his mind racing. Later, he could not remember exactly what he was thinking about but the sense of urgency was unmistakable. He had things to do, places to be. This was not going to be a typical Saturday morning.

He reached over to silence the buzzer and got up, involuntarily clenching his muscles as he removed his blanket and stepped out of its warmth. His wife’s admonishment rang through his head as he brushed his teeth “I don’t understand why you have to rush out on a Saturday morning to cook for a bunch of people that you don’t even know?“ As usual, he had no intelligent answer, just an assurance in the depths of his gut that told him that this was a good thing to do.

Saraswati Pujo (Pujo means worship, Saraswati is the Hindu goddess of learning) brought back fond memories for Ronodeep.  This was the only Pujo that he was involved in organizing when he was growing up half way across the world in Kolkata. Durga Pujo, the pride and joy of Bengali existence, was too big of an affair to be left to the kids, but Saraswati Pujo was different. It could be done in one of the empty garages of his cooperative housing society and it did not cost too much money. Ronodeep remembered the month of excitement before the event itself: there were donations to be collected from the residents, plays written and rehearsed, poems to be memorized for the cultural function, decorations, food….so many things. And there was the juggling between the Pujo his dad performed in their apartment and the affair at the cooperative society. Recently, a friend had posted photographs from one of those events on Facebook. Ronodeep looked at them as if in a dream. He looked at a scrawny version of himself from 25 years ago hoisting the idol of Saraswati onto the van, posing proudly in front of the decorations he had helped put up. He saw younger versions of his friends. He remembered the fight he had had with the boy on the left who was now a professor at a respected university and the crush he had had on the girl on the right who was now into her third marriage (or so rumor had it: she was not on Facebook to confirm or deny it). Mostly Ronodeep remembered being giddy with a sense of purpose: he was involved in something greater than just himself, something that was somehow meaningful in a way he could not describe but the feeling was there and it felt good. Many years later, he wanted that feeling back and he hoped cooking Khichuri in Boston for 500 Bengali immigrants on a Saturday morning in January was going to do the trick.

He slipped out of the apartment quietly so as not to wake his wife and son. They were going to have a busy day and would try to make the Puja in the evening if they had time: he had a swim meet in the morning and then he was going to hook up with his buddy to play on the Wii. Not unlike many Bengali kids of his age, he had to get through an hour of math and half an hour of piano before he could have any contact with the Wii. Oh, and there was the essay he had to write on his recent trip to the Taj Mahal where he posed as a home grown Indian kid so he could skip the more expensive NRI (non- Resident Indian) lines.  She was going to chauffer him around while fielding phone calls from the hospital:  “Mr. Jones blood sugar is through the roof but he wants to leave AMA (against medical advice) because he wants to join his friends on a trip to Vegas.” Or the nurse could say: “Should we call a psych consult on 98 year old Mrs. Pierce who was admitted last night because a neighbor called 911 after he saw her sprawled across her yard. She has a broken hip but she wants to talk to Mr. Pierce before she consents to surgery. The only problem: Mr. Pierce died 10 years ago.” 

Ronodeep punched in the address of the school where the Pujo was being held on his GPS as the CD in his car stereo kicked in: Vedic Chants that George Harrison and Ravi Shankar had put together. The evocation of Saraswati was track number 2:
Ya kundendu tushar har dhabala
Ya sweta vastambrita
Ya veena vara danda mandita kara
Ya sweta padmasana
(Oh goddess, white as snow, dressed in white, veena in hand, seated on a white lotus: we bow down to thee)

As he turned into the parking lot of the school, he was surprised to see a lot of cars. It was eight o’ clock in the morning and he was expecting to be the first to arrive. Then he noticed a large kid struggle out of his car and head towards the gym. He was wearing a T-shirt: 2006 Wrestling Champion, Suffolk County. “Great!” Ronodeep thought. “There is another event going on. People were going to have a tough time finding parking today.”

As Ronodeep walked towards the entrance, he scanned the surroundings for Bengali faces. He was not expecting the average Bengali to show up this early: most people came just in time for Pushpanjali (flower offering) and lunch; but a couple of the organizers should be here unloading stuff from vans, carrying things into the kitchen etc.  As he entered the outer doors, he saw the welcome banner for the event stashed in a corner, waiting to be put up. “Good”, he thought, “Someone is here”. He followed the signs to the cafeteria and peeked in the kitchen. 

The kitchen was already busy. Ronodeep recognized Feluda, one of the organizers and moved towards him.  “Thank God you arrived!” Feluda said, clearly relieved. “You can start with the Khichuri. I am going to fry up the spices and mix the rice and the daal together. After that it is up to you. Please figure out how to get those pots going….. and talk to Rob” he said, as he rushed off munching compulsively on his paan and zarda.

Rob turned out to be a middle aged Caucasian man dressed in a green uniform with a matching cap covering his sandy blonde hair. He showed Ronodeep how the pots worked. It was a thrill for Ronodeep’s inquisitive mind and a chance to hark back to the principles he learnt in Thermodynamics 101 more than 20 years ago. First, there was the boiler that converted water into steam. Once the boiler pressure reached a certain level, you turned some valves to let the steam circle around two giant stainless steel pots. “Easily 100 gallons each” thought Ronodeep, staring into their depths in awe. He had never seen such large cooking vessels before. You could fill them up with water from a tap and there was a drain at the bottom as well. “Be careful with the filter that sits on the drain” warned Rob.  ” I know you Indians like to stir things vigorously. That can dislodge the filter. Then the drain gets clogged and we will have a problem.” He handed Ronodeep a giant, stainless steel spatula that looked like an oar. “Your stirrer”, he said with a smile” Get ready to use those muscles”.

The plan was simple. Feluda would fry up the spices (cumene seeds, ginger, cumene powder and habanera paste) in oil in a separate pot and mix it with 30 pounds of Basmati rice and 30 pounds of preroasted Moong Daal. Meanwhile Ronodeep was going to boil water in the two giant pots. Then the mixture of rice, Daal and spices would be divided and dropped into the two pots. There, they would cook for two hours with occasional stirring using the giant spatula. Ronodeep’s job was to make sure the bottom did not char and the mixture retained the desired consistency: not too thick and not too runny. Twenty minutes before the end, he would throw in pre-fried cauliflowers, potatoes and peas.  Salt and sugar would be stirred in as needed. Finally the yellow mush, the consistency of porridge, would be topped with two large tubs of clarified butter that someone had painstakingly made at home the day before and sprinkled with crushed cinnamon, cloves and cardamom. That concoction would feed 500 Bengalis that would assemble in a few hours, hoping for a taste of home-cooked Khichuri.

Rob turned out to be a talker. He chatted amiably with Ronodeep about his life. He was a cook for the county schools but he had leant his culinary skills in the Navy, which he joined right after high school. “You don’t really learn how to cook in the Navy”, he said. “You learn to follow orders. There is no room for creativity”. Being in the Navy had allowed him to travel the world and sample different cuisines. “I liked the food in Hong Kong”, he said. “But those guys eat some crazy stuff. I once tried some of their street food… couldn’t keep it down” He ended his story with a flourish, his eyes glittering, “But I love Basmati, man…. And those Indian spices… uh, uh, uh”  

Ronodeep had noticed her the moment he walked into the kitchen because she was the only one wearing a headscarf. As he talked with Rob, he noticed the quiet efficiency with which she went about cutting the eggplant into thin disks, each one roughly the same thickness. Ronodeep knew that was important because they would then be dipped in batter and deep fried a dozen at a time and it was important that they all be the same thickness so that they cook evenly. She noticed him looking at her and introduced herself. Her name was Farida Bibi. With typical disregard for the American reticence to inquire into the personal affairs of someone you have just met, she obtained details about Ronodeep’s family: how many years he has been married, how many kids he had etc. She was surprised that he had only one kid after being married for over ten years and expressed more surprise and perhaps a bit of disapproval when he told her that one was all he and his wife could manage to raise, given their hectic lifestyles. She was equally forthcoming about her own life: She was born in Faridpur but grew up in Khulna. She has been living in Cambridge for the last 20 years. Her husband was a cook’s helper at a Bangladeshi owned Indian restaurant and she had three kids. She helped the family finances by cooking for a few Indian families, catering a few parties and helping out at events like this. Her eldest son was on the verge of “standing on his own two feet”. “He will graduate next year with a chemical engineering degree”, she said with a smile that showed the kind of pride that only comes after a long, arduous but successful ordeal.

After Ronodeep had finished his duties in the kitchen, he took off his apron and walked out into the coolness of the cafeteria where the Puja was being held. The Purohit (priest) was a guy he had gone to school with in India.  The Purohit announced on the microphone that it was time for the very last Pushpanjali, so Ronodeep joined the stragglers in a flower offering to the goddess of learning. “Bidyang dehi namastute (give me knowledge, I salute you)” he chanted with the group. He knew the invocation by heart: he had repeated the same verse every year since he was a child but each time he said it, he still got goose bumps.  As a kid, he would excitedly throw the flowers at the feet of the deity but the rules were different in America: you patiently waited as a basket was passed around for you to put the flowers in.

After the Pushpanjali, Ronodeep sat near the deity, gazing at the Shola (papier mache) decorations behind the goddess Saraswati and inspecting the utensils of the Puja. The utensils were made from copper, just like the ones back home. He recalled how his mother would wash them with tamarind. The acid in the fruit removed the patina from the copper and they glowed in their warm, red, native color. He visualized his father teaching him the proper way to conduct a Puja after his Poite (sacred thread) ceremony when he was 14. He remembered how kids would put books in front of the deity, hoping for extra blessings from the goddess of learning. He smiled, remembering how often Math books were proffered.
Ronodeep was roused from his reverie by a young woman who asked him if he would take a picture of her family in front of the goddess. Ronodeep complied; making sure the frame included everyone and the goddess. They all perked up in fake, “say cheese” smiles for the three seconds it took for the camera to execute its routine: a series of red flashes to eliminate red eye followed by the big , final flash that coincided with the opening of the shutter. Ronodeep suddenly remembered that when he was a kid, no one smiled when their pictures were being taken.  He had recently looked at some photos of his third grade class that his friends had posted on Facebook and was struck at how serious everyone looked. He now looked on as several families went through the same routine: the women dressed in their finest sarees and gold ornaments, the men in kurta-pyjamas. They all exhibited the same fake-smile mannerism, showing teeth, perpetuating their momentary exuberance in digital format. “How things change over time”, Ronodeep thought as he looked with amusement at the procession of families. 

The families all had their backs to him and the deity: so Ronodeep got a ringside tour the latest fashions in women’s blouses from Kolkata. He marveled at the infinite variety. There was the conservative blouse: full sleeved and covering the entire back, that were generally favored by the older women. Then there were the more daring cuts that the younger women preferred: no sleeve, low cut to the back or open back tied with strings that crisscrossed in various patterns.  Ronodeep wanted to stare at this unexpected display of skin and wrestled with himself to look away.  His task was made easier when one woman showed up with a particularly exposed back that she had failed to apply any moisturizer to. “The danger of long, New England winters”, Ronodeep thought as he headed towards the Prasad and Khichuri lines.

At the Khichuri line, Ronodeep had the pleasure of standing next to a very professorial looking, middle aged Bengali man. He seemed to have been around the block a few times, perhaps he was a Puja organizer himself that lived in another state and was here visiting friends. He waved his hands at his captive audience, which included a couple of Caucasian men and women in Indian costumes, and held a long discourse:  “The Puja organizers face a very peculiar challenge with the Bengali diaspora,” he said. “While the Puja is essentially a religious occasion, the real reason why most Bengalis gather at these occasions is to socialize, eat and watch the star attractions of the cultural program, usually professional artistes from Kolkata.” 

“Is this guy a sociologist?” thought Ronodeep. 

The Professor continued. “The crowd materializes magically half an hour before the Pushpanjali followed by lunch. Then a lot of people leave and come back in the evening when the stars are performing. Then they proceed to eat dinner and leave.  Meanwhile the organizers are desperate to hold on to the crowd in the intervening period between lunch and dinner because that is when the kids and local artistes perform.  Various tricks have been tried: sit and draw competitions for the kids, raffles etc. but the basic truths are undeniable: 1) If you or your kid is not performing, there is very little incentive to stick around. 2) There are simply far too many Bengali and Indian cultural opportunities available in America in the 21st century that the novelty of a home- grown Bengali program is passé.”  

Ronodeep saw the merit of that explanation despite his annoyance at having to listen to this pompous man. He himself always stuck around for these cultural programs because he viewed this as an opportunity for furthering his own amateur, anthropological explorations. He had his own theories and they were similar. In the dazed state that often beset him when he was stuck in a line that is not moving, Ronodeep found himself lecturing in his own mind to himself, drawing out the explanation, as if speaking to kids that needed more detailed explanations than the one that had just been given. Maybe he needed more convincing to firm up his own beliefs. ”Back in the 70’s, when the first wave of Bengali immigrants landed on the shores of New England, these gatherings were of tremendous value. At that time, there were no Bengali stores to shop in, no Bengali movies to watch, no 24 hour Tara Bangla or other Bengali channels on TV. Telephone calls to India were in excess of two dollars a minute. Thus, the Bengali diaspora desperately clung to any reminder of their parent culture and occasions like these were a welcome change. The whole affair was also much smaller: a few families would get together and everybody knew everybody else at the Pujas. Thus the intimacy and novelty of the event more than made up for the lack of talent. Fast forward to 2011 and the scene is entirely different. The Pujas are much larger now and apart from some of the old timers, most of the attendees don’t know each other. There is simply no reason to watch some unknown kid fumble his way through Sukumar Ray’s Abol Tabol in a mostly empty auditorium when you could be watching Sachin Tendulkar score another century against England.” 
He was roused from his reverie by a sudden movement in the line: they had started serving lunch!  “Why then”, Ronodeep wondered as he viewed the bustle of activity in the front of the line,” is there so much jockeying for power at the cultural committees for these programs? Who gives a damn? And yet, some of these people act like their entire self worth depended on it. What strange combination of incentives and utter delusion can propel these people to control something that has clearly become irrelevant to so many of the very people that they are hoping to serve?” Ronodeep resolved to watch the organizers closely and study their reactions to get a glimpse of their truth.

He felt a tap at his elbow: “Are Ronodeep je? Onekdeen bade”. (After many moons, eh Ronodeep?) Ronodeep turned to face a bearded, smiling man, a man that was once much younger, had no beard and attended same college as Ronodeep. After the usual “blast from the past” reactions and enquiries about the fate of common friends that neither had bothered to keep in touch with, the conversation settled on the present. It turned out that Kishan, the now bearded, much older man than the one Ronodeep remembered, was settled in the area with a steady job and a 30 year mortgage. More interestingly, having hit the glass ceiling on his climb up the corporate ladder, Kishan has turned his attention to a smoldering passion from his youth: theater. Back in the day, Kishan performed street dramas, mostly organized as part of a protest rally of some sort by left leaning, student-led political organizations. There were many things to protest against and dreams of a new world where oppression and corruption would be a thing of the past was a unifying theme under which Kishan honed his thespian and directorial skills. In post modern USA, jaded with excesses of every kind including revolutionary approaches to theater, Kishan has turned his attention to exploring globalization issues as they affect the middle class Bengali community.  Ronodeep listened as Kishan animatedly explained his latest project. “I just want to start some meaningful conversations about who we are”, Kishan exclaimed.  

As the conversation progressed, Ronodeep became aware of Kishan’s frustrations in marketing his productions. “I tried to stage a few shows at places like this”, he grimaced as he waved his hand at the assembly of Bengalis, all hurrying to get a spot to sit and eat their lunch. “But the general public seems to only want the pulsating rhythms of Anyesha.  Between that and the screaming, ill-behaved children running amuck, there is no place for serious theater here. To top it all, the organizers only want to produce hackneyed reruns of Tagore musicals, that too under their own direction using their age old notions of theater. While Tagore is always relevant, it is time we focused on other things.” Kishan complained. Ronodeep learnt that Kishan now stages his shows to select, small audiences once or twice a year. Ronodeep promised to attend their next show and the two parted company after planning to sit next to each other at the cultural program that evening. “Jayga rakhis”, Kishan said, referring to the peculiar, sometimes disgusting tradition of throwing a garment over a chair to reserve a spot for him in the auditorium.

After Ronodeep had eaten his lunch of Khichuri, begun bhaja, labra and chutney, he changed out of his cook’s garb into the attire that his mother had gotten for him the last time she visited. It was a beautiful kameez: shining, black silk with delicate, white embroidery all along the edges with a matching churidaar and a very long dupatta with gold filigree work or “zari” as it is commonly known. Hritik Roshan had popularized this kind of dress and it was supposed to fit well on tall men. Ronodeep smiled to himself as he tied the knots of the churidaar string around his waist while holding up the long end of his kameez between his chin and chest, a maneuver he had learnt by watching an older cousin as a child. Was he really hoping that the long, sleek cut of the kameez was going to minimize the bulge in his middle? He looked in the mirror of the bathroom where he was changing, a hopeful glance. No, the gut was just as unflattering as before. “Exercise and portion control”, thought Ronodeep, even as he knew that portion control was not a possibility tonight: There was Illish mach and goat curry on the dinner menu.

The phone rang and Ronodeep answered mechanically without first checking to see who it was. It was Souren, who Ronodeep had known from a past life. Souren and Ronodeep had organized parties for the local Bengali population while they were together and had maintained contact over the years. “Are Ronodeepda”, Souren said even as Ronodeep could hear Souren’s one year old screaming in the background, ”I need your help with a quiz contest I am organizing for the Bengalis here”.

Quiz contests are a staple feature of the Bengali get together. Ronodeep had many fond memories of participating in these trivial pursuit/ jeopardy concoctions as a kid. The quiz master would pick the question out of a hat and read it aloud. Then teams would get a chance to answer. Meanwhile the audience was instructed not to shout out answers. Ronodeep remembered the many giddy moments when he knew the answer to a particular question and had to wait his turn, his excitement building while he combated the gnawing fear in his stomach that the previous team would answer it first. Later on, as an organizer of quiz contests, Ronodeep had quickly learnt that there were three types of questions. The first kind was the easy ones, the confidence builders: you had to ask them to get the crowd involved. Also, these included insider questions (like: Name the first president of our organization) that were highly favored by the organizers. Then there were the super hard, esoteric questions that nobody cared about (like: Name the structures that pass through the femoral triangle). If you had too many of those, the majority of people tuned you out very quickly. Every quiz master dreamed of the third kind of questions: the ones where most people go: “O my god…I should know the answer… it is on the tip of my tongue but I can’t think of it”. These generated the most excitement followed by “Ema, eta janeesh na!” (How come you don’t know this!) as soon as the answers were revealed.  

Ronodeep promised to help Souren and fielded another call from his wife: she was under the weather and could not make it. “No big surprise there”, Ronodeep thought after he hung up. He knew that she did not care for these occasions as much as he did. The headache was probably real but if she wanted to come, she could have taken an aspirin. He found her unwillingness to participate in these occasions equally strange as his willingness to be involved. As he wandered through the hallways looking at the people, noting what they were doing, Ronodeep could not help feel that this was all a dream. What was he really doing here? What was he here for?

The professor sociologist that Ronodeep had seen before was holding court, lecturing to a few people that had gathered around him. Ronodeep’s curiosity was peeked. “What is he talking about now?” he thought as he joined the group. It turned out that the lecture was on identity.
 “There are two main theories on identity,” the professor claimed.” One says that you are who you are and you spend the rest of your life discovering yourself. You make one mental construct after another about who you are, only to find out that they need to be modified over time based on new experiences. Finally you realize that you are only the “awareness of self”. Everything else; your body, mind, intellect are just constructs in themselves, constantly evolving in cause and effect relationships.” 
“Oh no”, thought Ronodeep, “a Vendantist!” 

Ronodeep wondered what the other theory was. The professor got around to it finally” The other theory is also a mental construct theory, except that your cognitive mind is in control.  You wear many hats: the Indian, the Bengali, the professional, the father, the son, the friend, the left handed spin bowler, the wearer of fancy kurtas and so on.” he said, eyeing Ronodeep’s kurta with a hint of envy. ”At any given time, based on the circumstances, you choose to exhibit one or more of these identities. So, on some level, you are who you choose to be”.  

“What are these circumstances?” Ronodeep could not help interjecting. 

“Well, that is a lecture in itself”, smiled the professor causing Ronodeep’s anxiety levels to go up. ”It’s like this”, he said.” Society as a whole or, at least, the influential groups in society has defined constructs for us, the so called bounds of normal behavior. It rewards those behaviors.  It also punishes the behavior of smaller groups with identities that it considers threatening by calling them aberrant behaviors. Thus society punishes criminals by putting them in jail, lunatics by putting them in mad houses, gay people by not giving them marriage rights etc. Some people have even suggested that women are punished by society for being aberrant from male behavior. Notice however, society does not punish all minorities. For example, it is OK to be a red head, because they are not perceived as threatening in any way.  As individuals living in society, we are aware of these boundaries. We then exhibit behavior within those boundaries that maximize our utility functions”. 

Ronodeep could only guess at what utility functions were but he did not ask for a clarification. Instead he pursued the circumstances issue.

“So you are saying that the same people will change their behavior depending on the circumstance based on what they feel is the best course of action for them?” 

The professor beamed.”Within limits, yes.” he said.

The professor’s lecture went on. “While a black man cannot obviously pass for a white man, a man or woman will change their behaviors based on what kind of scrutiny they are under. For example, if you are talking with your Indian or Bengali friends at home: even if you are conversing in English, you will drop in a few Indian words like arre and yaar, but you will change your accent and switch to corporate speak when you are talking to someone at work.  You might be extolling the virtues of being an Indian to your son, but if a politician approaches you with the obvious intention of getting your vote, you might actually resent it if he tries to suck up to you by praising your Indian identity. At a company picnic you might be a Republican while you could be rooting for Jyoti Basu on Apriler Poddo Path (the annual gathering of Bengali poets in the New England area).”

The professor’s lecture was cut short by the announcement that the cultural program was beginning. Ronodeep trooped into the auditorium and found his seat beside Kishan. Not surprisingly, the agenda was heavy on Rabindranath, 2011 being Tagore’s 150th birth anniversary.  There were poems recited, songs sung. There was even a program on the effects of foreign musical traditions on Rabindranath’s music. Ronodeep sat through the mostly amateurish performances and tried to look at the reactions of the audience. The organizers were up front cheering everything on, beating their own drums about how much effort it took to put everything together and how happy they were that everything was going so well. There were the rows of “ninduks” or those that were critical of the performances. Their complaints ranged from how good it used to be when they were in charge or how someone’s kid was unfairly dropped from the performance or how one organizer had snubbed one of the kids’ mothers and so on. There were some older people that just sat and watched, saying nothing. Ronodeep wondered what they were thinking. Then there were the people who ignored the whole program and chatted in loud voices wile they let their cell phones ring to tunes of the latest Bollywood hits. They were disturbing the proceedings but managed to remain completely oblivious about it. Finally there were the children, running around, getting on stage, being shooed off and returning again to claim some negative attention a few minutes later.

Ronodeep liked the program on the influence of foreign musical genres on Rabindranath’s songs. The narrative was tight and a group of singers sang the original song and the Rabindrasangeet that it inspired, one after the other. When he was a kid, Ronodeep’s mother had forced him to take music lessons and part of that training involved learning about how Rabindranath was inspired by different musical traditions.  In the program he was watching now, he recognized some of the examples and hummed the tunes to himself. On an impulse, Ronodeep turned to Kishan and whispered in his ear. ”These guys are doing a good job. It would have been nicer though, if they got the original song and played it back for us, instead of trying to sing it. The natural Bengali inflections of the singers make it sound like it was the Rabindrasangeet that inspired the foreign tune, not the other way around”. Kishan nodded and mumbled something that Ronodeep didn’t catch. Clearly, this was going to have to be a larger, more detailed conversation when they met again.

The final performance was from a visiting artiste from New Jersey who was also going to sing Rabindrasangeet. When she walked on stage, there was a collective gasp from the audience. Someone from behind commented: “Look at her dress. Is she singing Rabindrasangeet or is she Lady Gaga?” The comment was not out of place. The artiste wore knee length leather boots and had dyed her short hair in some unusual shade of brown with red highlights. Her singing was pretty good however. Ronodeep could not help comment to Kishan when she sang Shawana gogone ghoro ghanaghata: “I always picture Konika in a saree pumping a harmonium when I hear this song. It is slightly dizzying to hear Lady Gaga sing it, although she is doing a pretty good job at it.” Kishan smiled. Ronodeep could see his mind churning:  Kishan was thinking of a new angle, a provocative way of including this in his next theater production.

A couple of hours later, Ronodeep lightly undid the bolt on his front door as he crept into his sleeping household. As he undressed, his mind was full of the events of the day.  As he slid into the covers and waited for them to warm up, his mind drifted through all that he had seen and heard. Was he happy that he had done this? Did it make him feel closer to his roots? Was the feeling he had hoped for when he was jumping out of bed in the morning there? Was he going to do it again next year? As he drifted off to sleep, he could not find answers to these questions. Maybe this is who he was? Maybe that is the behavior he chose to exhibit because it maximized his utility function? It didn’t matter anymore. There were chores to be done tomorrow and he had better get some sleep. 

