# The World is what it is by Nilay Mukherjee {-}

The world is what it is: but some days we see a more unpleasant side of it: perhaps our internal lens is disturbed to begin with, so we notice it more.

I woke up in my plush hotel bed with a start. It was only 4 am and as I stared across the pristine white sheets of my king size bed, I was hit with how lonely an experience it was.

As I tried to exercise, the TV only brought more bad news. Some teenage girl had committed suicide: victim to incessant bullying. Some famous golf commentator: his 29-year-old son had died from a drug overdose. The strain on their faces were visible, as they tried to put a positive spin on things: "Let's learn from this so that it never happens again", etc. etc. I just wanted to scream!
People have no time for you. Everyone is busy, everyone is rushing. If you are blue: just figure it out and keep going. Right? You are rushing yourself.... you don't have time for anyone else. Quid pro quo. Right?

And then Facebook: normally a paragon of self-promotion and how good a time everyone is having, serves me this: A video of a hapless man and woman in rural India who have been caught cheating: they have been stripped naked and paraded: he is forced to carry her on his shoulders. He goes for a while, staggers, falls. They beat the fallen bodies with sticks. They get up, stagger, fall again, plead for mercy and finally go into a fetal position. I watch, fascinated and repelled by it all.

A group I belong to: their website has been violated by Turkish terrorists who have deleted all its contents and uploaded a banner: our administrator could not understand the language, but there was a gun being brandished and the tone was unmistakable. Damn! It never rains, but it pours.

"Will it ever get better?" I voice a silent prayer. "Is anyone listening?" And then this happens.

There is a childcare facility outside my hotel. As I check out and begin loading my car.... I hear a voice.

"Hi" it says. Its a baby voice, full of innocence and expectation.

It takes me a moment to figure it out. It is coming from the other side of the green fence my car is parked next to. It's owner is a little boy: barely two. I doubt if he can speak a full sentence. He just looks at me expectantly across the fence.

I look around and find a ball in the grass. In fact there were two. Somehow, the kid had managed to chuck it over the fence and wants it back. I remembered when my son would take everything to the balcony and toss it: watching with fascination as it crashed to the earth below.

"You want your ball back?" I asked.

"Umm hmm" said the kid, his face breaking into a smile. He had been waiting a while.

As I tossed the ball over the fence, he trotted off after it.

I could only imagine the happiness I have been lucky to distribute on this day. There is a God!... I want to say it before my natural cynicism takes over.

I hope everyone has a great day! Peace to all!

