# Urinal Etiquette by Nilay Mukherjee

So, I have a question to pose: primarily to men, because it involves a matter of etiquette in a place where women are not allowed (oooh.... interesting... please, feminists don't get upset, there are such places still in existence even today for very good reasons), but women are free to pitch in with their comments.

So, let me set it up. I go into the men's room at work (ha ha.... got you..... go find somewhere else to vent about unequal pay for equal work and other REAL issues) and there is a co-worker: lets call him John: who is already standing at the urinal. As soon as I approach the urinal next to him, he looks up and goes: Hey! 

I say: Hey!

and he goes
"Too nice of a day not to be outside, huh?"
and all this while I am hearing the steady stream hitting the ceramic.
"Umm... it is nice" I say.

John finishes his business and saunters over to the basins (yes... we wash our hands... most of the time!) and he is talking: like really running his mouth.

"They are predicting it will cool down tomorrow..... holy cow! There are actually paper towels in here... did someone pay off the paper lady? Ha ha......." and he saunters out.

Meanwhile, almost like a ghost, another employee, let's call him Dick....no that is not appropriate here.... .Harry.... : so Harry has somehow managed to appear out of nowhere and has occupied the urinal John was in. And ladies... .just for your benefit.... these are spaced about 3 feet apart with partitions that go about nipple-high: so, if you wanted you could take a quick peek, although why you would want to do that is a tough question to answer.

But here is the thing. Harry is facing away from me: as far as it is possible to face away from me and still aim within the boundaries of the ceramic. His entire demeanor exudes focus, intensity and a desire to be private. He is doing something serious! No room for banter, no time to talk about the weather. No! This is a man communicating with his inner being, holding his most precious possession in his hand and his razor-sharp attention and his pinpoint concentration will not be breached for trivialities like the weather. No no, no!

So here is the question. Is it polite to start a conversation when you walk in and someone is in the middle of doing their business? Are you going to startle him so much that an accident could happen? Can you slap him on the shoulder and say, How about them Yankees?.... wait... I know that would definitely cause an accident.... but here is the conundrum: Can you start up a conversation? Is it polite? Is this the civilized thing to do?

Only well considered, articulate answers please!
